### ISSUE TITLE
Vstest.Console.exe crash when running UWP test app. 

### ISSUE THREAD

**Issue by Baljitsingh2** [Microsoft/vstest#1030]
## Description
vstest.console crash when try to run test for UWP unit tests app.

## Steps to reproduce

1. Create a UWP Unit test app.
2. Add some Unit tests. 
3. Build the project
4. Create appx file using makeappx. 
5. Sign the appx from step 4 using signtool with dev certificate. 
6. Install the Dev certificate.  
7. Run "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" /Platform:x86 TestAppp_1.0.0.0_x86_Debug.appx

## Expected behavior
All the Unit test in the app are ran. 

## Actual behavior
vstest.console.exe crashes with following exception

Unhandled Exception: System.Runtime.CallbackException: A user callback threw an exception.  Check the exception stack and inner exception to determine the callback that failed. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: applicationName
   at Microsoft.VisualStudio.TestPlatform.ObjectModel.ValidateArg.NotNull[T](T arg, String parameterName)
   at Microsoft.VisualStudio.TestPlatform.Client.LocalCrashDumpUtilities.TryGetLocalCrashDumpPath(String applicationName, String& crashDumpPath)
   at Microsoft.VisualStudio.TestPlatform.Client.TestExecutorServiceClient.TryGetLocalCrashDumpPath(String applicationName, String& crashDumpPath)
   at Microsoft.VisualStudio.TestPlatform.Client.TestExecutorServiceClient.GetTestRunAbortedMessage(String executorProcessName, Int32 executorProcessId, Boolean hasExited, Boolean isRemoteExecution)
   at Microsoft.VisualStudio.TestPlatform.Client.TestExecutorServiceClient.TestExecutorServiceChannel_Reset(Object sender, EventArgs e)
   at System.ServiceModel.Channels.CommunicationObject.OnClosed()
   --- End of inner exception stack trace ---
   at System.ServiceModel.Channels.CommunicationObject.OnClosed()
   at System.ServiceModel.ServiceHostBase.OnClosed()
   at System.ServiceModel.ServiceHost.OnClosed()
   at System.ServiceModel.Channels.CommunicationObject.Close(TimeSpan timeout)
   at Microsoft.VisualStudio.TestPlatform.Client.UniversalTestExecutorProxy.Close()
   at Microsoft.VisualStudio.TestPlatform.Client.TestExecutorServiceClient.StarPlatformSpecificTestExecution(IPlatformTestExecutorClient platformTestExecutorClient, ITestExecutorLauncher launcher, Architecture targetPlatform, FrameworkVersion targetFramework)
   at Microsoft.VisualStudio.TestPlatform.Client.TestExecutorServiceClient.Initialize_NoLock(Architecture targetPlatform, FrameworkVersion targetFramework)
   at Microsoft.VisualStudio.TestPlatform.Client.TestExecutorServiceClient.EnsureInitialized(IDictionary`2 environmentVariables, TestExecutionContext context)
   at Microsoft.VisualStudio.TestPlatform.Client.TestExecutorServiceClient.<>c__DisplayClass18_0.<StartTestRun>b__0()
   at Microsoft.VisualStudio.TestPlatform.Client.TestExecutorServiceClient.InvokeTestExecutorServiceAction(Action action)
   at Microsoft.VisualStudio.TestPlatform.Client.TestExecutorServiceClient.StartTestRun(IEnumerable`1 sources, TestExecutionContext executionContext, String runSettings, IDictionary`2 environmentVariables, String dataCollectionServiceUri, ITestCaseLog testCaseLog, ITestRunLog testRunLog, IFrameworkHandleInternal frameworkHandle)
   at Microsoft.VisualStudio.TestPlatform.Client.Rocksteady.RocksteadyExecutionManager.StartTestRun(TestRunCriteria testRunCriteria, Boolean inIsolation, DataCollectionParameters dataCollectionParameters, ITestRunEventsHandler runEventsHandler)
   at Microsoft.VisualStudio.TestPlatform.Client.TestRunRequest.ExecuteAsync()
   at Microsoft.VisualStudio.TestPlatform.CommandLine.Processors.RunTestsArgumentProcessor.RunTests(IEnumerable`1 sources, String packageFullName, String deviceInfo, Boolean isPhoneAppx, Boolean isUniversalTestAppx)
   at Microsoft.VisualStudio.TestPlatform.CommandLine.Processors.RunTestsArgumentProcessor.ExecuteAppContainerSources(List`1 appContainerSources, String deviceInfo, Boolean isPhoneAppx)
   at Microsoft.VisualStudio.TestPlatform.CommandLine.Processors.RunTestsArgumentProcessor.Execute()
   at Microsoft.VisualStudio.TestPlatform.CommandLine.Executor.Execute(String[] args)
   at RockSteady.Program.Main(String[] args)

## Environment
OS -> Windows 10 Pro. OS build 15063.40 Version: 1703
vstest.console ->

**Comment by jamiegs** [comment]
I have also ran into this issue. Is there any sort of workaround for it?

**Comment by smadala** [comment]
@jamiegs @Baljitsingh2  same repro in VS 2017?

**Comment by Baljitsingh2** [comment]
I think

**Comment by Baljitsingh2** [comment]
If you run the test from Visual Studio they work.

**Comment by singhsarab** [comment]
@Baljitsingh2 
Your comment here is tad bit confusing, as it says the test run with Visual Studio, which is expected, right?

**Comment by Baljitsingh2** [comment]
@singhsarab 
yeah, the test running is visual studio is expected. 
@jamiegs  was asking if it the test are rurning in visual Stutio. I was answer his question.

**Comment by singhsarab** [comment]
@Baljitsingh2 Can we just close this issue in that case?

**Comment by sanjaydebnath** [comment]
@Baljitsingh2 Make sure in command prompt you are navigating to "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow" folder first before running the vstest.console.exe command

**Comment by sanjaydebnath** [comment]
Facing same issue.
![image](https://user-images.githubusercontent.com/28987981/33888168-45e35776-df72-11e7-9498-bfc6af28420c.png)

**Comment by singhsarab** [comment]
@sanjaydebnath are you also creating appx using makeappx tool ?

**Comment by singhsarab** [comment]
Leave a comment
