### ISSUE TITLE
Data Collector Errors Cause TRX Result to be Failed

### ISSUE THREAD

**Issue by hankweber** [microsoft/vstest#10391]
We have tests where all of the tests pass, but there are data collector errors which then cause the overall result of the trx file to be marked as failed. Is there a way to bypass this logic and treat data collector errors as warnings?

**Comment by nohwnd** [comment]
I don't think there is a generic option to treat all collector errors as warnings. Is there a specific collector that you are having problems with? Maybe they have an option for this.

**Comment by felixb-croesus** [comment]
I think I have the same thing here. I run a test suite twice (sequentially) firstly targeting net8.0, then net462. Locally everything works, trx files are created with no errors, but in my CI run Blame works fine on the first test run (net8.0) but crashes on net462 after every tests passed.

This is my dotnet setup:

`DotNetTest(s => s
                    .SetProjectFile(E2ETestsProjectFile)
                    .SetConfiguration(Configuration)
                    .EnableNoBuild()
                    .SetFramework("net8.0")
                    .SetLoggers("console;verbosity=detailed")
                    .SetProcessArgumentConfigurator(args => args.Add($"--blame-hang-timeout 5m --logger:trx;LogFileName={dateTimeNow}_net8_0_test_results.trx"))
                );

                DotNetTest(s => s
                    .SetProjectFile(E2ETestsProjectFile)
                    .SetConfiguration(Configuration)
                    .EnableNoBuild()
                    .SetFramework("net462")
                    .SetLoggers("console;verbosity=detailed")
                    .SetProcessArgumentConfigurator(args => args.Add($"--blame-hang-timeout 5m --logger:trx;LogFileName={dateTimeNow}_net462_test_results.trx"))
                );`

This is my error:

`22:31:41 [ERR] The active test run was aborted. Reason: Test host process crashed
 22:31:41 [DBG] Data collector 'Blame' message: The specified inactivity time of 5 minutes has elapsed. Collecting hang dumps from testhost and its child processes.
  Error: Data collector 'Blame' message: Data collector caught an exception of type 'System.IO.FileNotFoundException': 'Collect dump was enabled but no dump file was generated.'. More details: Blame: Collecting hang dump failed with error...
  22:31:41 [ERR] Data collector 'Blame' message: Data collector caught an exception of type 'System.IO.FileNotFoundException': 'Collect dump was enabled but no dump file was generated.'. More details: Blame: Collecting hang dump failed with error...
  22:31:41 [DBG] Data collector 'Blame' message: All tests finished running, Sequence file will not be generated.

  Error: Test Run Aborted.
  22:31:41 [ERR] Test Run Aborted.
  22:31:41 [DBG] Total tests: Unknown
  22:31:41 [DBG]      Passed: 7
  22:31:41 [DBG]  Total time: 6.2070 Minutes
  22:31:41 [DBG] Results File: /home/runner/work/Project/Tests/E2E/TestResults/20241106_222415_net462_test_results.trx`
 

So the trx is created, my 7 tests passed, but the test run is marked as failure. Am I missing something obvious?

NOTE: It was working fine when I only had one test run (only net8.0)

**Comment by felixb-croesus** [comment]
Activated the --diag option,

```
C:\Program Files\dotnet\sdk\8.0.403\Extensions\Microsoft.VisualStudio.TestPlatform.Extensions.Trx.TestLogger.dll
TpTrace Information: 0 : 44200, 1, 2024/11/07, 12:49:22.040, 6998447518136, vstest.console.dll, AssemblyResolver.AddSearchDirectories: Adding more searchDirectories C:\Program Files\dotnet\sdk\8.0.403\Extensions,C:\Program Files\dotnet\sdk\8.0.403
TpTrace Information: 0 : 44200, 1, 2024/11/07, 12:49:22.040, 6998447518491, vstest.console.dll, AssemblyResolver.AddSearchDirectories: Adding more searchDirectories C:\Program Files\dotnet\sdk\8.0.403\Extensions,C:\Program Files\dotnet\sdk\8.0.403
TpTrace Information: 0 : 44200, 1, 2024/11/07, 12:49:22.040, 6998447518711, vstest.console.dll, AssemblyResolver.AddSearchDirectories: Adding more searchDirectories C:\Program Files\dotnet\sdk\8.0.403\Extensions,C:\Program Files\dotnet\sdk\8.0.403
TpTrace Information: 0 : 44200, 1, 2024/11/07, 12:49:22.040, 6998447518922, vstest.console.dll, AssemblyResolver.AddSearchDirectories: Adding more searchDirectories C:\Program Files\dotnet\sdk\8.0.403\Extensions,C:\Program Files\dotnet\sdk\8.0.403
TpTrace Information: 0 : 44200, 1, 2024/11/07, 12:49:22.040, 6998447519132, vstest.console.dll, AssemblyResolver.AddSearchDirectories: Adding more searchDirectories C:\Program Files\dotnet\sdk\8.0.403\Extensions,C:\Program Files\dotnet\sdk\8.0.403
TpTrace Information: 0 : 44200, 1, 2024/11/07, 12:49:22.040, 6998447519395, vstest.console.dll, AssemblyResolver.AddSearchDirectories: Adding more searchDirectories C:\Program Files\dotnet\sdk\8.0.403\Extensions,C:\Program Files\dotnet\sdk\8.0.403
TpTrace Information: 0 : 44200, 1, 2024/11/07, 12:49:22.041, 6998447522213, vstest.console.dll, AssemblyResolver.OnResolve: Microsoft.Diagnostics.NETCore.Client: Resolving assembly.
TpTrace Information: 0 : 44200, 1, 2024/11/07, 12:49:22.041, 6998447522846, vstest.console.dll, AssemblyResolver.OnResolve: Microsoft.Diagnostics.NETCore.Client: Searching in: 'C:\Program Files\dotnet\sdk\8.0.403\Extensions'.
TpTrace Information: 0 : 44200, 1, 2024/11/07, 12:49:22.055, 6998447667485, vstest.console.dll, AssemblyResolver.OnResolve: Microsoft.Diagnostics.NETCore.Client: Loading assembly 'C:\Program Files\dotnet\sdk\8.0.403\Extensions\Microsoft.Diagnostics.NETCore.Client.dll'.
TpTrace Information: 0 : 44200, 1, 2024/11/07, 12:49:22.057, 6998447690020, vstest.console.dll, AssemblyResolver.OnResolve: Resolved assembly: Microsoft.Diagnostics.NETCore.Client, from path: C:\Program Files\dotnet\sdk\8.0.403\Extensions\Microsoft.Diagnostics.NETCore.Client.dll
TpTrace Verbose: 0 : 44200, 1, 2024/11/07, 12:49:22.062, 6998447731743, vstest.console.dll, MetadataReaderExtensionsHelper: Discovering extensions inside assembly 'Microsoft.Diagnostics.NETCore.Client, Version=0.2.10.30701, Culture=neutral, PublicKeyToken=31bf3856ad364e35' file path 'C:\Program Files\dotnet\sdk\8.0.403\Extensions\Microsoft.Diagnostics.NETCore.Client.dll'
TpTrace Information: 0 : 44200, 1, 2024/11/07, 12:49:22.073, 6998447850172, vstest.console.dll, AssemblyResolver.OnResolve: Microsoft.Bcl.AsyncInterfaces: Resolving assembly.
TpTrace Information: 0 : 44200, 1, 2024/11/07, 12:49:22.074, 6998447851901, vstest.console.dll, AssemblyResolver.OnResolve: Microsoft.Bcl.AsyncInterfaces: Searching in: 'C:\Program Files\dotnet\sdk\8.0.403\Extensions'.
TpTrace Information: 0 : 44200, 1, 2024/11/07, 12:49:22.074, 6998447854761, vstest.console.dll, AssemblyResolver.OnResolve: Microsoft.Bcl.AsyncInterfaces: Assembly path does not exist: 'C:\Program Files\dotnet\sdk\8.0.403\Extensions\Microsoft.Bcl.AsyncInterfaces.dll', returning.
TpTrace Information: 0 : 44200, 1, 2024/11/07, 12:49:22.074, 6998447856841, vstest.console.dll, AssemblyResolver.OnResolve: Microsoft.Bcl.AsyncInterfaces: Assembly path does not exist: 'C:\Program Files\dotnet\sdk\8.0.403\Extensions\Microsoft.Bcl.AsyncInterfaces.exe', returning.
TpTrace Information: 0 : 44200, 1, 2024/11/07, 12:49:22.074, 6998447857780, vstest.console.dll, AssemblyResolver.OnResolve: Microsoft.Bcl.AsyncInterfaces: Searching in: 'C:\Program Files\dotnet\sdk\8.0.403'.
TpTrace Information: 0 : 44200, 1, 2024/11/07, 12:49:22.074, 6998447860085, vstest.console.dll, AssemblyResolver.OnResolve: Microsoft.Bcl.AsyncInterfaces: Assembly path does not exist: 'C:\Program Files\dotnet\sdk\8.0.403\Microsoft.Bcl.AsyncInterfaces.dll', returning.
TpTrace Information: 0 : 44200, 1, 2024/11/07, 12:49:22.075, 6998447862134, vstest.console.dll, AssemblyResolver.OnResolve: Microsoft.Bcl.AsyncInterfaces: Assembly path does not exist: 'C:\Program Files\dotnet\sdk\8.0.403\Microsoft.Bcl.AsyncInterfaces.exe', returning.
TpTrace Information: 0 : 44200, 1, 2024/11/07, 12:49:22.075, 6998447862873, vstest.console.dll, AssemblyResolver.OnResolve: Microsoft.Bcl.AsyncInterfaces: Failed to load assembly.
TpTrace Verbose: 0 : 44200, 1, 2024/11/07, 12:49:22.075, 6998447863694, vstest.console.dll, CurrentDomainAssemblyResolve: Resolving assembly 'Microsoft.Bcl.AsyncInterfaces'.
TpTrace Information: 0 : 44200, 1, 2024/11/07, 12:49:22.075, 6998447865019, vstest.console.dll, AssemblyResolver.OnResolve: Microsoft.Bcl.AsyncInterfaces: Resolving assembly.
TpTrace Information: 0 : 44200, 1, 2024/11/07, 12:49:22.075, 6998447865797, vstest.console.dll, AssemblyResolver.OnResolve: Microsoft.Bcl.AsyncInterfaces: Resolved from cache.
TpTrace Verbose: 0 : 44200, 1, 2024/11/07, 12:49:22.075, 6998447866282, vstest.console.dll, CurrentDomainAssemblyResolve: Resolving assembly 'Microsoft.Bcl.AsyncInterfaces'.
TpTrace Verbose: 0 : 44200, 1, 2024/11/07, 12:49:22.075, 6998447867457, vstest.console.dll, CurrentDomainAssemblyResolve: Failed to resolve assembly 'Microsoft.Bcl.AsyncInterfaces'.
TpTrace Verbose: 0 : 44200, 1, 2024/11/07, 12:49:22.079, 6998447905197, vstest.console.dll, CurrentDomainAssemblyResolve: Failed to resolve assembly 'Microsoft.Bcl.AsyncInterfaces'.
```

And the interesting part:

```
TpTrace Warning: 0 : 44200, 1, 2024/11/07, 12:49:22.098, 6998448100328, vstest.console.dll, TestPluginDiscoverer: Failed to get types from assembly 'Microsoft.Diagnostics.NETCore.Client, Version=0.2.10.30701, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Error: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The specified file is not found.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at Microsoft.VisualStudio.TestPlatform.Common.ExtensionFramework.TestPluginDiscoverer.GetTestExtensionsFromAssembly[TPluginInfo,TExtension](Assembly assembly, Dictionary`2 pluginInfos, String filePath) in /_/src/Microsoft.TestPlatform.Common/ExtensionFramework/TestPluginDiscoverer.cs:line 158
```

**Comment by felixb-croesus** [comment]
@nohwnd Would you like that I create a new issue? Or do you need more info? Thank you! :)

**Comment by nohwnd** [comment]
## Triage Analysis 🤖

I located the relevant code that causes this behavior in `TrxLogger.cs`:

```csharp
case TestMessageLevel.Error:
    TestResultOutcome = TrxLoggerObjectModel.TestOutcome.Failed;  // <-- This is the problem
    runMessage = new RunInfo(e.Message, null, Environment.MachineName, TrxLoggerObjectModel.TestOutcome.Error);
    _runLevelErrorsAndWarnings.Add(runMessage);
    break;
```

When **any** error-level message is received — including data collector errors — the `TestResultOutcome` is immediately set to `Failed`. There is no distinction between test failures and infrastructure/collector errors.

### Root Cause

The `TestMessageHandler` treats all `TestMessageLevel.Error` messages equally. Data collector errors come through this same path, which is why a collector error marks the run as failed even when all tests pass.

### Design Consideration

This behavior is intentional in the sense that data collector errors can indicate corrupted or incomplete coverage/blame data — silently ignoring them could lead to misleading results. However, users who have partial-failure tolerance (e.g., intermittent collector issues in CI) have a valid use case for treating these as non-fatal.

A potential fix would be to:
1. Add a new logger parameter (e.g., `TreatCollectorErrorsAsWarnings=true`) that changes the behavior for collector-originated error messages
2. Or distinguish between data collector error messages and other errors in `TestMessageHandler`

This requires a design decision about the API surface. Tagging for maintainer consideration.

**Workaround**: Currently there is no built-in workaround via the TRX logger. You might consider post-processing the TRX file to remove or downgrade the `ResultSummary` outcome, or using a custom logger.



> 🔍 *Triaged by [Issue Repro Triage & Auto-Fix 🔍](https://github.com/microsoft/vstest/actions/runs/25948865021)*

**Comment by nohwnd** [comment]
## 🤖 Automated Fix Submitted

I've implemented a fix for this issue and submitted a PR.

**Root cause:** In `TrxLogger.TestMessageHandler`, the `case TestMessageLevel.Error:` branch unconditionally sets `TestResultOutcome = Failed`. Data collector errors arrive as `TestMessageLevel.Error` messages, causing the TRX outcome to be marked `Failed` even when all tests pass.

**Fix:** Added a new `TreatErrorMessagesAsWarnings` logger parameter. When set to `true`, error-level messages no longer affect the TRX outcome.

**Usage:**
```
dotnet test ... --logger "trx;TreatErrorMessagesAsWarnings=true"
# or
vstest.console.exe ... /logger:"trx;TreatErrorMessagesAsWarnings=true"
```

Error messages are still recorded in the TRX file's `ErrorInfo` section — they are not silenced, just excluded from the pass/fail determination.

The default behavior is unchanged (backward compatible).



> 🔍 *Triaged by [Issue Repro Triage & Auto-Fix 🔍](https://github.com/microsoft/vstest/actions/runs/27280507487)*

**Comment by nohwnd** [comment]
## ✅ Fix Merged

PR [#16106](https://github.com/microsoft/vstest/pull/16106) was merged on June 12, 2026. The fix is now available in the codebase.

### What was added

A new `TreatErrorMessagesAsWarnings` parameter for the TRX logger. When set to `true`, error-level run messages (including data collector errors) no longer mark the TRX outcome as `Failed` — the outcome will reflect actual test results instead.

### Usage

```
dotnet test ... --logger "trx;TreatErrorMessagesAsWarnings=true"
```

or with vstest.console:

```
vstest.console.exe ... /logger:"trx;TreatErrorMessagesAsWarnings=true"
```

Error messages are still recorded in the TRX file's `ErrorInfo` section — they are not silenced, only excluded from the pass/fail determination. The default behavior is unchanged (backward compatible).



> 🔍 *Triaged by [Issue Repro Triage & Auto-Fix 🔍](https://github.com/microsoft/vstest/actions/runs/28322973169)*



> 🔍 *Triaged by [Issue Repro Triage & Auto-Fix 🔍](https://github.com/microsoft/vstest/actions/runs/28322973169)*

**Comment by nohwnd** [comment]
## ✅ Fix Available — Suggest Closing

A quick status update: the fix for this issue (PR [#16106](https://github.com/microsoft/vstest/pull/16106)) was merged on **June 12, 2026** and is available in the latest release.

The `TreatErrorMessagesAsWarnings` parameter lets you prevent data collector errors from marking the TRX outcome as failed:

```
dotnet test ... --logger "trx;TreatErrorMessagesAsWarnings=true"
```

Error messages are still recorded in the TRX file — they are not silenced, just excluded from the pass/fail determination. Default behavior is unchanged.

Could you confirm whether this resolves your scenario so the issue can be closed?

> 🔍 *Triaged by [Issue Repro Triage & Auto-Fix 🔍](https://github.com/microsoft/vstest/actions/runs/28796122297)*



> 🔍 *Triaged by [Issue Repro Triage & Auto-Fix 🔍](https://github.com/microsoft/vstest/actions/runs/28796122297)*

**Comment by nohwnd** [comment]
Closing this as completed by [microsoft/vstest#16106](https://github.com/microsoft/vstest/pull/16106). The `TreatErrorMessagesAsWarnings` parameter is available in the latest release. Please open a new issue with a small repro if this does not cover your scenario.

🤖
