### ISSUE TITLE
17.11+ System.IO.IOException: Connection forcibly closed by remote host

### ISSUE THREAD

**Issue by Sterlinghv** [microsoft/vstest#10402]
### Issue Description

After upgrading `Microsoft.NET.Test.Sdk` from version `17.10.0` to `17.11.0`, our AzureDevOps test pipeline task encounters a `System.IO.IOException` at the very beginning of the run.

### Steps to Reproduce

Use `Microsoft.NET.Test.Sdk` version `17.11.0` or above
Run `dotnet test` via the `DotNetCoreCLI@2` in an AzureDevOps pipeline:
```
  - task: DotNetCoreCLI@2
    displayName: dotnet test
    inputs:
      command: test
      projects: <project solution>
```

### Expected Behavior
Test run as expected with no IO exception at the start

###  Actual Behavior

Error seen in the AzureDevops test pipeline log:
```
System.IO.IOException: Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host..
 ---> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.BufferedStream.Flush()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.SocketCommunicationManager.WriteAndFlushToChannel(String rawMessage) in /_/src/Microsoft.TestPlatform.CommunicationUtilities/SocketCommunicationManager.cs:line 413
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.DataCollection.DataCollectionRequestSender.SendAfterTestRunEndAndGetResult(ITestMessageEventHandler runEventsHandler, Boolean isCancelled) in /_/src/Microsoft.TestPlatform.CommunicationUtilities/DataCollectionRequestSender.cs:line 155
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.DataCollection.ProxyDataCollectionManager.<>c__DisplayClass20_0.<AfterTestRunEnd>b__0() in /_/src/Microsoft.TestPlatform.CrossPlatEngine/DataCollection/ProxyDataCollectionManager.cs:line 155
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.DataCollection.ProxyDataCollectionManager.InvokeDataCollectionServiceAction(Action action, ITestMessageEventHandler runEventsHandler) in /_/src/Microsoft.TestPlatform.CrossPlatEngine/DataCollection/ProxyDataCollectionManager.cs:line 288
```

### Environment
Windows Server 2016 inside a AzureDevOps agent pipeline job

### Additional Notes
This is not happening on version `17.10.0` or presumably earlier. Seems to be happening at [ProxyDataCollectionManager.cs ](https://github.com/microsoft/vstest/blob/main/src/Microsoft.TestPlatform.CrossPlatEngine/DataCollection/ProxyDataCollectionManager.cs) line 288

I'm not sure what is trying to be written/connected when the issue happens

**Comment by nohwnd** [comment]
Hello, this error is a red herring, it means that the other process died unexpectedly. Please collect diagnostic logs and post them here: 

https://github.com/Microsoft/vstest/blob/main/docs/diagnose.md

Or if they contain private information, please create a visual studio feedback issue and upload them there, you can share logs there privately. 

If you are unable to share them, please look into the *.host.*.log for exceptions. Please start from the bottom, it should be the last exception that happens. OR if you see just heartbeat and then the process dies, then it was killed externally.

**Comment by srikcgaa2** [comment]
@nohwnd I can confirm that this error appears after I upgraded the version from 17.9.0 to 17.11.1 when this error does not appear before the update with same set of test cases

**Comment by nohwnd** [comment]
Can you provide the diag logs I was asking for above?

**Comment by srikcgaa2** [comment]
Today I was also able to see that with 17.10.0, this exception did not occur on the same branch.

**Comment by v-mykhalchuk** [comment]
Hello
We are seeing same issue when running 'dotnet test' in ADO pipeline job.

**Comment by v-mykhalchuk** [comment]
hey @nohwnd 
can you please confirm if above is helpful or if I should continue chasing the diag logs even though there seem to be nothing apparently pointing to an issue?

**Comment by nohwnd** [comment]
If you are unable to share the log, this is what I would do:

1) find log for the testhost or testhosts that are crashing. typically in the main log (the one that does not have *.host.* or *.datacollector.* in name, you can search for "exitcode:", and see which testhost exited with non-zero exit code. There will be PID of the testhost, and you can find the respective log by that, and correlate the data collector log by that as well.

There probably will be empty entry for errorMessage, under this log, meaning that we did not capture any error output from the testhost because it crashed. (Sometimes you can find error there for example for missing runtime version, or similar).

In the testhost log I go to the last lines and check if there are some closing lines saying: terminating or similar. If there are the testhost terminated on purpose, if not and the log just ends in the middle of work, it crashed. 

then I look into the datacollector log, to see if code coverage was enabled for this project, if yes, code coverage is often to blame for the crash due to access violation exception. If not I typically try to make a memory dump of the process to see how it crashed. 

for that you would need --blame-crash , if this is on windows and net framework please also install procdump to your path, e.g. via chocolatey.

**Comment by v-mykhalchuk** [comment]
@nohwnd based on [my findings above](https://github.com/microsoft/vstest/issues/10402#issuecomment-2970546056), code coverage is indeed involved into this, as changing it's settings seem to make the issue go away.

**Comment by v-mykhalchuk** [comment]
@nohwnd @fhnaseer quick sweep through windows event logs found that testhost.exe crashed:
```
Application: testhost.exe 
CoreCLR Version: 8.0.1725.26602 .NET Version: 8.0.17 
Description: The process was terminated due to an unhandled exception. 
Exception Info: System.ObjectDisposedException: Cannot access a disposed object. Object name: 'System.Net.Sockets.NetworkStream'. 
at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 count) 
at System.IO.BufferedStream.Flush() at System.IO.BufferedStream.Dispose(Boolean disposing) 
at System.IO.Stream.Close() 
at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.SocketCommunicationManager.StopClient() in /_/src/Microsoft.TestPlatform.CommunicationUtilities/SocketCommunicationManager.cs:line 237 
at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.DataCollectionTestCaseEventSender.Close() in /_/src/Microsoft.TestPlatform.CommunicationUtilities/DataCollectionTestCaseEventSender.cs:line 78 
at Microsoft.VisualStudio.TestPlatform.TestHost.DefaultEngineInvoker.Invoke(IDictionary`2 argsDictionary) in /_/src/testhost.x86/DefaultEngineInvoker.cs:line 166 
at Microsoft.VisualStudio.TestPlatform.TestHost.Program.Run(String[] args, UiLanguageOverride uiLanguageOverride) in /_/src/testhost.x86/Program.cs:line 65 
at Microsoft.VisualStudio.TestPlatform.TestHost.Program.Run(String[] args) in /_/src/testhost.x86/Program.cs:line 54 
at Microsoft.VisualStudio.TestPlatform.TestHost.Program.Main(String[] args) in /_/src/testhost.x86/Program.cs:line 37  
```

Also, from what I see, the coverage was reported successfully, and it may have indeed crashed upon shutdown after all the work was actually done.

**Comment by fhnaseer** [comment]
@v-mykhalchuk Do you see any errors in `.datacollector.` log file? Can you repro the issue by collecting coverage for only one project?

`dotnet test something.csproj --collect "Code Coverage"`

**Comment by fhnaseer** [comment]
Assembly size seems fine to me. Maybe something else is failing. Without looking at code coverage logs it is hard to say what's going wrong here. Code coverage logs are available in `.datacollector.` file.

You can enable full logging by updating these settings as well.

```xml
 <RunSettings>
  <DataCollectionRunSettings>
    <DataCollectors>
      <DataCollector friendlyName="Code Coverage" uri="datacollector://Microsoft/CodeCoverage/2.0" assemblyQualifiedName="Microsoft.VisualStudio.Coverage.DynamicCoverageDataCollector, Microsoft.VisualStudio.TraceCollector">
        <Configuration>
          <CoverageLogLevel>Dumps</CoverageLogLevel>
          <InstrumentationLogLevel>Dumps</InstrumentationLogLevel>
          <ManagedVanguardLogLevel>Verbose</ManagedVanguardLogLevel>
          <CoverageFileLogPath>C:\LogFolder\</CoverageFileLogPath>
          <PerTestCodeCoverage>False</PerTestCodeCoverage>
          <CodeCoverage>
            <FileLogPath>C:\LogFolder\</FileLogPath>
            <LogLevel>All</LogLevel>
            <DumpStaticNativeDisassembly>true</DumpStaticNativeDisassembly>
          </CodeCoverage>
        </Configuration>
      </DataCollector>
    </DataCollectors>
  </DataCollectionRunSettings>
</RunSettings>
```

Also, you can create a ticket here and can share logs in a secure way. https://developercommunity.visualstudio.com/VisualStudio

**Comment by v-mykhalchuk** [comment]
@fhnaseer silly question - where I would find/configure the folder VSTest.MSTest.Tests ?
I was assuming that will be our results directory folder (the one specified with --results-directory), but I can't seem to find the files like these.

**Comment by v-mykhalchuk** [comment]
@fhnaseer handed over the logs to you in a different channel. Those contain many files because those are related to full test run on our solution. The issue does not reproduce if we reduce the scope for the test run that's why we have a lot of stuff going on there.
Also I have included an ADO task log for the run that failed.

Please let me know if you need any additional details on that.
