### ISSUE TITLE
VSTest Blame dump failes with "Could not load file or assembly 'NuGet.Frameworks'"

### ISSUE THREAD

**Issue by dotMorten** [microsoft/vstest#10419]
I have a test run that occasionally crashes. I run with with the /blame parameter. This works great on my x64 and x86 test runs, but on our ARM64 test run, I always end up with the following:
```
Data collector 'Blame' message: Could not start process dump: System.IO.FileNotFoundException: Could not load file or assembly 'NuGet.Frameworks, Version=6.5.0.154, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
File name: 'NuGet.Frameworks, Version=6.5.0.154, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at Microsoft.TestPlatform.Extensions.BlameDataCollector.CrashDumperFactory.Create(String targetFramework)
   at Microsoft.TestPlatform.Extensions.BlameDataCollector.ProcessDumpUtility.StartTriggerBasedProcessDump(Int32 processId, String testResultsDirectory, Boolean isFullDump, String targetFramework, Boolean collectAlways, Action`1 logWarning) in /_/src/Microsoft.TestPlatform.Extensions.BlameDataCollector/ProcessDumpUtility.cs:line 104
   at Microsoft.TestPlatform.Extensions.BlameDataCollector.BlameCollector.TestHostLaunchedHandler(Object sender, TestHostLaunchedEventArgs args) in /_/src/Microsoft.TestPlatform.Extensions.BlameDataCollector/BlameCollector.cs:line 645
```

Test run is started with vstest.console using the parameter `"BLAMEPARAM=--Blame:CollectDump;CollectAlways=false;DumpType=full"` and `%PROCDUMP_PATH%` pointing to a path with procdump for all 3 process architectures (including ARM64)

**Comment by nohwnd** [comment]
Please show me the version that is printed in dotnet test when you run it (assuming this is coming from `dotnet test`), I am trying to figure out in which version this is happening. Nuget.Frameworks used to be a dependency of vstest, but it is not anymore, so maybe something somewhere was not removed correctly.

**Comment by dotMorten** [comment]
This is not `dotnet test` but as shown above `vstest.console.exe`

**Comment by nohwnd** [comment]
Yes, I am blind. I will have to stage arm64 machine for this, and I will be able to do that on monday at earliest.

**Comment by nohwnd** [comment]
## Triage Analysis 🤖

The `NuGet.Frameworks, Version=6.5.0.154` error is a strong indicator that an **older version of vstest** is being used.

### Root Cause

`NuGet.Frameworks` was a direct dependency of vstest in older versions (it was referenced externally as `NuGet.Frameworks.dll`). It has since been **internalized** — the framework parsing code is now compiled directly into `Microsoft.VisualStudio.TestPlatform.ObjectModel.dll` as the `NuGetClone.Frameworks` namespace, with no external `NuGet.Frameworks.dll` required.

The current `BlameDataCollector` project has **zero references** to the `NuGet.Frameworks` NuGet package. The error you're seeing means the `BlameDataCollector.dll` being loaded is from an older vstest version that still references the external DLL.

### Why ARM64?

When running `/Platform:ARM64` with `vstest.console.exe`, the test host process may be loaded from a different directory than the main vstest.console.exe (an ARM64-specific host). That alternate path may contain older vstest binaries (from a prior installation or from a VS extension cache) where `BlameDataCollector.dll` still expects `NuGet.Frameworks.dll`.

### Suggested Investigation

1. **Check the vstest version**: What version of vstest are you using? Run `vstest.console.exe` without arguments — it prints the version.
2. **Check the BlameDataCollector source**: The stack trace shows the file path `/_/src/Microsoft.TestPlatform.Extensions.BlameDataCollector/...` — this is a build artifact path. Can you share the full path to the `vstest.console.exe` and the `BlameDataCollector.dll` being loaded?
3. **Try updating VS**: If you're using VS-bundled vstest, update to the latest Visual Studio version. The current vstest (18.x) does not require `NuGet.Frameworks.dll`.
4. **Try the SDK's vstest**: Use `dotnet test` with `--blame-crash` instead of `vstest.console.exe --Blame:CollectDump` to ensure you're using the SDK-bundled vstest.

### Workaround

If updating isn't immediately possible, check the ARM64 test host directory (the path with `ARM64` in it under the vstest extensions folder) and ensure it doesn't contain an old `BlameDataCollector.dll` that was left from a previous install.

> 🔍 *Triaged by [Issue Repro Triage & Auto-Fix 🔍](https://github.com/microsoft/vstest/actions/runs/26348460730)*



> 🔍 *Triaged by [Issue Repro Triage & Auto-Fix 🔍](https://github.com/microsoft/vstest/actions/runs/26348460730)*
