### ISSUE TITLE
EndOfStreamException on Linux

### ISSUE THREAD

**Issue by chlowell** [Microsoft/vstest#1069]
## Description
I have a `netcoreapp2.0` NUnit project whose tests run on Windows but almost always crash `vstest.console` on Linux.

## Steps to reproduce
1. `git clone https://github.com/chlowell/logging-log4net.git --single-branch --branch netstandard2`
2. `dotnet test logging-log4net/tests/src/log4net.Tests.csproj`

## Expected behavior
I expect the test run to complete, as it does on Windows:
```console
$ dotnet test logging-log4net/tests/src/log4net.Tests.csproj
...
NUnit3TestExecutor converted 169 of 169 NUnit test cases
...
NUnit Adapter 3.8.0.0: Test execution complete

Total tests: 169. Passed: 164. Failed: 0. Skipped: 5.
Test Run Successful.
```

## Actual 

Only Linux, test runs very rarely complete. Typically only 55 or 46 tests execute:
```console
$ dotnet test logging-log4net/tests/src/log4net.Tests.csproj
...
NUnit3TestExecutor converted 169 of 169 NUnit test cases
...
The active test run was aborted. Reason:

Total tests: 55. Passed: 49. Failed: 1. Skipped: 5.
Test Run Failed.
```

The diagnostic log contains an exception stack:
```console
TpTrace Error: 0 : 1982, 4, 2017/09/08, 21:27:17.815, 803697545800, vstest.console.dll, SocketCommunicationManager ReceiveMessage: failed to receive message System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.__Error.EndOfFile()
   at System.IO.BinaryReader.ReadByte()
   at System.IO.BinaryReader.Read7BitEncodedInt()
   at System.IO.BinaryReader.ReadString()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.SocketCommunicationManager.TryReceiveRawMessage(CancellationToken cancellationToken)
```

## Environment
Debian-based Linux

**Comment by codito** [comment]
@chlowell thank you for reporting the issue. Can you please share `log.host.*.txt` diagnostics file? It will have details if the host crashed during the test run.

**Comment by chlowell** [comment]
@codito Sure, [here it is](https://gist.github.com/chlowell/9fd4b493d8552175243f6af97c58e823).

**Comment by chlowell** [comment]
Has this been investigated yet?

**Comment by chlowell** [comment]
@codito Any updates here?

**Comment by himanshukandwal** [comment]
I am also getting the same error. 

Test module csprpj file content:

```
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.3.0-preview-20170628-02" />
    <PackageReference Include="xunit" Version="2.2.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.2.0" />
  </ItemGroup>
```

**Comment by StephaneAskardjian** [comment]
I have exactly the same issue here.
I noticed that if I start the tests one by one using --Tests option, they all run properly under linux.

**Comment by StephaneAskardjian** [comment]
Any update about this bug ?
Is there any ETA for a fix ?
Thanks.

**Comment by smadala** [comment]
@chlowell @himanshukandwal @StephaneAskardjian Apologies for kept you hanging.  I suspect EndOfStreamException is not actual issue, The EndOfStreamException can occur in vstest.console process (testhost processes orchestrator) when the testhost process (In which tests run) crashes. It is possible a test or group of tests(in particular series) execution causing testhost processes to crash. You can find the test name/sequence of tests names by using `--blame` option. Which is available in dotnet sdk >= 2.1.0-preview1-007186. 

While using `--blame`, you might face https://github.com/Microsoft/vstest/issues/1169.(Workaround: https://github.com/Microsoft/vstest/issues/1169#issuecomment-334447802 )

Below is example how to find test which cause stackoverflow.
```
vstest@VSs-MacBook-Pro.local:~/samadala/issues/vstest-1069/sof_proj$dotnet test
Build started, please wait...
Build completed.

Test run for /Users/vstest/samadala/issues/vstest-1069/sof_proj/bin/Debug/netcoreapp20/sof_proj.dll(.NETCoreApp,Version=v2.0)
Microsoft (R) Test Execution Command Line Tool Version 15.5.0-preview-20170810-02
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
The active test run was aborted. Reason: Process is terminating due to StackOverflowException.


vstest@VSs-MacBook-Pro.local:~/samadala/issues/vstest-1069/sof_proj$dotnet test --blame
Build started, please wait...
Build completed.

Test run for /Users/vstest/samadala/issues/vstest-1069/sof_proj/bin/Debug/netcoreapp20/sof_proj.dll(.NETCoreApp,Version=v2.0)
Microsoft (R) Test Execution Command Line Tool Version 15.5.0-preview-20170810-02
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '2.0.0-beta-001737-00' was not found.
  - Check application dependencies and target a framework version installed at:
      /
  - Alternatively, install the framework version '2.0.0-beta-001737-00'.

Object reference not set to an instance of an object.
Object reference not set to an instance of an object.


vstest@VSs-MacBook-Pro.local:~/samadala/issues/vstest-1069/sof_proj$dotnet --info
.NET Command Line Tools (2.1.0-preview1-007186)

Product Information:
 Version:            2.1.0-preview1-007186
 Commit SHA-1 hash:  8e756edce1

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.0-preview1-007186/

Microsoft .NET Core Shared Framework Host

  Version  : 2.1.0-preview2-25616-02
  Build    : 8aa34a95bad481e1b5e4c8286e5cb2d7cb6ed943

vstest@VSs-MacBook-Pro.local:~/samadala/issues/vstest-1069/sof_proj$vim /usr/local/share/dotnet/sdk/2.1.0-preview1-007186/datacollector.
datacollector.deps.json           datacollector.dll                 datacollector.dll.config          datacollector.runtimeconfig.json  
vstest@VSs-MacBook-Pro.local:~/samadala/issues/vstest-1069/sof_proj$vim /usr/local/share/dotnet/sdk/2.1.0-preview1-007186/datacollector.runtimeconfig.json 
vstest@VSs-MacBook-Pro.local:~/samadala/issues/vstest-1069/sof_proj$sudo vim /usr/local/share/dotnet/sdk/2.1.0-preview1-007186/datacollector.runtimeconfig.json 
Password:
vstest@VSs-MacBook-Pro.local:~/samadala/issues/vstest-1069/sof_proj$dotnet test --blame
Build started, please wait...
Build completed.

Test run for /Users/vstest/samadala/issues/vstest-1069/sof_proj/bin/Debug/netcoreapp20/sof_proj.dll(.NETCoreApp,Version=v2.0)
Microsoft (R) Test Execution Command Line Tool Version 15.5.0-preview-20170810-02
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
The active test run was aborted. Reason: Process is terminating due to StackOverflowException.


Attachments:
  /Users/vstest/samadala/issues/vstest-1069/sof_proj/TestResults/d15847ba-a169-4dfd-810b-4996f01e2100/Sequence.xml


The active Test Run was aborted because the host process exited unexpectedly while executing following test(s):
sof_proj.UnitTest1.TestMethod1

vstest@VSs-MacBook-Pro.local:~/samadala/issues/vstest-1069/sof_proj$dotnet --info
.NET Command Line Tools (2.1.0-preview1-007186)

Product Information:
 Version:            2.1.0-preview1-007186
 Commit SHA-1 hash:  8e756edce1

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.0-preview1-007186/

Microsoft .NET Core Shared Framework Host

  Version  : 2.1.0-preview2-25616-02
  Build    : 8aa34a95bad481e1b5e4c8286e5cb2d7cb6ed943

vstest@VSs-MacBook-Pro.local:~/samadala/issues/vstest-1069/sof_proj$cat /Users/vstest/samadala/issues/vstest-1069/sof_proj/TestResults/d15847ba-a169-4dfd-810b-4996f01e2100/Sequence.xml
<?xml version="1.0"?>
<TestSequence>
  <Test Name="sof_proj.UnitTest1.TestMethod1" Source="/Users/vstest/samadala/issues/vstest-1069/sof_proj/bin/Debug/netcoreapp20/sof_proj.dll" />
</TestSequence>vstest@VSs-MacBook-Pro.local:~/samadala/issues/vstest-1069/sof_proj$

```

**Comment by chlowell** [comment]
`--blame` identifies which test was executing when something went wrong but doesn't provide any insight:
```
The active test run was aborted. Reason:

Attachments:
  /home/chlowe/code/logging-log4net/tests/src/TestResults/9b87a336-e0dc-4513-b0bd-bd8b43fd3e1d/Sequence.xml

Total tests: Unknown. Passed: 31. Failed: 0. Skipped: 5.
Test Run Aborted.
Test execution time: 4.7233 Seconds

The active Test Run was aborted because the host process exited unexpectedly while executing following test(s):
log4net.Tests.Appender.RollingFileAppenderTest.TestRollingCountUpFixedBackups
```

In the diagnostic log I see the same exception:

```
TpTrace Error: 0 : 6764, 11, 2017/12/15, 10:51:04.628, 7053981317000, vstest.console.dll, Socket: Message loop: failed to receive message due to socket error System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.ReadByte()
   at System.IO.BinaryReader.Read7BitEncodedInt()
   at System.IO.BinaryReader.ReadString()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.LengthPrefixCommunicationChannel.NotifyDataAvailable()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.TcpClientExtensions.MessageLoopAsync(TcpClient client, ICommunicationChannel channel, Action`1 errorHandler, CancellationToken cancellationToken)
```

I still can't determine whether the test itself is throwing an exception or what that exception might be.

**Comment by smadala** [comment]
@chlowell  As mentioned https://github.com/Microsoft/vstest/issues/1069#issuecomment-350048544 `EndOfStreamException` is only side effect of testhost process crash. From [logs](https://gist.github.com/chlowell/9fd4b493d8552175243f6af97c58e823), It appears `test code` causing testhost crash. Please identify the exception which caused crash, For windows we can create either create [Full dump](https://support.microsoft.com/en-us/help/931673/how-to-create-a-user-mode-process-dump-file-in-windows) and analyze or see the `Event Viewer`. Can you try similar things on linux. 

You can use the `Sequence.xml` file to narrow down the what order of tests execution causing the crash, Use `dotnet vstest /home/chlowe/code/logging-log4net/tests/src/log4net.Tests.dll  /Tests:TestMethod1,testMethod2` to run tests in sequence.

**Comment by Rpry** [comment]
> log.host.

Where log.host.* can be taken from? Should any setting be activated to get this file generated?

**Comment by Rpry** [comment]
> @chlowell thank you for reporting the issue. Can you please share `log.host.*.txt` diagnostics file? It will have details if the host crashed during the test run.

Where log.host.* can be taken from? Should any setting be activated to get this file generated?
