### ISSUE TITLE
Cannot run vstest.console.exe after building from sources

### ISSUE THREAD

**Issue by smadala** [Microsoft/vstest#1071]
_From @samasama on September 12, 2017 4:14_

After building the solution from sources on a windows machine using build.cmd, I tried running the vstest.console,exe at vstest\artifacts\Debug\net451\win7-x64 results in :
`No test is available in EPMLiveCore.Tests.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.` 
Using /diag, the first exception is 
`File name: 'Microsoft.VisualStudio.TestPlatform.Extensions.GenericTestAdapter, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ---> System.Security.SecurityException: Strong name validation failed. (Exception from HRESULT: 0x8013141A)
The Zone of the assembly that failed was:
MyComputer
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Microsoft.VisualStudio.TestPlatform.PlatformAbstractions.PlatformAssemblyLoadContext.LoadAssemblyFromPath(String assemblyPath)
   at Microsoft.VisualStudio.TestPlatform.Common.Utilities.AssemblyResolver.OnResolve(Object sender, AssemblyResolveEventArgs args)
`

Am I missing something to be done after building?

_Copied from original issue: Microsoft/vstest-docs#74_

**Comment by smadala** [comment]
@samasama First exception `Strong name validation failed.`  may not be the reason for failure. Please share   log file and repro project.

**Comment by samasama** [comment]
Unfortunately it is an organization repo
I checked the strong naming of the mentioned assembly (Microsoft.VisualStudio.TestPlatform.Extensions.GenericTestAdapter) using SN and it stated that it is delay-signed

**Comment by smadala** [comment]
@samasama You are right, it is deplay-signed. Use [this](https://github.com/Microsoft/vstest/blob/master/NuGet.config#L11) feed and package `Microsoft.TestPlatform 15.5.0-preview-20170913-02`(path: \tools\net451\vstest.console.exe) which contains signed dlls for latest vstest.console.exe . 
May I know why you are building vstest.console.exe for running organization repo tests?

**Comment by samasama** [comment]
Diagnostics attached

[diags.zip](https://github.com/Microsoft/vstest/files/1299330/diags.zip)

**Comment by smadala** [comment]
@samasama Looks like you are trying to run fakes tests from below stacktrace. Fakes and code coverage(VS enterprise features) are not part of this repo. To run Fakes tests/code coverage, you can use `C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\TestPlatform\vstest.console.exe` 
```cs
Microsoft.QualityTools.Testing.Fakes.UnitTestIsolation.UnitTestIsolationException: Failed to resolve profiler path from COR_PROFILER_PATH and COR_PROFILER environment variables., ErrorStackTrace:    at Microsoft.QualityTools.Testing.Fakes.UnitTestIsolation.IntelliTraceInstrumentationProvider.ResolveProfilerPath()
   at Microsoft.QualityTools.Testing.Fakes.UnitTestIsolation.IntelliTraceInstrumentationProvider.Initialize()
   at Microsoft.QualityTools.Testing.Fakes.UnitTestIsolation.UnitTestIsolationRuntime.InitializeUnitTestIsolationInstrumentationProvider()
   at Microsoft.QualityTools.Testing.Fakes.Shims.ShimRuntime.CreateContext()
   at SPEmulators.SPEmulationContext..ctor(IsolationLevel isolationLevel, String url)
   at SPEmulators.SPEmulationContext..ctor(IsolationLevel isolationLevel)
   epmlive2013release\EPMLiveCore\EPMLiveCore.Tests\ReportHelper\ReportDataTests.cs:line 22
```

**Comment by samasama** [comment]
I have a task to build that repo in a docker container and I faced this
issue:
https://github.com/Microsoft/vstest/issues/940
And I was investigating  to see if I can get it fixed specially that I am
currently on VS 14 with a little hope of receiving a fix

Thanks

**Comment by smadala** [comment]
Thanks for investigating, The root cause for #940 is Intellitrace(which is used when Fakes and Code coverage enabled) failed to create memory mapped file in the global namespace. Probably container having capability to create memory mapped file in the global namespace solves the issue for VS 14. 

I'm closing this issue, Please follow #940 for further conversation.
