### ISSUE TITLE
Failed to launch testhost with error: System.IO.FileNotFoundException: Path does not exist

### ISSUE THREAD

**Issue by Evangelink** [microsoft/vstest#10759]
Clone `dotnet/runtimelab` branch `feature/swift-bindings`: https://github.com/dotnet/runtimelab/tree/feature/swift-bindings

Build from VS or from CLI:

```
Failed to launch testhost with error: System.IO.FileNotFoundException: Path does not exist: C:\src\runtimelab\artifacts\bin\Swift.Bindings.Tests\Debug\net9.0\dotnet.exe
File name: 'C:\src\runtimelab\artifacts\bin\Swift.Bindings.Tests\Debug\net9.0\dotnet.exe'
   at Microsoft.VisualStudio.TestPlatform.PlatformAbstractions.ProcessHelper.LaunchProcess(String processPath, String arguments, String workingDirectory, IDictionary`2 envVariables, Action`2 errorCallback, Action`1 exitCallBack, Action`2 outputCallBack) in /_/src/Microsoft.TestPlatform.PlatformAbstractions/common/System/ProcessHelper.cs:line 58
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DotnetTestHostManager.LaunchHost(TestProcessStartInfo testHostStartInfo, CancellationToken cancellationToken) in /_/src/Microsoft.TestPlatform.TestHostProvider/Hosting/DotnetTestHostManager.cs:line 749
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DotnetTestHostManager.LaunchTestHostAsync(TestProcessStartInfo testHostStartInfo, CancellationToken cancellationToken) in /_/src/Microsoft.TestPlatform.TestHostProvider/Hosting/DotnetTestHostManager.cs:line 221
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, String runSettings) in /_/src/Microsoft.TestPlatform.CrossPlatEngine/Client/ProxyOperationManager.cs:line 237
Failed to launch testhost with error: System.IO.FileNotFoundException: Path does not exist: C:\src\runtimelab\artifacts\bin\Swift.Bindings.Tests\Debug\net9.0\dotnet.exe
File name: 'C:\src\runtimelab\artifacts\bin\Swift.Bindings.Tests\Debug\net9.0\dotnet.exe'
   at Microsoft.VisualStudio.TestPlatform.PlatformAbstractions.ProcessHelper.LaunchProcess(String processPath, String arguments, String workingDirectory, IDictionary`2 envVariables, Action`2 errorCallback, Action`1 exitCallBack, Action`2 outputCallBack) in /_/src/Microsoft.TestPlatform.PlatformAbstractions/common/System/ProcessHelper.cs:line 58
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DotnetTestHostManager.LaunchHost(TestProcessStartInfo testHostStartInfo, CancellationToken cancellationToken) in /_/src/Microsoft.TestPlatform.TestHostProvider/Hosting/DotnetTestHostManager.cs:line 749
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DotnetTestHostManager.LaunchTestHostAsync(TestProcessStartInfo testHostStartInfo, CancellationToken cancellationToken) in /_/src/Microsoft.TestPlatform.TestHostProvider/Hosting/DotnetTestHostManager.cs:line 221
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, String runSettings) in /_/src/Microsoft.TestPlatform.CrossPlatEngine/Client/ProxyOperationManager.cs:line 237
```

Attaching diagnostic logs: [diag.log](https://github.com/user-attachments/files/18165543/diag.log)

**Comment by nohwnd** [comment]
The path to dotnet is specified by settings: DotnetTestHostmanager: User specified custom path to dotnet host: 'C:\src\runtimelab\artifacts\bin\Swift.Bindings.Tests\Debug\net9.0\dotnet.exe'./

```xml
<RunSettings>
  <RunConfiguration>
   
    <DotNetHostPath>C:\src\runtimelab\artifacts\bin\Swift.Bindings.Tests\Debug\net9.0\dotnet.exe</DotNetHostPath>

  </RunConfiguration>
```

it is generated by target coming from here: https://github.com/dotnet/runtimelab/blob/feature/swift-bindings/eng/testing/runsettings.targets#L27

The latest commit in that repo (on the mentioned branch) does not build for me , but the previous commit 0ba0707 shows this as the content, which seems correct. 

![Image](https://github.com/user-attachments/assets/32174cd6-b2ee-46a4-8482-e59db42dc542)

**Comment by vitek-karas** [comment]
Please close this issue
