### ISSUE TITLE
TPv2 fails to execute tests in LiveUnitTesting.sln

### ISSUE THREAD

**Issue by KevinH-MS** [Microsoft/vstest#1205]
## Description
> When I attempt to run tests in the LiveUnitTesting.sln via Live Unit Testing, I get the following error:
```
[22:45:59.448 Error] - FatalError - System.AggregateException: One or more errors occurred. ---> Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Failed to initialize client proxy: could not connect to test process.
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyExecutionManager.StartTestRun(TestRunCriteria testRunCriteria, ITestRunEventsHandler eventHandler)
```

In the TP logs, I see:
```
TpTrace Warning: 0 : 449456, 7, 2017/10/16, 22:43:54.999, 2133744647236, testhost.x86.exe, LoaderExceptions: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Microsoft.VisualStudio.TestPlatform.Common.ExtensionFramework.TestPluginCache.CurrentDomainAssemblyResolve(Object sender, AssemblyResolveEventArgs args)
   at Microsoft.VisualStudio.TestPlatform.PlatformAbstractions.PlatformAssemblyResolver.AssemblyResolverEvent(Object sender, Object eventArgs)
   at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)
```

## Steps to reproduce
> git clone https://github.com/dotnet/testimpact
> build.cmd
> open LiveUnitTesting.sln
> Test > Live Unit Testing > Start

## Expected behavior
> Tests should execute

## Actual behavior
> Tests are discovered, but do not execute

## Diagnostic logs
> Full logs at ``` \\mlangfs1\public\kevinh\tplogs```

## Environment
d15rel.27015.1

**Comment by smadala** [comment]
> TpTrace Verbose: 0 : 474800, 6, 2017/10/16, 22:43:59.266, 2133758850854, vstest.console.exe, Launching default test Host Process **C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\PREVIEW\ENTERPRISE\COMMON7\IDE\EXTENSIONS\TESTPLATFORM\Extensions\..//testhost.x86.exe with arguments  --port 26631 --endpoint 127.0.0.1:026631 --role client --parentprocessid 474800 --diag "D:\TestImpact\.vs\LiveUnitTesting\lut\log\471860\1.host.17-10-16_22-43-59_26625_7.log" --testsourcepath "D:\TestImpact\.vs\LiveUnitTesting\lut\0\t\artifacts\Debug\bin\OrchestratorTest\Microsoft.CodeAnalysis.LiveUnitTesting.Orchestrator.UnitTests.dll" --telemetryoptedin false**
TpTrace Information: 0 : 474800, 1, 2017/10/16, 22:43:59.277, 2133758886868, vstest.console.exe, DesignModeClient: Processing Message of message type: TestExecution.CustomTestHostLaunchCallback
TpTrace Verbose: 0 : 474800, 6, 2017/10/16, 22:43:59.304, 2133758974826, vstest.console.exe, Test Runtime launched
TpTrace Error: 0 : 474800, 7, 2017/10/16, 22:44:59.308, 2133958677376, vstest.console.exe, ProxyExecutionManager.StartTestRun: Failed to start test run: Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Failed to initialize client proxy: could not connect to test process.
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyExecutionManager.StartTestRun(TestRunCriteria testRunCriteria, ITestRunEventsHandler eventHandler)

@KevinH-MS From vstest.console log I see testhost failed to launch, Is this happening intermittently? Can you share `1.host.17-10-16_22-43-59_26625_7.log`  file?

**Comment by KevinH-MS** [comment]
This repros 100% of the time.  All the logs that were produced are at:  ``` \\mlangfs1\public\kevinh\tplogs```

**Comment by KevinH-MS** [comment]
It appears that Live Unit Testing just needs to update its ObjectModel reference.  Closing in favor of VSO bug:  https://devdiv.visualstudio.com/DevDiv/_queries?id=510311&fullScreen=false&_a=edit

**Comment by smadala** [comment]
Add stacktrace for search
```
Testhost process exited with error: Unhandled Exception: System.TypeLoadException: Could not load type 'Microsoft.VisualStudio.TestPlatform.ObjectModel.ConnectionRole' from assembly 'Microsoft.VisualStudio.TestPlatform.ObjectModel, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
Server stack trace:
   at Microsoft.VisualStudio.TestPlatform.TestHost.DefaultEngineInvoker.Invoke(IDictionary`2 argsDictionary)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)
Exception rethrown at [0]:
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Microsoft.VisualStudio.TestPlatform.TestHost.IEngineInvoker.Invoke(IDictionary`2 argsDictionary)
   at Microsoft.VisualStudio.TestPlatform.TestHost.AppDomainEngineInvoker`1.Invoke(IDictionary`2 argsDictionary)
   at Microsoft.VisualStudio.TestPlatform.TestHost.Program.Run(String[] args)
   at Microsoft.VisualStudio.TestPlatform.TestHost.Program.Main(String[] args)
```
