### ISSUE TITLE
Active test run aborted in Visual Studio IDE test output pane.

### ISSUE THREAD

**Issue by smadala** [Microsoft/vstest#1256]
## Description
> Test run aborted intermittently in VS Test explorer. 

## Steps to reproduce
- [Insertion.zip](https://github.com/Microsoft/vstest/files/1433614/Insertion.zip)
- Open Above solution
- Click "Run All" multiple times.

## Expected behavior
> Test run should run successful always.

## Actual behavior
> Intermittently  Active test run aborted.

## Diagnostic logs
-  [log.txt](https://github.com/Microsoft/vstest/files/1433618/log.txt)
- Interesting logs
```
TpTrace Warning: 0 : 6844, 16, 2017/10/31, 05:23:11.744, 88988150153, vstest.console.exe, ProxyOperationManager: Timed out waiting for test host to exit. Will terminate process.
TpTrace Verbose: 0 : 6844, 16, 2017/10/31, 05:23:11.744, 88988160922, vstest.console.exe, TestRunRequest:SendTestRunStatsChange: Starting.
TpTrace Information: 0 : 6844, 16, 2017/10/31, 05:23:11.744, 88988161530, vstest.console.exe, TestRunRequest:SendTestRunStatsChange: Completed.
TpTrace Verbose: 0 : 6844, 16, 2017/10/31, 05:23:11.744, 88988161978, vstest.console.exe, ParallelProxyExecutionManager: HandlePartialRunComplete: Total completed clients = 2, Run complete = True, Run canceled: False.
TpTrace Verbose: 0 : 6844, 16, 2017/10/31, 05:23:11.759, 88988165305, vstest.console.exe, TestRunRequest:TestRunComplete: Starting. IsAborted:False IsCanceled:False.
TpTrace Information: 0 : 6844, 1, 2017/10/31, 05:23:11.759, 88988172359, vstest.console.exe, DesignModeClient: Processing Message of message type: TestExecution.Abort
TpTrace Information: 0 : 6844, 1, 2017/10/31, 05:23:11.759, 88988172709, vstest.console.exe, TestRequestManager.AbortTestRun: Sending abort request.
TpTrace Verbose: 0 : 6844, 1, 2017/10/31, 05:23:11.759, 88988173346, vstest.console.exe, TestRunRequest.Abort: Aborting.
TpTrace Information: 0 : 6844, 16, 2017/10/31, 05:23:11.759, 88988174567, vstest.console.exe, TestRunRequest:TestRunComplete: Completed.
TpTrace Verbose: 0 : 6844, 12, 2017/10/31, 05:23:11.759, 88988175150, vstest.console.exe, TestRunRequest.Dispose: Starting.
TpTrace Information: 0 : 6844, 12, 2017/10/31, 05:23:11.759, 88988175414, vstest.console.exe, TestRunRequest.Dispose: Completed.
TpTrace Information: 0 : 6844, 12, 2017/10/31, 05:23:11.759, 88988175626, vstest.console.exe, TestRequestManager.RunTests: run tests completed, sucessful: True.
TpTrace Error: 0 : 6844, 1, 2017/10/31, 05:23:11.759, 88988193936, vstest.console.exe, DesignModeClient: Error processing request: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'testRunRequest'.
   at Microsoft.VisualStudio.TestPlatform.Client.Execution.TestRunRequest.Abort()
   at Microsoft.VisualStudio.TestPlatform.CommandLine.TestPlatformHelpers.TestRequestManager.AbortTestRun()
   at Microsoft.VisualStudio.TestPlatform.Client.DesignMode.DesignModeClient.ProcessRequests(ITestRequestManager testRequestManager)
TpTrace Verbose: 0 : 6844, 1, 2017/10/31, 05:23:11.759, 88988205154, vstest.console.exe, Executor.Execute: Exiting with exit code of 1
TpTrace Verbose: 0 : 7796, 1, 2017/10/31, 05:49:38.772, 104858285565, vstest.console.exe, Using effective platform:X86 effective framework:.NETFramework,Version=v4.0
```
- **Received TestRunAbort from Testwindow**
## Environment
> VS 15.5.0. Preview 3.0 [27027.1d15rel]
> VSTest  15.5.0-preview-20171031-01

**Comment by Faizan2304** [comment]
Fixed.
