### ISSUE TITLE
VSTest not correctly supporting pre-enumerated theories xunit

### ISSUE THREAD

**Issue by xavierjohn** [microsoft/vstest#1291]
## Description
> VSTest not correctly supporting pre-enumerated theories xunit

## Steps to reproduce
Here is the link to the xUnit issue with all the details and it looks like a problem in vstest.

https://github.com/xunit/xunit/issues/1483#issuecomment-343691972

**Comment by mayankbansal018** [comment]
@AbhitejJohn Profiling for xunit Theory tests do not work, because while creating the file for profile report, we fail to do so as the name of the file is invalid.

for e.g. in the attached project the file name that we try to create ends with ""any_theory(input: "1")"", where Path.Combine Api fails

Method public string CreateProfilerReportPath(string testName)
File: ProfilerHost.cs in devdiv.

**Comment by Evangelink** [comment]
@shyamnamboodiripad @AbhitejJohn It seems that the problem mentioned in the linked ticket concerns Test Window.

Here is the link to the comment with reproducer: https://github.com/xunit/visualstudio.xunit/issues/114#issuecomment-343691544

Here is the error trace in the test output window:

```
[21/07/2022 2:41:29.066 pm] [Error] System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String path1, String path2)
   at Microsoft.VisualStudio.TestWindow.Profiler.ProfilerHost.CreateProfilerReportPath(String testName)
   at Microsoft.VisualStudio.TestWindow.Profiler.ProfilerLauncher.StartProfiling(String testName, String targetFramework, ExecutionPlatform testExecPlatform)
   at Microsoft.VisualStudio.TestWindow.Profiler.ProfilerController.Start()
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Microsoft.VisualStudio.TestWindow.Logging.ILoggerExtensions.CallInternalWithLogging(IInternalLogger log, Action action, Boolean shouldThrow)
```

I am also seeing another one that wasn't mentioned at first:

```
[21/07/2022 2:41:31.027 pm] [Error] System.ArgumentNullException: Value cannot be null.
Parameter name: profilerReport
   at Microsoft.VisualStudio.TestWindow.Profiler.ValidateArg.NotNull[T](T arg, String parameterName)
   at Microsoft.VisualStudio.TestWindow.Profiler.ProfilerHost.DisplayReport(String profilerReport)
   at Microsoft.VisualStudio.TestWindow.Profiler.ProfilerController.DisplayResult()
   at Microsoft.VisualStudio.TestWindow.Profiler.ProfilerController.<Stop>b__28_0()
   at Microsoft.VisualStudio.TestWindow.Logging.ILoggerExtensions.CallInternalWithLogging(IInternalLogger log, Action action, Boolean shouldThrow)
```

@MarcoRossignoli @jakubch1 Do you guys know if the `Profile` entry is supposed to work? I am getting a popup with the following error message "File contains no data buffer".

**Comment by Evangelink** [comment]
I have opened the issue on Test Window side as the problem is on their side.
