### ISSUE TITLE
vstest.console execution fails with System.ArgumentNullException

### ISSUE THREAD

**Issue by psaniuk** [Microsoft/vstest#1332]
## Description
vstest.console.exe fails to run a UWP application unit tests because of an exception.

## Steps to reproduce
1. Create an UWP application with Visual Studio 2017 and add a reference  to Microsoft.Engagement.Framework;
2. Modify App.xaml.cs OnLaunched with:
`   StoreServicesEngagementManager engagementManager = StoreServicesEngagementManager.GetDefault();
                await engagementManager.RegisterNotificationChannelAsync(new StoreServicesNotificationChannelParameters());`
3. Create a unit test project and add some tests;
4. Create .appx package for the test project;
5. Execute tests with vstest.console.exe.

## Expected behavior
The tests are executed.

## Actual behavior
Execution fails with an exception.
Stack trace:
Unhandled Exception: System.Runtime.CallbackException: A user callback threw an exception.  Check the exception stack and inner exception to determine the callback that failed. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: applicationName
   at Microsoft.VisualStudio.TestPlatform.ObjectModel.ValidateArg.NotNull[T](T arg, String parameterName)
   at Microsoft.VisualStudio.TestPlatform.Client.LocalCrashDumpUtilities.TryGetLocalCrashDumpPath(String applicationName, String& crashDumpPath)
   at Microsoft.VisualStudio.TestPlatform.Client.TestExecutorServiceClient.TryGetLocalCrashDumpPath(String applicationName, String& crashDumpPath)
   at Microsoft.VisualStudio.TestPlatform.Client.TestExecutorServiceClient.GetTestRunAbortedMessage(String executorProcessName, Int32 executorProcessId, Boolean hasExited, Boolean isRemoteExecution)
   at Microsoft.VisualStudio.TestPlatform.Client.TestExecutorServiceClient.TestExecutorServiceChannel_Reset(Object sender, EventArgs e)
   at System.ServiceModel.Channels.CommunicationObject.OnClosed()
   --- End of inner exception stack trace ---
   at System.ServiceModel.Channels.CommunicationObject.OnClosed()
   at System.ServiceModel.ServiceHostBase.OnClosed()
   at System.ServiceModel.ServiceHost.OnClosed()
   at System.ServiceModel.Channels.CommunicationObject.Close(TimeSpan timeout)
   at Microsoft.VisualStudio.TestPlatform.Client.UniversalTestExecutorProxy.Close()
   at Microsoft.VisualStudio.TestPlatform.Client.TestExecutorServiceClient.StarPlatformSpecificTestExecution(IPlatformTestExecutorClient platformTestExecutorClient, ITestExecutorLauncher launcher, Architecture targetPlatform, FrameworkVersion targetFramework)
   at Microsoft.VisualStudio.TestPlatform.Client.TestExecutorServiceClient.Initialize_NoLock(Architecture targetPlatform, FrameworkVersion targetFramework)
   at Microsoft.VisualStudio.TestPlatform.Client.TestExecutorServiceClient.EnsureInitialized(IDictionary`2 environmentVariables, TestExecutionContext context)
   at Microsoft.VisualStudio.TestPlatform.Client.TestExecutorServiceClient.<>c__DisplayClass18_0.<StartTestRun>b__0()
   at Microsoft.VisualStudio.TestPlatform.Client.TestExecutorServiceClient.InvokeTestExecutorServiceAction(Action action)
   at Microsoft.VisualStudio.TestPlatform.Client.TestExecutorServiceClient.StartTestRun(IEnumerable`1 sources, TestExecutionContext executionContext, String runSettings, IDictionary`2 environmentVariables, String dataCollectionServiceUri, ITestCaseLog testCaseLog, ITestRunLog testRunLog, IFrameworkHandleInternal frameworkHandle)
   at Microsoft.VisualStudio.TestPlatform.Client.Rocksteady.RocksteadyExecutionManager.StartTestRun(TestRunCriteria testRunCriteria, Boolean inIsolation, DataCollectionParameters dataCollectionParameters, ITestRunEventsHandler runEventsHandler)
   at Microsoft.VisualStudio.TestPlatform.Client.TestRunRequest.ExecuteAsync()
   at Microsoft.VisualStudio.TestPlatform.CommandLine.Processors.RunTestsArgumentProcessor.RunTests(IEnumerable`1 sources, String packageFullName, String deviceInfo, Boolean isPhoneAppx, Boolean isUniversalTestAppx)
   at Microsoft.VisualStudio.TestPlatform.CommandLine.Processors.RunTestsArgumentProcessor.ExecuteAppContainerSources(List`1 appContainerSources, String deviceInfo, Boolean isPhoneAppx)
   at Microsoft.VisualStudio.TestPlatform.CommandLine.Processors.RunTestsArgumentProcessor.Execute()
   at Microsoft.VisualStudio.TestPlatform.CommandLine.Executor.Execute(String[] args)
   at RockSteady.Program.Main(String[] args)

## Environment
Windows 10 Enterprise, version 10.0.15063 Buidl 15063
Test Execution Command Line Tool Version 15.0.27128.1

**Comment by mayankbansal018** [comment]
@psaniuk , Can you please attach a repro project, or share it on github

**Comment by mayankbansal018** [comment]
@psaniuk , We are introducing a newer test platform for UWP in VS2017 update 6, it's available since preview4, & this should get resolved.

Please re-open this issue, & share a repro if you hit it again

**Comment by psaniuk** [comment]
@mayankbansal018 thanks for the help. I've tried your suggestion and got and exception:

> TpTrace Information: 0 : 23116, 5, 2018/03/08, 17:33:30.885, 1424523238123, vstest.console.exe, AssemblyResolver: Microsoft.Tools.Deploy, Version=10.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: Resolving assembly.
TpTrace Information: 0 : 23116, 5, 2018/03/08, 17:33:30.886, 1424523239554, vstest.console.exe, AssemblyResolver: Microsoft.Tools.Deploy, Version=10.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: Failed to load assembly.
TpTrace Information: 0 : 23116, 7, 2018/03/08, 17:33:30.909, 1424523302669, vstest.console.exe, AssemblyResolver: Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a: Resolving assembly.
TpTrace Information: 0 : 23116, 7, 2018/03/08, 17:33:30.909, 1424523302993, vstest.console.exe, AssemblyResolver: Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a: Resolved from cache.
TpTrace Information: 0 : 23116, 5, 2018/03/08, 17:33:31.958, 1424526181292, vstest.console.exe, AssemblyResolver: Microsoft.SmartDevice.Connectivity, Version=11.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a: Resolving assembly.
TpTrace Information: 0 : 23116, 5, 2018/03/08, 17:33:31.959, 1424526182788, vstest.console.exe, AssemblyResolver: Microsoft.SmartDevice.Connectivity, Version=11.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a: Failed to load assembly.
TpTrace Verbose: 0 : 23116, 5, 2018/03/08, 17:33:32.527, 1424527741719, vstest.console.exe, Test host launched
TpTrace Verbose: 0 : 23116, 5, 2018/03/08, 17:33:32.528, 1424527742884, vstest.console.exe, TestRequestSender.WaitForRequestHandlerConnection: waiting for connection with timeout: 60000
TpTrace Error: 0 : 23116, 5, 2018/03/08, 17:34:32.538, 1424692305576, vstest.console.exe, ProxyExecutionManager.StartTestRun: Failed to start test run: Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Failed to initialize client proxy: could not connect to test process.
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyExecutionManager.StartTestRun(TestRunCriteria testRunCriteria, ITestRunEventsHandler eventHandler)
TpTrace Verbose: 0 : 23116, 5, 2018/03/08, 17:34:32.563, 1424692373910, vstest.console.exe, TestRunRequest:SendTestRunMessage: Starting.
TpTrace Information: 0 : 23116, 5, 2018/03/08, 17:34:32.563, 1424692375076, vstest.console.exe, TestRunRequest:SendTestRunMessage: Completed.
TpTrace Verbose: 0 : 23116, 5, 2018/03/08, 17:34:32.566, 1424692383363, vstest.console.exe, ParallelProxyExecutionManager: HandlePartialRunComplete: Total completed clients = 1, Run complete = True, Run canceled: False.
TpTrace Verbose: 0 : 23116, 5, 2018/03/08, 17:34:32.588, 1424692441328, vstest.console.exe, TestRunRequest:TestRunComplete: Starting. IsAborted:True IsCanceled:False.
TpTrace Information: 0 : 23116, 5, 2018/03/08, 17:34:32.595, 1424692462274, vstest.console.exe, TestRunRequest:TestRunComplete: Completed.
TpTrace Verbose: 0 : 23116, 1, 2018/03/08, 17:34:32.597, 1424692467216, vstest.console.exe, TestRunRequest.Dispose: Starting.
TpTrace Information: 0 : 23116, 1, 2018/03/08, 17:34:32.597, 1424692467827, vstest.console.exe, TestRunRequest.Dispose: Completed.
TpTrace Information: 0 : 23116, 1, 2018/03/08, 17:34:32.597, 1424692468112, vstest.console.exe, TestRequestManager.RunTests: run tests completed, sucessful: True.
TpTrace Information: 0 : 23116, 1, 2018/03/08, 17:34:32.597, 1424692468730, vstest.console.exe, RunTestsArgumentProcessor:Execute: Test run is completed.
TpTrace Verbose: 0 : 23116, 1, 2018/03/08, 17:34:32.597, 1424692469003, vstest.console.exe, Executor.Execute: Exiting with exit code of 1

**Comment by mayankbansal018** [comment]
@psaniuk , can you please share a sample repro project with us?

**Comment by psaniuk** [comment]
@mayankbansal018  I've tried to point vstest.console to another test project and it worked well. Currently, I'm trying to get a sample repo where I can reproduce the issue.

**Comment by ShreyasRmsft** [comment]
@psaniuk closing this issue for now. Please re-open if you get a re-pro. Also share the re-pro steps/solution.

**Comment by isaac-mcgarvey** [comment]
Here's a repro solution:
[repro.zip](https://github.com/Microsoft/vstest/files/1922904/repro.zip)

I only know how to repro it in Visual Studio, not the command line. I'm using Visual Studio 2017 15.6.6. Open that solution and build the XamarinUnitTests.UWP project. Make sure it actually builds rather than getting skipped (right click the project in Solution Explorer and choose build). Then, click "Run All" in Test Explorer. The exception is the same as above.

Note that this project doesn't actually contain any unit tests. It's simply an empty Xamarin.Forms project template. I created it by following these steps:
1. File -> New -> Project
2. Visual C# -> Cross-Platform -> Mobile App (Xamarin.Forms)
3. Platform: UWP only
4. Code Sharing Strategy: .NET Standard

Although this repro doesn't contain unit tests, I'm encountering this in a real solution where I have a Xamarin Forms project and another project containing unit tests. This problem prevents those unit tests in the other project from running.

**Comment by mayankbansal018** [comment]
@isaac-mcgarvey , neither of your projects are UWP UT projects, I'm adding IDE folks to investigate as to why a test run/discovery request is issued for these projects.

@AbhitejJohn , @ManishJayaswal  , can you please investigate this. A test run/discovery request is being issued for Xamarin projects which are not UT projects.

**Comment by ManishJayaswal** [comment]
ok, we will take a look. I have created a tracking bug for this in VSO. We will update this issue with what we find - (https://devdiv.visualstudio.com/DevDiv/_workitems/edit/608790)

@peterwald - FYI

**Comment by ManishJayaswal** [comment]
We have fixed this issue in 15.8 branch. The fix should be available in previews 2 release of 15.8.

**Comment by genlu** [comment]
@mayankbansal018 I think TestPlatform should be able to handle non-test UWP projects passed to it, just like it can handle any .net framework assemblies.
