### ISSUE TITLE
Provide a way to skip the test host version check for callers of IVsTestConsoleWrapper

### ISSUE THREAD

**Issue by KevinH-MS** [microsoft/vstest#1424]
## Description
I do not have a consistent repro, but I recently saw the following error while running Live Unit Testing:
```
[09:57:46.680 Error] [TestDiscoverer 1] Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Failed to negotiate protocol. Wait for response timed out.
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.TestRequestSender.CheckVersionWithTestHost()
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyDiscoveryManager.DiscoverTests(DiscoveryCriteria discoveryCriteria, ITestDiscoveryEventsHandler2 eventHandler)
[09:59:56.062 Error] [TestDiscoverer 1] Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Failed to negotiate protocol. Wait for response timed out.
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.TestRequestSender.CheckVersionWithTestHost()
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyDiscoveryManager.DiscoverTests(DiscoveryCriteria discoveryCriteria, ITestDiscoveryEventsHandler2 eventHandler)
[09:59:56.086 Error] Test discovery aborted/timed-out.
```

## Steps to reproduce
N/A

## Expected behavior
No error

## Actual behavior
Error, even though I don't think there's any scenario where the console doesn't match the testhost in the VS IDE.  I've also seen this protocol version negotiation show up in perf traces (about 190ms for each testhost that is launched).

## Diagnostic logs
N/A

## Environment
N/A

**Comment by singhsarab** [comment]
Unable to reproduce this one in the latest bits. 
Will reopen if you have a consistent repro.
