### ISSUE TITLE
Using DiaSession in test adapter causes COM manifest error

### ISSUE THREAD

**Issue by jnm2** [Microsoft/vstest#1432]
I've finished the much-anticipated work of making NUnit's VSTest adapter handle test assemblies with portable PDBs by using DiaSession rather than Mono.Cecil, except for this one last issue.

`dotnet vstest` and `dotnet test` both work fine with .NET Core tests.
The `vswhere`-located vstest.console.exe works fine with .NET Framework tests.
However, `dotnet test` with .NET Framework tests causes this error:

> Could not find the manifest file C:\Users\Joseph\Source\Repos\nunit3-vs-adapter\\.dotnet\sdk\1.1.4\TestHost\TestPlatform.ObjectModel.x86.manifest for Registry free Com registration.

```
Exception Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException, Exception thrown executing tests in C:\Users\Joseph\Source\Repos\nunit3-vs-adapter\src\NUnitTestAdapterTests\bin\Release\net45\NUnit.VisualStudio.TestAdapter.Tests.dll
Could not find the manifest file C:\Users\Joseph\Source\Repos\nunit3-vs-adapter\.dotnet\sdk\1.1.4\TestHost\TestPlatform.ObjectModel.x86.manifest for Registry free Com registration.
   at Microsoft.VisualStudio.TestPlatform.ObjectModel.Navigation.FullSymbolReader.GetManifestFileForRegFreeCom()
   at Microsoft.VisualStudio.TestPlatform.ObjectModel.Navigation.FullSymbolReader.CacheSymbols(String binaryPath, String searchPath)
   at Microsoft.VisualStudio.TestPlatform.ObjectModel.DiaSession..ctor(String binaryPath, String searchPath, ISymbolReader symbolReader)
```

Why is `TestPlatform.ObjectModel.x86.manifest` missing from `.dotnet\sdk\1.1.4\TestHost`?
Am I misusing DiaSession? Do you have a readme on this?

I tried dotnet SDKs 1.1.4 and 1.1.7.

Thank you!

**Comment by mayankbansal018** [comment]
@jnm2 , From the logs it seems you are generating full pdb's for .Net Framework, can you please try this with latest dotnet SDK, 2.1.*. We have moved away from using RegFreeCom via Manifest file, to use P/Invoke, & it works fine for mstest adapter.
