### ISSUE TITLE
vstest.console.exe crashes at socket layer

### ISSUE THREAD

**Issue by acesiddhu** [Microsoft/vstest#1437]
## Description
Don't have a consistent repro. we saw this on a production environment.
#[error]RunMessage : The active test run was aborted. Reason: Unhandled Exception: System.InvalidOperationException: LocalDataStoreSlot storage has been freed.
2018-02-12T09:25:52.8391446Z    at System.LocalDataStore.GetData(LocalDataStoreSlot slot)
2018-02-12T09:25:52.8391757Z    at System.Windows.Interop.ComponentDispatcher.get_CurrentThreadData()
2018-02-12T09:25:52.8392050Z    at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
2018-02-12T09:25:52.8392355Z    at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
2018-02-12T09:25:52.8392667Z    at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
2018-02-12T09:25:52.8392946Z    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
2018-02-12T09:25:52.8393307Z    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
2018-02-12T09:25:52.8393702Z    at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
2018-02-12T09:25:52.8394014Z    at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
2018-02-12T09:25:52.8394182Z 
2018-02-12T09:25:52.8895094Z    at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
2018-02-12T09:25:52.8896224Z    at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
2018-02-12T09:25:52.8897276Z    --- End of inner exception stack trace ---
2018-02-12T09:25:52.8898118Z    at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
2018-02-12T09:25:52.8898810Z    at System.IO.Stream.ReadByte()
2018-02-12T09:25:52.8899112Z    at System.IO.BinaryReader.ReadByte()
2018-02-12T09:25:52.8899731Z    at System.IO.BinaryReader.Read7BitEncodedInt()
2018-02-12T09:25:52.8900284Z    at System.IO.BinaryReader.ReadString()
2018-02-12T09:25:52.8900569Z    at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.LengthPrefixCommunicationChannel.NotifyDataAvailable()
2018-02-12T09:25:52.8900943Z    at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.TcpClientExtensions.MessageLoopAsync(TcpClient client, ICommunicationChannel channel, Action`1 errorHandler, CancellationToken cancellationToken)>
> For a defect reproducable from the vstest command line, describe the issue you've observed.

**Comment by mayankbansal018** [comment]
@acesiddhu , do you have a crash dump saved for vstest.console, & testhost process?

**Comment by acesiddhu** [comment]
@mayankbansal018 no. this is from our telemetry. some customer faced this issue. if we can debug from logs lets fix it. else we can close this one

**Comment by OsirisTerje** [comment]
@acesiddhu @mayankbansal018 Have you managed to debug this further?  We have a system now with this error.

**Comment by acesiddhu** [comment]
@OsirisTerje we weren't able to debug this. do you have dumps for this?
cc: @singhsarab

**Comment by OsirisTerje** [comment]
@acesiddhu  Ok, we'll try to get some dumps.

**Comment by OsirisTerje** [comment]
@acesiddhu It seems to a failure caused by using WPFControls, and not handling them correctly.  
The fix to this was like shown below:
![image](https://user-images.githubusercontent.com/203432/37283407-266225cc-25f8-11e8-814b-2f7a6f92e689.png)
The test is running as STA  (using  the attribute  [Apartment(ApartmentState.STA)]) , but it seems that it is not properly STA for some reason, or....  
Anyway, the fix above seems to do it, and the failure is not related to VSTest, so I am pretty sure this issue can be closed.
For reference also see links:
https://stackoverflow.com/questions/26528329/nunit-test-process-fails-frequently-with-wpf-controls
https://social.msdn.microsoft.com/Forums/ja-JP/bb990ddb-ecde-4161-8915-e66e913e3a3b/invalidoperationexception-localdatastoreslot-storage-has-been-freed?forum=exceldev

**Comment by acesiddhu** [comment]
@OsirisTerje thanks for digging into the issue. I will close the issue for now.
