### ISSUE TITLE
Starting Http listener in VS Test fails with AccessDenied

### ISSUE THREAD

**Issue by vaishnavk** [Microsoft/vstest#1546]
We have a test which brings up a Owin Selfhost service. The test fails with access denied when running it through the VS Test Task.

Error message
 Initialization method VolumeResourceManager.Test.VolumeResourceManagerTest.TestSetup threw exception. System.Net.HttpListenerException: Access is denied.
 Stack trace
 at System.Net.HttpListener.AddAllPrefixes()

at System.Net.HttpListener.Start()

at Microsoft.Owin.Host.HttpListener.OwinHttpListener.Start(HttpListener listener, Func2 appFunc, IList1 addresses, IDictionary2 capabilities, Func2 loggerFactory)

at Microsoft.Owin.Host.HttpListener.OwinServerFactory.Create(Func2 app, IDictionary2 properties)

https://msazure.visualstudio.com/One/Service%20Fabric/_build/index?buildId=12478884&_a=summary&tab=ms.vss-test-web.test-result-details

I am guessing this is because the tests are run with lower privilege. I couldn't find an option in VS Test task to run it with higher privilege. Any idea on how to fix this?

**Comment by cltshivash** [comment]
You will need to run the automation agent with a higher privilege. There's no plan to enhance the vstest task as a different user.
