### ISSUE TITLE
[C#][.Net Core][UT&Desktop] Cancel "Run All" failed and throw 2 errors

### ISSUE THREAD

**Issue by EdwardDing** [Microsoft/vstest#1568]
## Description
Cancel "Run All" failed at the seconding cancelling and 2 error messages will be thrown in output window.

## Steps to reproduce
Repro gif:  \\mlangfs1\public\v-zchan\CancelRunAll.gif 
1. Create a Console App(.NET Core) application
2. Have your sample test methods in your project.
3. Add a new "Unit Test Project(.NET Core)" project into this solution.
4. Refer above console app in this unit test project.
5. Call your sample code in this unit test project's test method
6. Have a negative test also which fails.
7. Run the test methods(Try different ways to run)
8. Run the test methods again and  then click "Cancel" quickly 

## Expected behavior
Cancel execution successfully.

## Actual behavior
Cancelling failed and throw 2 errors as following:
**Error message:**
[4/26/2018 11:14:24 PM Informational] ------ Run test started ------
[4/26/2018 11:14:29 PM Error] Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Failed to launch testhost with error: System.AggregateException: One or more errors occurred. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, CancellationToken cancellationToken)
---> (Inner Exception #0) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyExecutionManager.StartTestRun(TestRunCriteria testRunCriteria, ITestRunEventsHandler eventHandler)
[4/26/2018 11:14:29 PM Error] Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Failed to launch testhost with error: System.AggregateException: One or more errors occurred. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, CancellationToken cancellationToken)
---> (Inner Exception #0) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyExecutionManager.StartTestRun(TestRunCriteria testRunCriteria, ITestRunEventsHandler eventHandler)
[4/26/2018 11:14:29 PM Informational] ========== Run test finished: 0 run (0:00:05.1030327) ==========

## Diagnostic logs
None

## Environment
Visual Studio d15.7\27625.00

**Comment by mayankbansal018** [comment]
@EdwardDing apart from observing exception messages in Test output pane, are you also observing any additional issues, for e.g. your subsequest run test doesn't work, or incorrect result?

**Comment by EdwardDing** [comment]
@mayankbansal018 The subsequest run test is working and no incorrect result, but if canceling, sometimes, the output window will show this exception, and cancel will failed. Sometimes, cancel is successful.

**Comment by singhsarab** [comment]
@EdwardDing We have recently made fixes around to cancellation. 
Like: https://github.com/Microsoft/vstest/pull/1543

Can you please try moving to latest bits of VS and then re-try.

**Comment by singhsarab** [comment]
@EdwardDing I am closing the issue. Let's re-open if you disagree.
