### ISSUE TITLE
TestSession.Message does not get logged to console during discovery

### ISSUE THREAD

**Issue by karanjitsingh** [Microsoft/vstest#1569]
`TestSession.Message` sent to vstest.console via a custom test host does not get logged to console.

[vstest.console.log](https://github.com/Microsoft/vstest/files/1960126/vstest.console.log)
```
...
139:    TpTrace Verbose: 0 : 2600, 5, 2018/04/30, 15:13:22.058, 4073531597669, vstest.console.exe, TestRequestSender.OnDiscoveryMessageReceived: Received message: {"Version":2,"MessageType":"TestSession.Message","Payload":{"MessageLevel":2,"Message":"TypeError: Cannot read property 'cleanCache' of undefined\n    at EventEmitter.DiscoveryManager.discoveryComplete (D:\\JavaScriptTestHost\\src\\JSTestHost\\TestHost\\ExecutionManagers\\DiscoveryManager.ts:71:56)\n    at emitTwo (events.js:126:13)\n    at EventEmitter.emit (events.js:214:7)\n    at EventDispatcher.raise (D:\\JavaScriptTestHost\\src\\JSTestHost\\Environment\\Node\\EventDispatcher.ts:27:21)\n    at Event.raise (D:\\JavaScriptTestHost\\src\\JSTestHost\\Events\\Event.ts:17:74)\n    at TestSessionManager.setSessionComplete (D:\\JavaScriptTestHost\\src\\JSTestHost\\TestHost\\ExecutionManagers\\TestSessionManager.ts:31:37)\n    at EventEmitter.TestSessionEnd (D:\\JavaScriptTestHost\\src\\JSTestHost\\TestHost\\ExecutionManagers\\DiscoveryManager.ts:84:37)\n    at emitTwo (events.js:126:13)\n    at EventEmitter.emit (events.js:214:7)\n    at EventDispatcher.raise (D:\\JavaScriptTestHost\\src\\JSTestHost\\Environment\\Node\\EventDispatcher.ts:27:21)"}}
...
```

**Comment by smadala** [comment]
@karanjitsingh Can you update this issue with detail repro steps?

**Comment by smadala** [comment]
Fixed in https://github.com/Microsoft/vstest/pull/1656
