### ISSUE TITLE
NUnit3-vs-adapter raises exception when used with "UseVerifiableInstrumentation" set to False.

### ISSUE THREAD

**Issue by pvlakshm** [Microsoft/vstest#1654]
This is related to NUnit-vs-adapter issue [#519](https://github.com/nunit/nunit3-vs-adapter/issues/519).<br>
I have created a reduced repro here: [BugRepro](https://github.com/pvlakshm/Samples/tree/master/BugRepro
).

**Comment by smadala** [comment]
I have debugged the issue and observed that exception is occurred while calling .ctor of `NUnit.Framework.Api.FrameworkController`
Below is the callstack.
```
{System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Security.VerificationException: Operation could destabilize the runtime.
   at NUnit.Framework.Api.FrameworkController..ctor(String assemblyNameOrPath, String idPrefix, IDictionary settings) in C:\src\nunit\nunit\src\NUnitFramework\framework\Api\FrameworkController.cs:line 68
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(String assemblyString, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)
   at System.AppDomain.CreateInstance(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityAttributes)
   at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityAttributes)
   at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityAttributes)
   at NUnit.Engine.Drivers.NUnit3FrameworkDriver.CreateObject(String typeName, Object[] args)}
```

We suspect this is due to the some security attribute/property of `nunit.framework.dll` assembly, [FrameworkController.cs](https://github.com/nunit/nunit-compactframework/blob/4d48d7a3f0dca99f7bcea3c24f6d63d063248606/src/NUnitFramework/framework/Api/FrameworkController#L53) type or FrameworkController.ctor code. **Removing nunit.framework.pdb from test-assembly source directory won't repro the issue**. 

`UseVerifiableInstrumentation` option is used by code coverage profiler to decide how to insert probe (records which blocks get executed) for each basic block in JIT-Compiled code.
Following is behavior for `True` and `False`.

- `True` : In case of true, code coverage(cc) profiler, use `Microsoft.VisualStudio.CodeCoverage.Shim.dll` which is loaded from GAC to insert probe. Due to Microsoft.VisualStudio.CodeCoverage.Shim.dll loaded from GAC this assembly CLR allows to insert the probes anywhere(Not sure about this).

- `False`: In case of cc profiler `Microsoft.VisualStudio.CodeCoverage.Shim.dll` won't be used, That can lead to unexpected behavior.


We don't recommend to change the default configuration of code coverage, see [doc](https://github.com/Microsoft/vstest-docs/blob/master/docs/configure.md).

May I know why you have to change the default configuration `<UseVerifiableInstrumentation>False</UseVerifiableInstrumentation>`?

**Comment by smadala** [comment]
@OsirisTerje Sorry, Forgot to tag you.

**Comment by OsirisTerje** [comment]
The configuration file comes from @NikitaEgorov , I assume he can answer.  Are you sure this is not some default file?

**Comment by smadala** [comment]
@NikitaEgorov Can you use custom runsettings file to enable code coverage with default configuration. 

@ShreyasRmsft @kaadhina Do you have idea why the RFT task settings `UseVerifiableInstrumentation` to `false` ?

**Comment by OsirisTerje** [comment]
@ShreyasRmsft This is from your code, can you please check connect up with https://github.com/nunit/nunit3-vs-adapter/issues/519.
