### ISSUE TITLE
Linux Test runner uses netcoreapp2.1 regardless of csproj TargetFramework of netcoreapp2.0

### ISSUE THREAD

**Issue by CIPop** [microsoft/vstest#1669]
## Description
In Linux, `dotnet run` doesn't seem to honor the TFM of a test application:
```XML
<TargetFramework>netcoreapp2.0</TargetFramework>
```

## Steps to reproduce

1. Clone https://github.com/azure/azure-iot-sdk-csharp
2. Checkout the `lts_2018_01` branch
2. b - I've worked around the issue. You would need to checkout commit id# 53fef330f8d6a62f39342ad82dc070c65ea1dcab
3. `cd provisioning\service\tests`
4. `dotnet test`

## Expected behavior

On Windows this works, as expected:

```
dotnet test
Build started, please wait...
Build completed.

Test run for S:\cs\provisioning\service\tests\bin\Debug\netcoreapp2.0\Microsoft.Azure.Devices.Provisioning.Service.Test.dll(.NETCoreApp,Version=v2.0)
Microsoft (R) Test Execution Command Line Tool Version 15.7.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

Total tests: 123. Passed: 123. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 1.4527 Seconds
```

## Actual behavior

On Linux this fails, apparently due to to https://github.com/dotnet/corefx/issues/30793.
```
Test run for /home/jenkins/azure-iot-sdk-csharp/provisioning/service/tests/bin/Debug/netcoreapp2.0/Microsoft.Azure.Devices.Provisioning.Service.Test.dll(.NETCoreApp,Version=v2.0)
Microsoft (R) Test Execution Command Line Tool Version 15.7.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
Failed   QueryResult_Constructor_SucceedOnIndividualEnrollment
Error Message:
 Test method Microsoft.Azure.Devices.Provisioning.Service.Test.QueryResultTests.QueryResult_Constructor_SucceedOnIndividualEnrollment threw exception:
Microsoft.Azure.Devices.Provisioning.Service.ProvisioningServiceClientException:  ---> System.ArgumentException: parameter is not a valid Base64 string ---> System.FormatException: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.
Stack Trace:
    at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64String(String s)
   at Microsoft.Azure.Devices.Provisioning.Service.ParserUtils.EnsureBase64String(String input) in /home/jenkins/azure-iot-sdk-csharp/provisioning/service/src/Config/ParserUtility.cs:line 65
--- End of inner exception stack trace ---
    at Microsoft.Azure.Devices.Provisioning.Service.ParserUtils.EnsureBase64String(String input) in /home/jenkins/azure-iot-sdk-csharp/provisioning/service/src/Config/ParserUtility.cs:line 69
   at Microsoft.Azure.Devices.Provisioning.Service.TpmAttestation.set_EndorsementKey(String value) in /home/jenkins/azure-iot-sdk-csharp/provisioning/service/src/Config/TpmAttestation.cs:line 63
   at Microsoft.Azure.Devices.Provisioning.Service.TpmAttestation..ctor(String endorsementKey, String storageRootKey) in /home/jenkins/azure-iot-sdk-csharp/provisioning/service/src/Config/TpmAttestation.cs:line 40
--- End of inner exception stack trace ---
    at Microsoft.Azure.Devices.Provisioning.Service.TpmAttestation..ctor(String endorsementKey, String storageRootKey) in /home/jenkins/azure-iot-sdk-csharp/provisioning/service/src/Config/TpmAttestation.cs:line 45
   at lambda_method(Closure , Object[] )
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract contract, JsonProperty containerProperty, JsonReader reader, Type objectType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract contract, JsonProperty containerProperty, JsonReader reader, Type objectType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Microsoft.Azure.Devices.Provisioning.Service.QueryResult..ctor(String typeString, String bodyString, String continuationToken) in /home/jenkins/azure-iot-sdk-csharp/provisioning/service/src/Config/QueryResult.cs:line 120
   at Microsoft.Azure.Devices.Provisioning.Service.Test.QueryResultTests.QueryResult_Constructor_SucceedOnIndividualEnrollment() in /home/jenkins/azure-iot-sdk-csharp/provisioning/service/tests/Config/QueryResultTests.cs:line 178


Total tests: 123. Passed: 122. Failed: 1. Skipped: 0.
Test Run Failed.
Test execution time: 1.9479 Seconds
```

## Diagnostic logs
[log.txt](https://github.com/Microsoft/vstest/files/2156891/log.txt)

## Environment
Ubuntu 16.04 (`FROM ubuntu:xenial`) docker container with .NET Core 2.1 SDK (`RUN apt-get install -y dotnet-sdk-2.1`).

**Comment by abhishkk** [comment]
@CIPop 
Are you still facing this issue?
I see reference of this pull request: https://github.com/Azure/azure-iot-sdk-csharp/pull/545

**Comment by CIPop** [comment]
> Are you still facing this issue?

Yes - this is a bug in vstest, not our SDK. The referenced PR is for a workaround in our code.
The issue is that vstest is not using the specified TFM which is a big impact for us: our LTS bits were released with .NET Core 2.0 support only and we are now blocked on testing them against the correct .NET Core version.

**Comment by karanjitsingh** [comment]
@CIPop, I know this is a very delayed response, in case you're still getting this issue.

From the logs you provided 

```
TpTrace Verbose 0  737, 4, 20180702, 213855.232, 276041503966600, vstest.console.dll, DotnetTestHostManager Starting process 'usrsharedotnetdotnet' with command line 'exec --runtimeconfig homejenkinsazure-iot-sdk-csharpprovisioningservicetestsbinDebugnetcoreapp2.0Microsoft.Azure.Devices.Provisioning.Service.Test.runtimeconfig.json --depsfile homejenkinsazure-iot-sdk-csharpprovisioningservicetestsbinDebugnetcoreapp2.0Microsoft.Azure.Devices.Provisioning.Service.Test.deps.json
```

Based on the runtimeconfig the runtime will be loaded, VSTest has no control over whether to load netcoreapp2.0 or netcoreapp2.1

**Comment by karanjitsingh** [comment]
@CIPop, I tried an experiment, I took the failing test code and ran it in a new console app. On running the console app it throws the same expection

```bash
karan@karan-vm:~/azure-iot-sdk-csharp/provisioning/service/tests/console$ dotnet bin/Debug/netcoreapp2.0/console.dll
 
Unhandled Exception: Microsoft.Azure.Devices.Provisioning.Service.ProvisioningServiceClientException ---> System.ArgumentException: parameter is not a valid Base64 string ---> System.FormatException: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64String(String s)
   at Microsoft.Azure.Devices.Provisioning.Service.ParserUtils.EnsureBase64String(String input) in /home/karan/azure-iot-sdk-csharp/provisioning/service/src/Config/ParserUtility.cs:line 65
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Provisioning.Service.ParserUtils.EnsureBase64String(String input) in /home/karan/azure-iot-sdk-csharp/provisioning/service/src/Config/ParserUtility.cs:line 69
   at Microsoft.Azure.Devices.Provisioning.Service.TpmAttestation.set_EndorsementKey(String value) in /home/karan/azure-iot-sdk-csharp/provisioning/service/src/Config/TpmAttestation.cs:line 63
   at Microsoft.Azure.Devices.Provisioning.Service.TpmAttestation..ctor(String endorsementKey, String storageRootKey) in /home/karan/azure-iot-sdk-csharp/provisioning/service/src/Config/TpmAttestation.cs:line 40
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Provisioning.Service.TpmAttestation..ctor(String endorsementKey, String storageRootKey) in /home/karan/azure-iot-sdk-csharp/provisioning/service/src/Config/TpmAttestation.cs:line 45
   at lambda_method(Closure , Object[] )
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract contract, JsonProperty containerProperty, JsonReader reader, Type objectType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract contract, JsonProperty containerProperty, JsonReader reader, Type objectType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Microsoft.Azure.Devices.Provisioning.Service.QueryResult..ctor(String typeString, String bodyString, String continuationToken) in /home/karan/azure-iot-sdk-csharp/provisioning/service/src/Config/QueryResult.cs:line 120
   at tests.Program.Main(String[] args) in /home/karan/azure-iot-sdk-csharp/provisioning/service/tests/console/Program.cs:line 51
Aborted (core dumped)
```

I'd suggest opening the same issue on dotnet repo. If you want to try out my experiment check [this branch](https://github.com/karanjitsingh/azure-iot-sdk-csharp/tree/exp) that was created with your repro commit as base

**Comment by nohwnd** [comment]
As mentioned above the runtime config is used for execution, and that is the case for any version, the actual resolved version depends on the roll forward policy (defined in your project or in environment variables).
