### ISSUE TITLE
Could not load type 'System.Runtime.Loader.AssemblyLoadContext' from assembly 'System.Runtime.Loader'

### ISSUE THREAD

**Issue by efrainsteinbach** [Microsoft/vstest#1715]
## Description
Somehow having a custom `nuget.config` in a parent folder of the test project, with a setting `globalPackagesFolder` breaks the execution **on Linux hosts**.

## Steps to reproduce
- Get the repro ZIP [here](http://s000.tinyupload.com/download.php?file_id=11605448365005286119&t=1160544836500528611949211).
- Run 'docker build .' .. see the dockerfile: this takes an ubuntu image, installs dotnet 2.1 and runs the tests.

## Expected behavior
The test is run.

## Actual behavior
The following error shows up after 'Starting test execution, please wait...':

```
Microsoft.VisualStudio.TestPlatform.ObjectModel.SettingsException: An error occurred while loading the run settings.  Error: Could not load type 'System.Runtime.Loader.AssemblyLoadContext' from assembly 'System.Runtime.Loader, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. ---> System.TypeLoadException: Could not load type 'System.Runtime.Loader.AssemblyLoadContext' from assembly 'System.Runtime.Loader, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
   at Microsoft.VisualStudio.TestPlatform.PlatformAbstractions.PlatformAssemblyResolver..ctor()
   at Microsoft.VisualStudio.TestPlatform.Common.Utilities.AssemblyResolver..ctor(IEnumerable`1 directories)
   at Microsoft.VisualStudio.TestPlatform.Common.ExtensionFramework.TestPluginCache.SetupAssemblyResolver(String extensionAssembly)
   at Microsoft.VisualStudio.TestPlatform.Common.ExtensionFramework.TestPluginCache.DiscoverTestExtensions[TPluginInfo,TExtension](String endsWithPattern)
   at Microsoft.VisualStudio.TestPlatform.Common.SettingsProvider.SettingsProviderExtensionManager.Create()
   at Microsoft.VisualStudio.TestPlatform.Common.RunSettings.ReadRunSettings(XmlReader reader)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.TestPlatform.Common.RunSettings.ReadRunSettings(XmlReader reader)
   at Microsoft.VisualStudio.TestPlatform.Common.RunSettings.InitializeSettingsProviders(String settings)
   at Microsoft.VisualStudio.TestPlatform.Common.Utilities.RunSettingsUtilities.CreateAndInitializeRunSettings(String settingsXml)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.BaseRunTests.SetContext()
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.ExecutionManager.StartTestRun(Dictionary`2 adapterSourceMap, String package, String runSettings, TestExecutionContext testExecutionContext, ITestCaseEventsHandler testCaseEventsHandler, ITestRunEventsHandler runEventsHandler)

Test Run Aborted.
```

## Diagnostic logs
Get them yourself from the repro zip (Logs.txt).

## Environment
Ubuntu Xenial, dotnet 2.1
Microsoft.NET.Test.Sdk 15.8.0
NUnit 3.10.1, NUnit3TestAdapter 3.10.0

**Comment by singhsarab** [comment]
@efrainsteinbach Apologies, we have not been able to get back on this one.
I tried fetching the repro, but unfortunately, it was deleted, Can you please provide another link please.

**Comment by efrainsteinbach** [comment]
I'm sorry - unfortunately I don't have these files anymore. 😞

**Comment by singhsarab** [comment]
@efrainsteinbach Without the files, I am really not sure how to make progress on this one. 

I will be closing this issue for now. I'll re-open it once you have a repro project that you can share. Hope that's fine with you. :)

**Comment by amitla** [comment]
Hi @singhsarab,

This happened to me as well. you can find the reproduciton project attached.
[UnitTestProject1.zip](https://github.com/Microsoft/vstest/files/2977863/UnitTestProject1.zip)


Any way to work around this issue for the time being?

Thanks.

**Comment by cltshivash** [comment]
@amitla  : https://github.com/dotnet/corefx/issues/22142#issuecomment-473392197 (Please refer to this issue). System.Runtime.Loader is not supported for full framework. The repro that is added targets full framework. ( var gh = System.Runtime.Loader.AssemblyLoadContext.Default;) works fine in a net core test project.
