### ISSUE TITLE
Cannot run Unit tests in Release mode from CLI when a winrt module is present in sln

### ISSUE THREAD

**Issue by nvineeth** [Microsoft/vstest#1720]
## Description
Attached is the test sln consisting of a C++ WinRT component and a C# Unit test UWP Project.
`vstest.console.exe` fails to run the tests, due to which we are unable to automate the tests on a build machine.

## Steps to reproduce
* Extract the contents of the attached `WindowsRuntimeComponent1.7z`
[WindowsRuntimeComponent1.zip](https://github.com/Microsoft/vstest/files/2265258/WindowsRuntimeComponent1.zip)
* Launch `Develop Console for VS 2017`
* Build using command : `msbuild /p:configuration=Release;platform=x64 /verbosity:minimal WindowsRuntimeComponent1.sln`
* Install the necessary certificates by running the script `WindowsRuntimeComponent1\UnitTestProject1\AppPackages\UnitTestProject1_1.0.0.0_x64_Test\Add-AppDevPackage.ps1` in powershell
* Run the unit tests with command: `vstest.console.exe --diag:Diagnostics.txt  /InIsolation /logger:trx /Platform:x64 UnitTestProject1\AppPackages\UnitTestProject1_1.0.0.0_x64_Test\UnitTestProject1_1.0.0.0_x64.appx`

## Expected behavior
* The Unit tests must run.

## Actual behavior
* We see the following output:
```
vstest.console.exe --diag:Diagnostics.txt  /InIsolation /logger:trx /Platform:x64 UnitTestProject1\AppPackages\UnitTestProject1_1.0.0.0_x64_Test\UnitTestProject1_1.0.0.0_x64.appx
Microsoft (R) Test Execution Command Line Tool Version 15.7.2
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
Logging Vstest Diagnostics in file: C:\Users\Anonymous\devel\tmp\WindowsRuntimeComponent1\Diagnostics.txt
Attempting to deploy to target 'Local Machine'.
Deployment operation succeeded, package moniker: 'ee00b760-d48e-4a93-9ed7-12fe69dd03c9_1.0.0.0_x64__ebktjqa94myh4'.
Attempting to launch app with app user model Id 'ee00b760-d48e-4a93-9ed7-12fe69dd03c9_ebktjqa94myh4!vstest.executionengine.universal.App' and arguments '--port 58982 --endpoint 127.0.0.1:058982 --role client --parentprocessid 4080 --diag "C:\Users\Anonymous\devel\tmp\WindowsRuntimeComponent1\Diagnostics.host.18-08-07_12-11-16_01005_6.txt" --telemetryoptedin false'.
Successfully launched process Id '11536'.

......... Hangs for 10-20 seconds ..........

Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Failed to initialize client proxy: could not connect to test process.
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyExecutionManager.StartTestRun(TestRunCriteria testRunCriteria, ITestRunEventsHandler eventHandler)
Closing app with package full name 'ee00b760-d48e-4a93-9ed7-12fe69dd03c9_1.0.0.0_x64__ebktjqa94myh4'.

Test Run Aborted.
```

## Diagnostic logs
[Diagnostics.txt](https://github.com/Microsoft/vstest/files/2265312/Diagnostics.txt)

## Environment
* VS 2017 15.7.6
* Windows 10 Version 1709.

**Comment by singhsarab** [comment]
@nvineeth I looked into your repro project.
The problem I see is that your Unit test project is pointing to older version of TestPlatform.Universal (15.0.0.0) while expected to point to 15.5.0.0. (which I am guessing is because of project.json files present in the project).

I was able to get it working,
1. Setting UnitTestPlatformVersion to 15.5 in the csproj
2. Restore and build the project.
3. Run via appxrecipe instead, like

>vstest.console.exe --diag:Diagnostics.txt /InIsolation /logger:trx /Platform:x64 "WindowsRuntimeComponent1\UnitTestProject1\bin\x64\Release\UnitTestProject1.build.appxrecipe"
