### ISSUE TITLE
Test discovery fails with Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).

### ISSUE THREAD

**Issue by frjol** [Microsoft/vstest#1823]
We are having an issue regarding Native C++ tests discovery in Visual Studio or in command line. It seems to be new in 15.8. Browsing around I could not find any work around or similar issue opened. I managed to build the same release version and could not find an easy way of fixing it.

> vstest.console.exe 
> "D:\TFS\Synergis\Dev\Integration\Main\Source\bin\Debug\AxisExtension.Native.UnitTests.dll" /TestAdapterPath:D:\TFS\Synergis\Dev\Integration\Main\Source\bin\Debug /diag:diag.txt
> Microsoft (R) Test Execution Command Line Tool Version 15.8.0-dev
> Copyright (c) Microsoft Corporation. All rights reserved.
> 
> Starting test execution, please wait...
> Logging Vstest Diagnostics in file: D:\Code\vstest-rel-15.8\diag.txt
> Data collection : Logging DataCollector Diagnostics in file: D:\Code\vstest-rel-15.8\diag.datacollector.18-10-25_09-18-01_06900_1.txt
> Data collection : Data collector 'UnitTestIsolation' threw an exception during type loading, construction, or initialization: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentOutOfRangeException: Length cannot be less than zero.
> Parameter name: length
> at System.String.Substring(Int32 startIndex, Int32 length)
> at Microsoft.VisualStudio.IntelliTrace.TraceLogger.get_InstallDir() in F:\dd\src\edev\diagnostics\intellitrace\tracelog\TraceLogger.cs:line 1222
> at Microsoft.VisualStudio.IntelliTrace.TraceLogger.GetProfilerEnvVars() in F:\dd\src\edev\diagnostics\intellitrace\tracelog\TraceLogger.cs:line 937
> at Microsoft.VisualStudio.TraceCollector.CommonDataCollector..ctor() in F:\dd\src\edev\diagnostics\intellitrace\collectorV2\CommonDataCollector.cs:line 142
> at Microsoft.VisualStudio.TraceCollector.UnitTestIsolationDataCollector..ctor() in F:\dd\src\edev\diagnostics\intellitrace\collectorV2\UnitTestIsolationCollector\UnitTestIsolationDataCollector.cs:line 35
> --- End of inner exception stack trace ---
> at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
> at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
> at System.Activator.CreateInstance(Type type, Boolean nonPublic)
> at System.Activator.CreateInstance(Type type)
> at Microsoft.VisualStudio.TestPlatform.Common.ExtensionFramework.TestPluginManager.CreateTestExtension[T](Type extensionType) in D:\Code\vstest-rel-15.8\src\Microsoft.TestPlatform.Common\ExtensionFramework\TestPluginManager.cs:line 96
> at Microsoft.VisualStudio.TestPlatform.Common.ExtensionFramework.Utilities.LazyExtension`2.get_Value() in D:\Code\vstest-rel-15.8\src\Microsoft.TestPlatform.Common\ExtensionFramework\Utilities\LazyExtension.cs:line 153
> at Microsoft.VisualStudio.TestPlatform.Common.DataCollector.DataCollectionManager.TryGetTestExtension(String extensionUri) in D:\Code\vstest-rel-15.8\src\Microsoft.TestPlatform.Common\DataCollection\DataCollectionManager.cs:line 404
> at Microsoft.VisualStudio.TestPlatform.Common.DataCollector.DataCollectionManager.LoadAndInitialize(DataCollectorSettings dataCollectorSettings, String settingsXml) in D:\Code\vstest-rel-15.8\src\Microsoft.TestPlatform.Common\DataCollection\DataCollectionManager.cs:line 429.
> Logging TestHost Diagnostics in file: D:\Code\vstest-rel-15.8\diag.host.18-10-25_09-18-01_79093_1.txt
> Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).
> No test is available in D:\TFS\Synergis\Dev\Integration\Main\Source\bin\Debug\AxisExtension.Native.UnitTests.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
> 
> Test Run Failed.

We have the same issue just listing the tests. In some cases, it can list a couple tests before failing. We could not find anything wrong in our tests related to that issue. The issue is present in master as well. It was not present in 15.7.
I included diag files.

Thanks,

[diag.datacollector.18-10-25_09-18-01_06900_1.txt](https://github.com/Microsoft/vstest/files/2515154/diag.datacollector.18-10-25_09-18-01_06900_1.txt)
[diag.host.18-10-25_09-18-01_79093_1.txt](https://github.com/Microsoft/vstest/files/2515155/diag.host.18-10-25_09-18-01_79093_1.txt)
[diag.txt](https://github.com/Microsoft/vstest/files/2515156/diag.txt)

**Comment by frjol** [comment]
I managed to get the call stack of the error in testhost.x86.exe. 

> at System.Guid.TryParseGuidWithNoStyle(String guidString, GuidResult& result)
>    at System.Guid.TryParseGuid(String g, GuidStyles flags, GuidResult& result)
>    at System.Guid..ctor(String g)
>    at System.ComponentModel.GuidConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
>    at Microsoft.VisualStudio.TestPlatform.ObjectModel.TestObject.ConvertPropertyFrom[T](TestProperty property, CultureInfo culture, Object value) in D:\Code\vstest-rel-15.8\src\Microsoft.TestPlatform.ObjectModel\TestObject.cs:line 315
>    at Microsoft.VisualStudio.TestPlatform.ObjectModel.TestObject.SetPropertyValue[T](TestProperty property, T value, CultureInfo culture) in D:\Code\vstest-rel-15.8\src\Microsoft.TestPlatform.ObjectModel\TestObject.cs:line 216
>    at Microsoft.VisualStudio.TestPlatform.ObjectModel.TestObject.SetPropertyValue[T](TestProperty property, T value) in D:\Code\vstest-rel-15.8\src\Microsoft.TestPlatform.ObjectModel\TestObject.cs:line 155
>    at Microsoft.VisualStudio.TestTools.CppUnitTestFramework.CppUnitTestExtension.TestCaseForDiscover.AddAttributes(String[] attributeNames, String[] attributeValues) in F:\dd\src\vset\Agile\CppUnit\cppunittestextension\TestCase.cs:line 143
>    at Microsoft.VisualStudio.TestTools.CppUnitTestFramework.CppUnitTestExtension.TestCaseForDiscover..ctor(ITestCase testCase, String executorUri) in F:\dd\src\vset\Agile\CppUnit\cppunittestextension\TestCase.cs:line 75
>    at Microsoft.VisualStudio.TestTools.CppUnitTestFramework.CppUnitTestExtension.TestDiscoverer.GetTestsImpl(String filePath, IMessageLogger logger, ITestCaseDiscoverySink discoverySink) in F:\dd\src\vset\Agile\CppUnit\cppunittestextension\TestDiscoverer.cs:line 142
>    
>

**Comment by frjol** [comment]
It seems that this is due to the TEST_METHOD_ATTRIBUTE("TestType", "UnitTest") that now requires a Guid instead of a string like before. Actually, it converts the string directly into Guid.

**Comment by mayankbansal018** [comment]
@frjol , can you please share a sample project with us to diagnose it better? Also you mentioned that the tests are Native, but from the logs I see you have also enabled Fakes, are you running to managed, & native tests?

**Comment by frjol** [comment]
```
#include "CppUnitTest.h"
using namespace Microsoft::VisualStudio::CppUnitTestFramework;

TEST_CLASS(TestClassExample)
{
    BEGIN_TEST_METHOD_ATTRIBUTE(TestMethodExample)
    TEST_OWNER(L"john")
    TEST_METHOD_ATTRIBUTE(L"TestType", L"UnitTest") //This breaks the discovery
    END_TEST_METHOD_ATTRIBUTE()
    TEST_METHOD(TestMethodExample);
};

void TestClassExample::TestMethodExample()
{
    Assert::IsTrue(true);
}
```

You can see that the `TEST_METHOD_ATTRIBUTE` with "TestType" was working in 15.7 while now it is broken in 15.8.

It breaks in TestHost.x86.exe at TestObject.cs line 311
`return converter.ConvertFrom(null, culture, value);`
Trying to convert the string "UnitTest" to a Guid.

**Comment by mayankbansal018** [comment]
@frjol , I analyzed this issue, & the reason for this is, that one of our internal test adapter `Microsoft.VisualStudio.TestPlatform.Extensions.TmiAdapter.dll`, is already registering a property `TypeType`, & setting it's value type to be `Guid`, hence when you define it on your C++ test case, it says I've already registered this property, & it's Type is Guid, which causes us to throw the exception when we find it's type to String. 

I'll double check internally that when was this code added, but can you please try to rename your Attribute, & try again.

**Comment by mayankbansal018** [comment]
@frjol , Just checked it, & it seems we have recently added this property to one of our legacy adapters. I'll talk to the team to see if that Property is needed, or can it be avoided or not.

Assuming worst case, where we cannot avoid that, is it possible for you to take a fix at your end?

**Comment by frjol** [comment]
We are considering removing/renaming the property to resolve the discovery issue. This might require a lot of changes on our end. At least, we have a workaround.
