### ISSUE TITLE
Code coverage is flaky, throws missing method exceptions

### ISSUE THREAD

**Issue by onovotny** [Microsoft/vstest#1926]
See the results here:
https://dev.azure.com/dotnet/Rx.NET/_build/results?buildId=10312

It's throwing errors like

```
Error Message:
 System.MissingMethodException : Method not found: 'Void Microsoft.VisualStudio.CodeCoverage.Shim.135762730__coverage_runtime_method__6817_16922__(UInt64)'.
Stack Trace:
   at System.Linq.AsyncEnumerable.ToAsyncEnumerable[TSource](IEnumerable`1 source)
   at Tests.AsyncQueryableExTests.<>c.<MinAsync14>b__188_2() in D:\a\1\s\Ix.NET\Source\System.Linq.Async.Queryable.Tests\AsyncQueryableTests.Generated.cs:line 1962
   at Tests.AssertEx.Throws[T](Action action, Func`2 assert) in D:\a\1\s\Ix.NET\Source\System.Linq.Async.Queryable.Tests\AssertEx.cs:line 19
   at Tests.AsyncQueryableExTests.MinAsync14() in D:\a\1\s\Ix.NET\Source\System.Linq.Async.Queryable.Tests\AsyncQueryableTests.Generated.cs:line 1964

```

Other times it works.

**Comment by mayankbansal018** [comment]
@onovotny apologies for getting so late on this, can you please share if this is still happening, if yes, can you please share a build, the above one expired.

Or better if we could have some repro steps

**Comment by onovotny** [comment]
We switched to Coverlet

**Comment by geirsagberg** [comment]
Can confirm this happens for me too, using `dotnet --collect "Code Coverage"`.

**Comment by juanperezADD** [comment]
We have the same error using `dotnet --collect "Code Coverage"`. 

The error occurs randomly and it's difficult to reproduce.

Could this issue be reopened?

**Comment by mayankbansal018** [comment]
@juanperezADD can you please create a new bug, & mention the repro steps, we track these issues internally as well, & reopening long closed bugs, tends to mess up our tracking.

**Comment by juanperezADD** [comment]
@mayankbansal018 I have created the issue #2176.
