### ISSUE TITLE
Running vstest.console with legacy mstest test adapter

### ISSUE THREAD

**Issue by shenhong1000** [Microsoft/vstest#1954]
This is more like a question I guess. We want to run vstest.console.exe with a legacy mstest test adapter. I found a document online which points out runsettings cannot take some mstest test adapter (vstest.console doesn't even locate our mstest adapater configured in the runsettings), however I can pass testsettings directly. I found it do tried to load our test adapter configured in testsettings, however it throws exception as following. So my questions is 
1. How can I confirm if our mstest test adapter is workable on vstest.console.exe?
2. Another options is implementing a new test adapter for vstest.console. Is there a easy way/tool to convert mstest test adapater to vstest.console test adapater? Also do you have a detailed documents to implement vstest.console test adapater?

C:\TestCases>"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" QAPlatform.BizMgt.exe /Tests:TestPlatform.CacheTests.UserCacheFlushAfterTeamMembershipChange /settings:local.testsettings
Microsoft (R) Test Execution Command Line Tool Version 14.0.25420.1
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test discovery, please wait...
Warning: The diagnostic data adapter 'Microsoft.Crm.QA.MsTest.Adapters.UtfDataAdapter, Microsoft.Crm.QA.MsTest.Adapters.Utf, Version=9.0.0.0, Culture=neutral, PublicKeyToken=2db8a640daea42cf' on agent 'Aurora84320' threw an exception during type loading, construction, or initialization: System.ArgumentException: Invalid directory on URL.
   at System.Security.Util.DirectoryString.CreateSeparatedString(String directory)
   at System.Security.Util.URLString.ParseFileURL(String url)
   at System.Security.Util.URLString.GetFileName()
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Microsoft.VisualStudio.TestTools.DataCollection.ExecutionPluginManager.GetCollectorTypeHandlingVersionMismatch(String collectorTypeName).

**Comment by cltshivash** [comment]
1. To use older mstest test adpater you will need to ensure that the adpater is registered on the machine running the tests and validate the execution through mstest.exe. To make it run via vstest.console.exe you will need testsettings file. However,
2. We highly recommend moving to a vstest adapter as the testsettings and the mstest are deprecated and will be removed in a future release of VS. Please refer to : https://github.com/Microsoft/vstest-docs/blob/master/RFCs/0004-Adapter-Extensibility.md
