### ISSUE TITLE
TestHost SocketClient CancellationTokenSource has been disposed

### ISSUE THREAD

**Issue by Mobrockers** [Microsoft/vstest#1965]
## Description
Intermittent exceptions with following stacktrace when running vstest.console.exe:

Unhandled Exception: System.ObjectDisposedException: The CancellationTokenSource has been disposed.
   at System.Threading.CancellationTokenSource.ThrowObjectDisposedException()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.SocketClient.Stop()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.TestRequestHandler.Dispose()
   at Microsoft.VisualStudio.TestPlatform.TestHost.DefaultEngineInvoker.Invoke(IDictionary`2 argsDictionary)
   at Microsoft.VisualStudio.TestPlatform.TestHost.Program.Run(String[] args)
   at Microsoft.VisualStudio.TestPlatform.TestHost.Program.Main(String[] args)

## Steps to reproduce
Not sure

## Expected behavior
No random exceptions from testrunner infrastructure

## Actual behavior
Intermittent exceptions with stacktrace:
Unhandled Exception: System.ObjectDisposedException: The CancellationTokenSource has been disposed.
   at System.Threading.CancellationTokenSource.ThrowObjectDisposedException()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.SocketClient.Stop()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.TestRequestHandler.Dispose()
   at Microsoft.VisualStudio.TestPlatform.TestHost.DefaultEngineInvoker.Invoke(IDictionary`2 argsDictionary)
   at Microsoft.VisualStudio.TestPlatform.TestHost.Program.Run(String[] args)
   at Microsoft.VisualStudio.TestPlatform.TestHost.Program.Main(String[] args)

## Environment
vstest.console.exe 16.0.0 on windows 10

**Comment by ShreyasRmsft** [comment]
@Mobrockers hmmm, can you provide the full diag logs? Also does has this been reproing for a particular test project you have?

Looking for some sort of a repro in case the full diag logs don't help in diagnosing the issue. Thanks.

**Comment by cltshivash** [comment]
Please do provide logs (or a minimal repro as suggested by the template).
