### ISSUE TITLE
TFS. Failed to launch testhost. Possible to make it working?

### ISSUE THREAD

**Issue by silentnightwalk** [Microsoft/vstest#1983]
## Description
One test run on server resulted in (say) half of tests to be countered. From [my previous post and the answer],(https://github.com/Microsoft/vstest/issues/1979) i found out that once connection b/w vstest and testhost breaks, the other tests do not get run.

Second and 3rd and 4th and so on... test runs **fail to launch testshost** at all. None of tests are countered in .trx. No .trx files. To make it more clear, at this stage i'm trying to run each test in its own `exec` with `/Tests:NameOfTest` specified.

**Is it possible to execute some command to make the testhost working?**

## Expected behavior
Would be great to know how to get testhost working.

## Actual behavior
Failed to launch testhost. I guess that this error occured once and keeped on occuring afterwards. Could be that, at some point some obstacle appeared. 

## Diagnostic logs
The errors are (one followed by another):
```
TpTrace Error: 0 : ###, 1, 2019/04/08, 11:24:48.478, ####, vstest.console.dll, ProxyOperationManager: Failed to launch testhost :System.AggregateException: One or more errors occurred. (The system cannot find the file specified) ---> System.ComponentModel.Win32Exception: The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.VisualStudio.TestPlatform.PlatformAbstractions.ProcessHelper.LaunchProcess(String processPath, String arguments, String workingDirectory, IDictionary`2 envVariables, Action`2 errorCallback, Action`1 exitCallBack)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DefaultTestHostManager.LaunchHost(TestProcessStartInfo testHostStartInfo, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DefaultTestHostManager.<>c__DisplayClass35_0.<LaunchTestHostAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DefaultTestHostManager.LaunchTestHostAsync(TestProcessStartInfo testHostStartInfo, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources)
---> (Inner Exception #0) System.ComponentModel.Win32Exception (2): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.VisualStudio.TestPlatform.PlatformAbstractions.ProcessHelper.LaunchProcess(String processPath, String arguments, String workingDirectory, IDictionary`2 envVariables, Action`2 errorCallback, Action`1 exitCallBack)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DefaultTestHostManager.LaunchHost(TestProcessStartInfo testHostStartInfo, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DefaultTestHostManager.<>c__DisplayClass35_0.<LaunchTestHostAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DefaultTestHostManager.LaunchTestHostAsync(TestProcessStartInfo testHostStartInfo, CancellationToken cancellationToken)<---

TpTrace Error: 0 : ###, 1, 2019/04/08, 11:24:48.479, ####, vstest.console.dll, ProxyDiscoveryManager.DiscoverTests: Failed to discover tests: Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Failed to launch testhost with error: System.AggregateException: One or more errors occurred. (The system cannot find the file specified) ---> System.ComponentModel.Win32Exception: The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.VisualStudio.TestPlatform.PlatformAbstractions.ProcessHelper.LaunchProcess(String processPath, String arguments, String workingDirectory, IDictionary`2 envVariables, Action`2 errorCallback, Action`1 exitCallBack)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DefaultTestHostManager.LaunchHost(TestProcessStartInfo testHostStartInfo, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DefaultTestHostManager.<>c__DisplayClass35_0.<LaunchTestHostAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DefaultTestHostManager.LaunchTestHostAsync(TestProcessStartInfo testHostStartInfo, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources)
---> (Inner Exception #0) System.ComponentModel.Win32Exception (2): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.VisualStudio.TestPlatform.PlatformAbstractions.ProcessHelper.LaunchProcess(String processPath, String arguments, String workingDirectory, IDictionary`2 envVariables, Action`2 errorCallback, Action`1 exitCallBack)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DefaultTestHostManager.LaunchHost(TestProcessStartInfo testHostStartInfo, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DefaultTestHostManager.<>c__DisplayClass35_0.<LaunchTestHostAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DefaultTestHostManager.LaunchTestHostAsync(TestProcessStartInfo testHostStartInfo, CancellationToken cancellationToken)<---

   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyDiscoveryManager.DiscoverTests(DiscoveryCriteria discoveryCriteria, ITestDiscoveryEventsHandler2 eventHandler)
```

## Environment
`Dotnet.exe` was the latest version 2-3 weeks ago.

**Comment by mayankbansal018** [comment]
From the logs it seems that testhost.exe was not even found by vstest.console. Can you share the diagnostics logs, it will contain information from where we were trying to launch testhost process.

**Comment by silentnightwalk** [comment]
@mayankbansal018, thanks, here's some diagnostics:
```
TpTrace Verbose: 0 : ###, 1, 2019/04/08, 11:24:34.332, ############, vstest.console.dll, DefaultTestHostmanager: Full path of TestHost\testhost.exe is C:\Program Files\dotnet\sdk\2.1.503\Extensions\..//TestHost\testhost.exe
TpTrace Verbose: 0 : ###, 5, 2019/04/08, 11:24:34.334, 5963890872610, vstest.console.dll, Launching default test Host Process C:\Program Files\dotnet\sdk\2.1.503\Extensions\..//TestHost\testhost.exe with arguments  --port ### --endpoint 127.0.0.1:###--role client --parentprocessid #### --diag "########################\bin\Release\diag_TestFindCommand.host.19-04-08_11-24-34_33102_1.txt" --tracelevel 4 --telemetryoptedin false
TpTrace Verbose: 0 : ###, 5, 2019/04/08, 11:24:34.334, ########, vstest.console.dll, DefaultTestHostManager: Starting process 'C:\Program Files\dotnet\sdk\2.1.503\Extensions\..//TestHost\testhost.exe' with command line ' --port ####--endpoint 127.0.0.1:######--role client --parentprocessid ### --diag "########################\bin\Release\diag_TestFindCommand.host.19-04-08_11-24-34_33102_1.txt" --tracelevel 4 --telemetryoptedin false'
```

**Comment by mayankbansal018** [comment]
@silentnightwalk from the logs the location from where vstest is trying to run the testhost is correct, & from the above exception the only conclusion I can draw is that the testhost.exe is not present at that location.
I'm not sure why that would be, but can you confirm if on your build agents under path `C:\Program Files\dotnet\sdk\2.1.503\TestHost`, is testhost even present? Or alternatively can you please try to get latest dotnet sdk on your machines?

**Comment by silentnightwalk** [comment]
@mayankbansal018 , thanks!
I'll try to update or confirm the presence of testhost tomorrow. Sorry for misleading info: we have fresh dotnet on other machine, but on this one it's outdated...

**Comment by silentnightwalk** [comment]
Haven't yet had managed to update version. Hopefully, i'll do it on monday.
(i'll delete these two last comments later)

**Comment by mayankbansal018** [comment]
Any update on it?

**Comment by silentnightwalk** [comment]
Sorry for late reply.
After version update, now it's fine.
Not sure what the problem was.

**Comment by mayankbansal018** [comment]
Sure, please comment back here, if you find this issue again, I'll reopen it.

**Comment by jonnyguo1988** [comment]
I got the same issue recently, the testhost file is there. I finally fixed it by reinstall VS and add C:\Program Files\dotnet to PATH
