### ISSUE TITLE
TestPlatformException: Unable to find testhost.dll. Please publish your test project and retry

### ISSUE THREAD

**Issue by aminipour** [microsoft/vstest#2157]
## Description
When I build any of my projects, the build succeeds but I see a message in status bar saying:

> Unexpected error detected. Check the Tests Output Pane for details.

E.g. if I build one of my non-test projects I see this in Tests Output:

```
[06/09/2019 4:14:04.287 PM Informational] ---------- Discovery started ----------
[06/09/2019 4:14:04.831 PM Informational] NUnit Adapter 3.15.1.0: Test discovery starting
[06/09/2019 4:14:04.963 PM Informational] NUnit Adapter 3.15.1.0: Test discovery complete
[06/09/2019 4:14:05.012 PM Error] Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Unable to find [project_path]\bin\Debug\netcoreapp3.0\testhost.dll. Please publish your test project and retry.
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DotnetTestHostManager.GetTestHostPath(String runtimeConfigDevPath, String depsFilePath, String sourceDirectory)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DotnetTestHostManager.GetTestHostProcessStartInfo(IEnumerable`1 sources, IDictionary`2 environmentVariables, TestRunnerConnectionInfo connectionInfo)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyDiscoveryManager.DiscoverTests(DiscoveryCriteria discoveryCriteria, ITestDiscoveryEventsHandler2 eventHandler)
[06/09/2019 4:14:05.387 PM Informational] NUnit Adapter 3.15.1.0: Test discovery starting
[06/09/2019 4:14:05.619 PM Informational] NUnit Adapter 3.15.1.0: Test discovery complete
[06/09/2019 4:14:06.098 PM Informational] NUnit Adapter 3.15.1.0: Test discovery starting
[06/09/2019 4:14:06.321 PM Informational] NUnit Adapter 3.15.1.0: Test discovery complete
[06/09/2019 4:14:06.788 PM Informational] NUnit Adapter 3.15.1.0: Test discovery starting
[06/09/2019 4:14:07.753 PM Informational] NUnit Adapter 3.15.1.0: Test discovery complete
[06/09/2019 4:14:07.756 PM Informational] ========== Discovery aborted: -1 tests found (0:00:03.4678642) ==========
```

When I build an NUnit test project, I see a similar output but a little bit different:

```
[06/09/2019 4:27:18.607 PM Informational] ---------- Discovery started ----------
[06/09/2019 4:27:18.615 PM Error] Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Unable to find [project_path]\bin\Debug\netcoreapp3.0\testhost.dll. Please publish your test project and retry.
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DotnetTestHostManager.GetTestHostPath(String runtimeConfigDevPath, String depsFilePath, String sourceDirectory)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DotnetTestHostManager.GetTestHostProcessStartInfo(IEnumerable`1 sources, IDictionary`2 environmentVariables, TestRunnerConnectionInfo connectionInfo)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyDiscoveryManager.DiscoverTests(DiscoveryCriteria discoveryCriteria, ITestDiscoveryEventsHandler2 eventHandler)
[06/09/2019 4:27:19.041 PM Informational] NUnit Adapter 3.13.0.0: Test discovery starting
[06/09/2019 4:27:19.171 PM Informational] NUnit Adapter 3.13.0.0: Test discovery complete
[06/09/2019 4:27:19.667 PM Informational] NUnit Adapter 3.15.1.0: Test discovery starting
[06/09/2019 4:27:22.393 PM Informational] NUnit Adapter 3.15.1.0: Test discovery complete
[06/09/2019 4:27:22.394 PM Informational] NUnit Adapter 3.15.1.0: Test discovery starting
[06/09/2019 4:27:23.095 PM Informational] NUnit Adapter 3.15.1.0: Test discovery complete
[06/09/2019 4:27:23.098 PM Informational] ========== Discovery aborted: 1755 tests found (0:00:04.4893864) ==========
```

This `[project_path]` causing the exception is always the same project which is my TestInfrastructure which
* is not a test project
* is a class library
* has this property (or not, it doesn't have an effect) `<IsTestProject>false</IsTestProject>`
* references `NUnit 3.12.0`

## Steps to reproduce
```
<PropertyGroup>
   <TargetFramework>netcoreapp3.0</TargetFramework>
</PropertyGroup>
<ItemGroup>
   <PackageReference Include="NUnit" Version="3.12.0" />
</ItemGroup>
```

Build any project in solution.

[ConsoleApp2.zip](https://github.com/microsoft/vstest/files/3584394/ConsoleApp2.zip)

## Expected behavior
> Don't see this exception when I set `<IsTestProject>false</IsTestProject>`

## Environment
Win10-x64, netcore3.0 preview7

**Comment by aminipour** [comment]
Deleting bin and obj folders fixed this issue
