### ISSUE TITLE
The dotnet test command fails randomly with codecoverage

### ISSUE THREAD

**Issue by juanperezADD** [microsoft/vstest#2176]
## Description
This issue is a continuation of #1926.

When we are using dotnet test with codecoverage the following error occurs randomly:
 
```
Testhost process exited with error: Unhandled Exception: System.MissingMethodException: Method not found: 'Void Microsoft.VisualStudio.CodeCoverage.Shim.1124859581__coverage_runtime_method__23574_20339__(UInt64)'.
   at Newtonsoft.Json.JsonSerializerSettings..ctor()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.JsonDataSerializer..ctor()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.JsonDataSerializer.get_Instance()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.TestRequestHandler..ctor()
   at Microsoft.VisualStudio.TestPlatform.TestHost.DefaultEngineInvoker..ctor()
   at Microsoft.VisualStudio.TestPlatform.TestHost.Program.GetEngineInvoker(IDictionary`2 argsDictionary)
   at Microsoft.VisualStudio.TestPlatform.TestHost.Program.Run(String[] args)
   at Microsoft.VisualStudio.TestPlatform.TestHost.Program.Main(String[] args)
```

## Steps to reproduce
Execute the following command until the error occurs:
`dotnet test Solution.sln --logger trx --results-directory D:\W\JP\Git\Co\Wo\TestResults -c release --no-build --collect "Code coverage" --diag:log.txt`

## Expected behavior
The dotnet test command works well with codecoverage.

## Actual behavior
The dotnet test fails randomly with codecoverage.

## Diagnostic logs
[Log.txt](https://github.com/microsoft/vstest/files/3617214/Log.txt)

**Comment by mayankbansal018** [comment]
@juanperezADD apologies for getting back so late on this, can you please share a small repro project for this? Also if possible can share log files for testhost process as well?

**Comment by mayankbansal018** [comment]
Closing this, please ping here again, with small repro project if possible, & log files for testhost process
