### ISSUE TITLE
Getting System.IO.IOException: The file exists when running tests in an Azure DevOps Services pipeline

### ISSUE THREAD

**Issue by tomaustin700** [microsoft/vstest#2194]
Hi

## Description
We are getting the following error when running tesks via the vstest task on a self hosted build agent. We have ran the pipeline on other agents and get no issues so it is specific to the machine.

```
Unhandled exception ocurred: System.IO.IOException: The file exists.
```

## Steps to reproduce
We can only duplicate this on one of our self hosted agents. Just running a pipeline with the vstest task produces the error.

## Expected behavior
Vstest should execute correctly.

## Actual behavior
The following error is thrown:

```

DtaExecutionHost version 17.157.29222.1.
Starting TestExecution Model...
##[error]Unhandled exception ocurred: System.IO.IOException: The file exists.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Path.InternalGetTempFileName(Boolean checkHost)
   at System.IO.Abstractions.PathWrapper.GetTempFileName()
   at MS.VS.TestService.VstestConsoleAdapter.VstestConsoleRunContext.CreateRunContext()
   at MS.VS.TestService.VstestConsoleAdapter.VstestConsoleRunContext.get_Instance()
   at Microsoft.VisualStudio.TestService.AgentExecutionHost.LocalTestRunHost.Execute(Boolean debugLogs)
   at Microsoft.VisualStudio.TestService.AgentExecutionHost.Program.Main(String[] args)

Unhandled Exception: System.IO.IOException: The file exists.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Path.InternalGetTempFileName(Boolean checkHost)
   at System.IO.Abstractions.PathWrapper.GetTempFileName()
   at MS.VS.TestService.VstestConsoleAdapter.VstestConsoleRunContext.CreateRunContext()
   at MS.VS.TestService.VstestConsoleAdapter.VstestConsoleRunContext.get_Instance()
   at Microsoft.VisualStudio.TestService.AgentExecutionHost.LocalTestRunHost.Execute(Boolean debugLogs)
   at Microsoft.VisualStudio.TestService.AgentExecutionHost.Program.Main(String[] args)
```

## Diagnostic logs
Will provide via email as they contain private information. 

## Environment
Windows Server 2016 Datacenter 1607, build 14393.3204
Vstest 2.157.3 installed using the vstest installer task

**Comment by tomaustin700** [comment]
I can send you the debug logs if someone let's me know an email address to send them to. Thanks.

**Comment by ShreyasRmsft** [comment]
@tomaustin700 

We use this dotnet api (https://docs.microsoft.com/en-us/dotnet/api/system.io.path.gettempfilename?view=netframework-4.8) to get a temp file name System.IO.Abstractions.PathWrapper.GetTempFileName() and if your temp folder already has all the possible temp file names this method can generate then it throws.

Ideally the task uses the agent temp folder for generating all these temp files, in case you are using an old vsts-agent then it used to use the os.temp-dir where you can run into this issue.

Can you please try updating your agent to the latest version and this issue should go away? Other wise clearing your system temp folder should also work.

**Comment by tomaustin700** [comment]
@ShreyasRmsft Hi! I have updated the agent to 2.158.0 but I'm still getting it. What is the path to the temp directory and I will try clearing it? Thanks.

**Comment by tomaustin700** [comment]
@ShreyasRmsft Clearing down %TEMP% sorted the issue. Seems that GetTempFileName throws IOException where there are more than 65535 files in temp. Thanks for your help.
