### ISSUE TITLE
Calling dotnet test from a shell script fails on Ubuntu server with net core 3

### ISSUE THREAD

**Issue by livarcocc** [microsoft/vstest#2223]
_From @stuartd on Thursday, October 10, 2019 4:08:16 PM_

We have a shell script that runs our .net core 3 integration tests on a Ubuntu server: it was running just fine, but since upgrading to .net core 3 it has stopped working.

It still works on OSX and in WSL using net core 3 (and the equivalent .bat file works on Windows). 

I have reinstalled .net core 3 on the server but to no effect.

There are two problems, which are detailed below:

1. Calling `dotnet test` from a shell script fails with a permissions error in net core 3, but when calling it from the command line it will run - however..
2. Parameters to `dotnet test` are somehow mangled when running from the command line.

## Permissions error

The shell script is just this:

```bash
# this works just fine
git pull

# run the project which gets the repo path, CDs to the test project folder, 
# and runs the tests, passing along any parameters as a test filter
dotnet run --project TestRunner/TestRunner.csproj $@ 

# run the project which analyzes the test results and generates a results page
dotnet run --project TestResultAnalyzer/TestResultAnalyzer/TestResultAnalyzer.csproj 
```

The first issue is a permissions error calling `dotnet test` from the script: this is the diagnostic output of the TestRunner project:

```
Current directory: /home/username/code/codename/src/API/App/App.Tests
Test command:
dotnet test --filter skeleton -l:trx;LogFileName=App_Test_Run_2019-10-10-11-40.trx -r /home/username/code/codename/src/API/TestRuns/App
Starting process
```
And this is the error which occurs when starting the process:

> Unhandled exception. System.ComponentModel.Win32Exception (13): Permission denied
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at TestRunner.Program.Main(String[] args) in /home/username/code/codename/src/Misc/TestRunner/Program.cs:line 77
   
And this is the code:

```cs
process = new Process {
	StartInfo = {
		Arguments = $"test {arguments} -l:trx;LogFileName={testRunName}.trx -r {testResultFolder}",
		FileName = "dotnet",
		UseShellExecute = false
	}
};
                      
var commandDebug = $"{process.StartInfo.FileName} {process.StartInfo.Arguments}";

Console.WriteLine("Test command");
Console.WriteLine(commandDebug);
Console.WriteLine("Starting process");
process.Start(); // boom
```
   
So, my first issue is:

Why is calling `dotnet test` from a shell script resulting in a permissions error, when calling it from the command line does not?

## Test parameter mangling

And that leads to my second issue.

If I run the above from the command line (note we are using NUnit as the test runner)

`dotnet test --filter skeleton -l:trx;LogFileName=App_Test_Run_2019-10-10-11-40.trx -r /home/username/code/codename/src/API/TestRuns/App`

Then the tests run, but I get this error message:

> -r: command not found

As per [the documentation](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-test), `-r` specifies the location of the test output file:
 
> Directory in which to find the binaries to run.
> -r|--results-directory <PATH>

And indeed the file is not put in the right place, it ends out here, instead of in the `TestRuns/App` folder as specified:

> /home/username/code/codename/src/API/App/App.Tests/TestResults/_servername_2019-10-10_11_46_36.trx

And thus the analyzer can't find it, as it's not in the right place.

Now as I said above, this exact same code works in Windows, OSX and WSL and worked on Ubuntu with net core 2.2 - but on the Ubuntu server it Just. Will. Not. Work. with net core 3.

So the second issue is:

Why is this test syntax not working on Ubuntu under net core 3?

Supplementary info:

#### Output of `dotnet --info`

```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /snap/dotnet-sdk/49/sdk/3.0.100/

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  3.0.100 [/snap/dotnet-sdk/49/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0 [/snap/dotnet-sdk/49/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0 [/snap/dotnet-sdk/49/shared/Microsoft.NETCore.App]
```
  
#### Package references in the test project

```xml
<ItemGroup>
  <PackageReference Include="FluentAssertions" Version="5.9.0" />
  <PackageReference Include="JetBrains.DotMemoryUnit" Version="3.0.20171219.105559" />
  <PackageReference Include="nunit" Version="3.12.0" />
  <PackageReference Include="NUnit.ConsoleRunner" Version="3.10.0" />
  <PackageReference Include="NUnit3TestAdapter" Version="3.15.1" />
  <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.3.0" />
</ItemGroup>
```  

### Server culture

The server culture is en-US-POSIX (which hates humans and their puny case-sensitivity, but I digress..)

 

_Copied from original issue: dotnet/cli#12860_

**Comment by nohwnd** [comment]
@stuartd I am trying to reproduce this issue, are you still facing it? I see some inconsistencies in behavior between 2.1 3.0 and 3.1 dotnet sdk in connection to LC_ALL=POSIX, but can't reproduce the exact problem you have. On the other hand I am getting some weird escape sequence printed into my terminal. 


If you are still facing this issue, could you share a simple project that shows the error? I am for example not sure how you are getting the `testRunName` and `testResultFolder`, and that is potetnially important if you are running it from a script because this looks like a double parsing issue. 

Thanks!

**Comment by stuartd** [comment]
I did try it under 3.1 last week and still got the error.

 I'll have a go at setting up a repro, when I can carve out some time.

> I am for example not sure how you are getting the testRunName and testResultFolder

We get them like this:

```
// get local repo path
var process = new Process {
	StartInfo = {
		Arguments = "rev-parse --show-toplevel",
		FileName = "git",
		RedirectStandardOutput = true
	}
};

Console.WriteLine($"Starting git with command line: {process.StartInfo.FileName} {process.StartInfo.Arguments}");

process.Start();

string rootPath = null;
while (!process.StandardOutput.EndOfStream) {
	rootPath = process.StandardOutput.ReadLine();
}

process.WaitForExit();

Console.WriteLine($"Completed git request, using repo path '{rootPath}'");

rootPath = rootPath.Replace("/", @"\");

// This is the folder containing the project we run the tests in
var testDir = Path.Combine(rootPath, @"src\API\Project\Project.Tests");

// This is the folder where we want the test output file to be stored
var testResultFolder = Path.Combine(rootPath, @"src\Misc\TestRuns\Project");

if (!RuntimeInformation.IsOSPlatform(OSPlatform.Windows)) {
	testResultFolder = testResultFolder.Replace(@"\", "/");
	testDir = testDir.Replace(@"\", "/");
}

Console.WriteLine($"Test result folder: {testResultFolder}");

Directory.CreateDirectory(testResultFolder);

Console.WriteLine($"Test folder: {testDir}");

Directory.SetCurrentDirectory(testDir);

Console.WriteLine("Current directory: " + Directory.GetCurrentDirectory());

var testRunName = "Project_Test_Run_" + DateTime.Now.ToString("yyyy-MM-dd-HH-mm");

string arguments = args.Any() 
	? "--filter " + string.Join(" ", args)
	: null;

process = new Process {
	StartInfo = {
		Arguments = $"test {arguments} -l:trx;LogFileName={testRunName}.trx -r {testResultFolder}",
		FileName = "dotnet",
		UseShellExecute = false
	}
};

// and here we get the permissions error.	  
var command = $"{process.StartInfo.FileName} {process.StartInfo.Arguments}";
```

> that is potetnially important if you are running it from a script because this looks like a double parsing issue

However, the second issue above - the error message when running the command generated by the above code directly in the terminal - still happens.

When I run this command:

    dotnet test --filter skeleton -l:trx;LogFileName=Project_Test_Run_2020-02-11-17-05.trx -r /home/sme-graph/code/vendorgraph/src/Misc/TestRuns/Project

This is the final output:

    -r: command not found

.. and the output file is not where it should be.

**Comment by nohwnd** [comment]
@stuartd thanks!

**Comment by nohwnd** [comment]
I am not seeing the access denied issue, nor the parameter mangling. I only see the -r command not found when I run it directly in terminal (see below). 

I tried reproducing this like this, and it works: 
![image](https://user-images.githubusercontent.com/5735905/75171483-f68f0600-572b-11ea-8bed-a9e14c000afc.png)

```bash
n@nuuuub:~/folder$ ./runner.sh 
Microsoft (R) Build Engine version 16.3.2+e481bbf88 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 31.71 ms for /home/n/folder/console1/console1.csproj.
  console1 -> /home/n/folder/console1/bin/Debug/netcoreapp3.0/console1.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.79
Microsoft (R) Build Engine version 16.3.2+e481bbf88 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 19.35 ms for /home/n/folder/src/API/Project/Project.Tests/Project.Tests.csproj.
  Project.Tests -> /home/n/folder/src/API/Project/Project.Tests/bin/Debug/netcoreapp3.0/Project.Tests.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.86
Starting git with command line: git rev-parse --show-toplevel
Completed git request, using repo path '/home/n/folder'
Test result folder: /home/n/folder/src/Misc/TestRuns/Project
Test folder: /home/n/folder/src/API/Project/Project.Tests
Current directory: /home/n/folder/src/API/Project/Project.Tests
Test command
dotnet test  -l:trx;LogFileName=Project_Test_Run_2020-02-24-16-31-19.trx -r /home/n/folder/src/Misc/TestRuns/Project
Starting process
n@nuuuub:~/folder$ Test run for /home/n/folder/src/API/Project/Project.Tests/bin/Debug/netcoreapp3.0/Project.Tests.dll(.NETCoreApp,Version=v3.0)
Microsoft (R) Test Execution Command Line Tool Version 16.3.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

A total of 1 test files matched the specified pattern.
;1RResults File: /home/n/folder/src/Misc/TestRuns/Project/Project_Test_Run_2020-02-24-16-31-19.trx
```
---
```
n@nuuuub:~/folder$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.103
 Commit:    b7ef045669

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /snap/dotnet-sdk/65/sdk/3.0.103/

Host (useful for support):
  Version: 3.0.3
  Commit:  c03f2fe626

.NET Core SDKs installed:
  3.0.103 [/snap/dotnet-sdk/65/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.3 [/snap/dotnet-sdk/65/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.3 [/snap/dotnet-sdk/65/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

---
I can see the `-r` command not found error when I paste the code directly to command line, and it is caused by missing quotes: 
`-l:trx;LogFileName=Project_Test_Run_2020-02-11-17-05.trx -r <- incorrect ` 
`-l:"trx;LogFileName=Project_Test_Run_2020-02-11-17-05.trx" -r <- correct`

You are basically terminating the first command on the `;`, then defining an environment variable for the next command `-r` which does not exist, and so bash reports the error.

[folder.zip](https://github.com/microsoft/vstest/files/4245622/folder.zip)

**Comment by moh-hassan** [comment]
I faced  such a problem in .Net Core 3.1 when copying script from windows to Ubuntu.
The script contain commands with parameters.
```
dotnet myapp.dll --param1 --param2
```
If I run the commands from the terminal it is working fine, but fail from the script file.

The root problem was that every line was ended with **CRLF** characters.
I used dos2unix to convert the file to unix format and now  it is working fine.

```
sudo apt-get install dos2unix
dos2unix run.sh
./run.sh    # now it's ok
```

**Comment by stuartd** [comment]
@nohwnd thank you very much and @moh-hassan that's very interesting. I had a niggling thought at the back of my mind about line terminators, but never looked at it properly.

I've been very busy (as are we all, of course) but I will look into these as soon as I can.

**Comment by nohwnd** [comment]
@stuartd gentle ping, if you'd find a moment to try this out 🙂

**Comment by nohwnd** [comment]
@stuartd Closing this due to no activity, the issue with `;` should be a syntax issue. Let us know if you need more assistance.
