### ISSUE TITLE
System.NullReferenceException if InProcess collector doesn't subscribe to TestCaseStart/TestCaseEnd

### ISSUE THREAD

**Issue by MarcoRossignoli** [microsoft/vstest#2289]
If an InProcess collector doesn't subscribe to TestCaseStart or TestCaseEnd connection between datacollector process and host is not setup(`--datacollectionport 0`)

https://github.com/microsoft/vstest/blob/7b6248203164f8ea821f6795632bd22e0b69afb0/src/Microsoft.TestPlatform.Common/DataCollection/TestPlatformDataCollectionEvents.cs#L96

This lead to null ref exception when we try to read from network stream on host side 

https://github.com/microsoft/vstest/blob/7b6248203164f8ea821f6795632bd22e0b69afb0/src/Microsoft.TestPlatform.CommunicationUtilities/DataCollectionTestCaseEventSender.cs#L90-L94

ends to

https://github.com/microsoft/vstest/blob/031cd319cdbcb3ea770e4fb832e7b2b1a67d32dd/src/Microsoft.TestPlatform.CommunicationUtilities/SocketCommunicationManager.cs#L320

but `binaryReader` is null

```
TpTrace Error: 0 : 4716, 13, 2020/01/04, 15:33:28.899, 5909922957355, testhost.dll, TestCaseEventsHandler.RaiseTestCaseStart: Exception occurred while calling handler of type Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.DataCollection.ProxyOutOfProcDataCollectionManager for TestCaseStartEventArgs: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.SocketCommunicationManager.ReceiveRawMessage()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.SocketCommunicationManager.ReceiveMessage()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.DataCollectionTestCaseEventSender.SendTestCaseStart(TestCaseStartEventArgs e)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.DataCollection.ProxyOutOfProcDataCollectionManager.TriggerTestCaseStart(Object sender, TestCaseStartEventArgs e)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at Microsoft.VisualStudio.TestPlatform.Utilities.MulticastDelegateUtilities.SafeInvoke(Delegate delegates, Object sender, EventArgs args, String traceDisplayName)
```

Write side doesn't have problem because is correctly null handled 

https://github.com/microsoft/vstest/blob/031cd319cdbcb3ea770e4fb832e7b2b1a67d32dd/src/Microsoft.TestPlatform.CommunicationUtilities/SocketCommunicationManager.cs#L406

cc: @vagisha-nidhi @AbhitejJohn @singhsarab

**Comment by MarcoRossignoli** [comment]
I've got a PR ready, assign to me if you want.
