### ISSUE TITLE
NullReference exception while publishing test results

### ISSUE THREAD

**Issue by uandrei** [microsoft/vstest#2366]
## Steps to reproduce
This doesn't happen all the time, it's on and off, although recently it seems to be happening more often than before. Our CI pipeline in DevOps fails at the test stage. The test run is successful and when test results are published the vstest app crashes with a null reference exception.

Captured diagnostics and full debug log from the Azure DevOps console and attached to this email alongside the output trx.

Considering the fact that is not always failing i'm just wondering if it's a timing issue whereby the trx is not yet flushed to the disk before it tries to read it?

Error stack trace

Error occurred while publishing test results : System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
    at Microsoft.TeamFoundation.TestClient.PublishTestResults.TrxResultParser.<>c__DisplayClass16_0.<ReadActualResults>b__1(String xunitParentNodeKey)
    at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
    at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
    at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
    --- End of inner exception stack trace ---
    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
    at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
    at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
    at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body)
    at Microsoft.TeamFoundation.TestClient.PublishTestResults.TrxResultParser.ReadActualResults(XmlNodeList resultsNodes, TestType testType, Dictionary`2 xUnitTestCaseCounts)
    at Microsoft.TeamFoundation.TestClient.PublishTestResults.TrxResultParser.ParseTestResultFile(TestRunContext runContext, String filePath)
    at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
    at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
    at Microsoft.TeamFoundation.TestClient.PublishTestResults.TrxResultParser.ParseTestResultFiles(TestRunContext runContext, IList`1 resultFilePaths)
    at Microsoft.VisualStudio.TestService.TcmTestResultPublisher.TrxTestResultPublisher.ParseTrx(TestRunContext testRunContext, IList`1 trxFilePaths)
    at Microsoft.VisualStudio.TestService.TcmTestResultPublisher.TrxTestResultPublisher.PublishTestRunResults(TestRunModel testRunModel)
    at MS.VS.TestService.VstestConsoleAdapter.PublishTestResult.CreateOrUpdateTestRun(TestRunModel testRunModel)
    at MS.VS.TestService.VstestConsoleAdapter.PublishTestResult.Publish(VstestConsoleRunContext testRunContext)
    ---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
    at Microsoft.TeamFoundation.TestClient.PublishTestResults.TrxResultParser.<>c__DisplayClass16_0.<ReadActualResults>b__1(String xunitParentNodeKey)
    at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
    at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
    at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---

## Attachments
[github-issue.zip](https://github.com/microsoft/vstest/files/4355112/github-issue.zip)
[logs.txt](https://github.com/microsoft/vstest/files/4355113/logs.txt)

> Operating system, Build version of vstest.console
OS: Windows (Windows Server 2016 Datacenter)
VSTest: 16.5.0

**Comment by nohwnd** [comment]
The trx logger can skip the whole Results section or parts of it when it encounters an error. So maybe this is related because it fails in TrxResultParser? 

Possibly related: https://github.com/microsoft/vstest/issues/2319

**Comment by uandrei** [comment]
our test runs don't have any errors, that's the weird part of it. tests are written in xunit

**Comment by nohwnd** [comment]
When I said error I meant internal framework error. Are you able to grab the trx file? Does it have <Results> node and that has the correct amount of tests? it is possibly missing as a whole or missing some tests. I've seen both problems happen.

**Comment by uandrei** [comment]
i've attached the trx and the diagnostics. can grab it from there

**Comment by uandrei** [comment]
Not an expert in trx files, but the one i've attached to this bug looks OK. Like i said this failure is not consistent so if i compare this TRX with another one from a successful run they look similar.

Again, this started happening in the last couple of weeks

**Comment by ocdi** [comment]
I'm seeing this too on CI - re-running the job with exactly the same code usually fixes it, however it is a pain when the build takes 10 minutes and you have many PRs that need to be built.

**Comment by uandrei** [comment]
Just an update...tried moving back to 16.4.0 and it seems to be better, so it feels like this issue is tied to 16.5.0 version of the test platform.

**Comment by mihaipanait** [comment]
I can confirm we had the same issue today. All tests were green but the job failed with 'Error occurred while publishing test results : System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.  at Microsoft.TeamFoundation.TestClient.PublishTestResults.TrxResultParser.<>c__DisplayClass16_0.<ReadActualResults>b__1(String xunitParentNodeKey)'

It eventually went through after three retries.

**Comment by aurnoi1** [comment]
Same problem as described since 27th of March.

VSTest: 1.16.5
Images: windows-2019
**TestFramework: xUnit**

**Comment by gavinjensen** [comment]
My team has experienced this problem as well running 16.5.0.  I see it was added to the 16.7.0 milestone.  Does that mean is this going to be fixed in that build?

**Comment by menoret-allan** [comment]
On our projectwe had the same issue, the downgrade from 16.5.0 to the 16.4.0 mention by @uandrei works :)

**Comment by nohwnd** [comment]
@gavinjensen  that would be a question for @cvpoienaru to answer, because he is assigned here, but yes we expect this to be addressed in 16.7.0.

**Comment by ShreyasRmsft** [comment]
This is an issue with the Publish Test results task, it has already been fixed with the latest version of the vstest task
