### ISSUE TITLE
vstest deletes the deployment directory while it is in use when using /parallel

### ISSUE THREAD

**Issue by michael-baker** [microsoft/vstest#2372]
## Steps to reproduce
- Two test assemblies both containing [DeploymentItem]
- Execute test assemblies in parallel with the `/parallel` switch
- A race condition means MSTest can delete the deployment directory used by another test execution 

> What steps can reproduce the defect?
- Both test assemblies targeting .NET 4.8

```
"C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" /Logger:trx /Platform:x64  /Parallel C:\B\1004\2\s\Libraries.Roles\Bin\Test\UnitTest.DeploymentManifestValidation.dll C:\B\1004\2\s\Libraries.Roles\Bin\Test\UnitTest.Roles.dll /Settings:C:\Users\michael.baker\desktop\testsettings.txt /diag:log.txt
```

Test settings file
```
<?xml version="1.0" encoding="utf-8"?>
<RunSettings>
  <RunConfiguration>
    <MaxCpuCount>4</MaxCpuCount>
    <TestSessionTimeout>1200000</TestSessionTimeout>
  </RunConfiguration>
  <!-- MSTest adapter -->
  <MSTest>
    <MapInconclusiveToFailed>True</MapInconclusiveToFailed>
    <CaptureTraceOutput>true</CaptureTraceOutput>
    <DeleteDeploymentDirectoryAfterTestRunIsComplete>true</DeleteDeploymentDirectoryAfterTestRunIsComplete>
    <DeploymentEnabled>true</DeploymentEnabled>
   
  </MSTest>
</RunSettings>
```

Occasionally a test run will explode with a ```FileNotFoundException``` as one of the assemblies completes and then ```TestHost.exe``` proceeds to delete the DeploymentDirectory that is being used by the other second ```TestHost.exe```

```
UnitTest.Roles.RoleUnitTests.RoleTest failed. ErrorMessage:Unable to get type UnitTest.Roles.RoleUnitTests. Error: System.IO.FileNotFoundException: Could not load file or assembly 'file:///C:\users\michael.baker\Desktop\TestResults\Deploy_michael.baker 2020-03-25 16_06_26\Out\UnitTest.Roles.dll' or one of its dependencies. The system cannot find the file specified.
File name: 'file:///C:\users\michael.baker\Desktop\TestResults\Deploy_michael.baker 2020-03-25 16_06_26\Out\UnitTest.Roles.dll'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Microsoft.VisualStudio.TestPlatform.MSTestFramework.TypeCache.LoadType(String typeName, String assemblyName)

Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
Running under executable  C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\Extensions\TestPlatform\testhost.exe
```

## Expected behavior
```/parallel``` is not subject to race conditions.

## Actual behavior
```/parallel``` is subject to race conditions.

## Diagnostic logs
Logs from the two ```TestHost.exe``` instances.

[1.host.20-03-25_16-06-25_36815_7.txt](https://github.com/microsoft/vstest/files/4378848/1.host.20-03-25_16-06-25_36815_7.txt)
[1.host.20-03-25_16-06-25_38380_8.txt](https://github.com/microsoft/vstest/files/4378849/1.host.20-03-25_16-06-25_38380_8.txt)

Snippet from log file ```7```
```
TpTrace Information: 0 : 7156, 14, 2020/03/25, 16:06:27.261, 203948524928, testhost.exe, Executed tests belonging to source C:\users\michael.baker\Desktop\TestResults\Deploy_michael.baker 2020-03-25 16_06_26\Out\UnitTest.DeploymentManifestValidation.dll
TpTrace Information: 0 : 7156, 14, 2020/03/25, 16:06:27.261, 203948528082, testhost.exe, Deleting deployment directory C:\users\michael.baker\Desktop\TestResults\Deploy_michael.baker 2020-03-25 16_06_26
TpTrace Error: 0 : 7156, 14, 2020/03/25, 16:06:27.276, 203948580688, testhost.exe, DeploymentManager.DeleteDirectories failed for the directory 'C:\users\michael.baker\Desktop\TestResults\Deploy_michael.baker 2020-03-25 16_06_26': System.IO.IOException: The process cannot access the file 'C:\users\michael.baker\Desktop\TestResults\Deploy_michael.baker 2020-03-25 16_06_26\Out' because it is being used by another process.
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at Microsoft.VisualStudio.TestPlatform.MSTestFramework.DeploymentManager.DeleteDirectories(String filePath)
TpTrace Information: 0 : 7156, 14, 2020/03/25, 16:06:27.276, 203948580894, testhost.exe, Deleted deployment directory C:\users\michael.baker\Desktop\TestResults\Deploy_michael.baker 2020-03-25 16_06_26
```

Snippet from log file ```8```

```
TpTrace Verbose: 0 : 6156, 14, 2020/03/25, 16:06:27.589, 203949630606, testhost.exe, MSTestExecutor:Test UnitTest.Roles.RoleUnitTests.RoleTest failed. ErrorMessage:Unable to get type UnitTest.Roles.RoleUnitTests. Error: System.IO.FileNotFoundException: Could not load file or assembly 'file:///C:\users\michael.baker\Desktop\TestResults\Deploy_michael.baker 2020-03-25 16_06_26\Out\UnitTest.Roles.dll' or one of its dependencies. The system cannot find the file specified.
File name: 'file:///C:\users\michael.baker\Desktop\TestResults\Deploy_michael.baker 2020-03-25 16_06_26\Out\UnitTest.Roles.dll'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
```

Comparing these files you can see log file ```7``` initiates a directory delete at 16:06:27.261 while it is being used at 16:06:27.589.

## Environment
> Please share additional details about the test environment.

- Windows Server 2016 1607
- Test Execution Command Line Tool Version 15.9.1

I can side step the issue by setting ```DeleteDeploymentDirectoryAfterTestRunIsComplete``` to false but then my CI servers fill up with hundreds of GB of assets pretty quickly. 

FYI in the issue template 'reproducible' is spelled incorrectly  as 'reproducable'.

**Comment by nohwnd** [comment]
Thanks for reporting, will try to get back to this soon.

**Comment by michael-baker** [comment]
My assumption is you should get a separate ```Out``` directory per test process to avoid race conditions. This would mean repeating deployments which has a performance cost but I don't see a way to make the test run stable without doing this. 
If the intent is to create separate directories per assembly then the problem could be in ```GetRootDeploymentDirectory``` as it does not use something stable like the PID for the directory name. 

Otherwise perhaps a synchronized clean up is needed?

**Comment by nohwnd** [comment]
This change would impact how deployments work and we don't know what would break.
