### ISSUE TITLE
Not able to run vstest.console.exe with custom logger

### ISSUE THREAD

**Issue by steaad** [microsoft/vstest#2444]
I have used a custom logger when running vstest.console.exe. This was working for v16.5.0 of the Microsoft.TesFramework. But now after I upgraded to v16.6.1 this now fails. Previously it worked to place the custom logger .dll file inside the "Extensions" folder. Then it was possible to use the logger by attribute /logger:customLoggerFriendlyName. Now I get the message <_Could not find a test logger with AssemblyQualifiedName, URI or FriendlyName 'MsTestTrxLogger'_>. What has changed in the latest version of the testframework?

## Steps to reproduce
I copy the customLogger .dll to the extensions folder of the testframework. Then I simply just open the command line and run vstest.console.exe testProject.dll /logger:customLoggerFriendlyName

## Expected behavior
Would expect the framework to accept my custom logger and generate the trx file.

## Actual behavior
Get an message in command saying <_Could not find a test logger with AssemblyQualifiedName, URI or FriendlyName 'MsTestTrxLogger'_>. According to the log it look like the framework thinks the custom dll could be harmful. It does not allow external dll to be added. The framework tries to load the dll through reflection but it fails. (see log)

## Diagnostic logs
[log.txt](https://github.com/microsoft/vstest/files/4671275/log.txt)

## Environment
NET451, vstest.console.exe says assembly file v 15.0.0.0 (product v 16.6.1)

**Comment by nohwnd** [comment]
This is what I see in the log, the file is downloaded but not unblocked:
```
TpTrace Information: 0 : 15436, 1, 2020/05/23, 08:19:04.329, 3678491755630, vstest.console.exe, AssemblyResolver.OnResolve: MsTestTrxLogger: Resolving assembly.
TpTrace Information: 0 : 15436, 1, 2020/05/23, 08:19:04.347, 3678491936874, vstest.console.exe, AssemblyResolver.OnResolve: MsTestTrxLogger: Failed to load assembly. Reason:System.IO.FileLoadException: Could not load file or assembly 'file:///C:\Users\aadneviks\.nuget\packages\microsoft.testplatform.portable\16.5.0\tools\net451\Extensions\MsTestTrxLogger.dll' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
File name: 'file:///C:\Users\aadneviks\.nuget\packages\microsoft.testplatform.portable\16.5.0\tools\net451\Extensions\MsTestTrxLogger.dll' ---> System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Microsoft.VisualStudio.TestPlatform.PlatformAbstractions.PlatformAssemblyLoadContext.LoadAssemblyFromPath(String assemblyPath)
   at Microsoft.VisualStudio.TestPlatform.Common.Utilities.AssemblyResolver.OnResolve(Object sender, AssemblyResolveEventArgs args)

 
TpTrace Warning: 0 : 15436, 1, 2020/05/23, 08:19:04.348, 3678491949015, vstest.console.exe, TestPluginDiscoverer-FileLoadException: Failed to load extensions from file 'C:\Users\aadneviks\.nuget\packages\microsoft.testplatform.portable\16.5.0\tools\net451\Extensions\MsTestTrxLogger.dll'.  Skipping test extension scan for this file.  Error: System.IO.FileLoadException: Could not load file or assembly 'MsTestTrxLogger' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
File name: 'MsTestTrxLogger' ---> System.IO.FileLoadException: Could not load file or assembly 'file:///C:\Users\aadneviks\.nuget\packages\microsoft.testplatform.portable\16.5.0\tools\net451\Extensions\MsTestTrxLogger.dll' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
```

**Comment by Evangelink** [comment]
@steaad can you try to unblock the dll as recommended by @nohwnd ?
