### ISSUE TITLE
Blame Collector attachment not found in test results. So it is not a test case abort issue. It's abort from test platform, might be during app domain tear down.

### ISSUE THREAD

**Issue by EnriGrossi** [microsoft/vstest#2562]
I get this message while running tests in azure devops build pipeline.
I have already tried without useful results to add this parameter to the runsettings:
`<DisableAppDomain>true</DisableAppDomain>`

In the event viewer i've this message:
Application: testhost.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0000005, exception address 00007FF9BD1C2922
Stack:
   at Microsoft.VisualStudio.TestTools.CppUnitTestFramework.TestEngine.IExecutor.RunTestCase(Microsoft.VisualStudio.TestTools.CppUnitTestFramework.TestEngine.ITestCase2, Microsoft.VisualStudio.TestTools.CppUnitTestFramework.ComInterfaces.IRunSettings, Microsoft.VisualStudio.TestTools.CppUnitTestFramework.ComInterfaces.ITestLog, Microsoft.VisualStudio.TestTools.CppUnitTestFramework.ComInterfaces.ITestResult)
   at Microsoft.VisualStudio.TestTools.CppUnitTestFramework.TestEngine.IExecutor.RunTestCase(Microsoft.VisualStudio.TestTools.CppUnitTestFramework.TestEngine.ITestCase2, Microsoft.VisualStudio.TestTools.CppUnitTestFramework.ComInterfaces.IRunSettings, Microsoft.VisualStudio.TestTools.CppUnitTestFramework.ComInterfaces.ITestLog, Microsoft.VisualStudio.TestTools.CppUnitTestFramework.ComInterfaces.ITestResult)
   at Microsoft.VisualStudio.TestTools.CppUnitTestFramework.TestEngine.CppTestEngine.RunTestCases(Microsoft.VisualStudio.TestTools.CppUnitTestFramework.ComInterfaces.ITestCaseEnumerator, Microsoft.VisualStudio.TestTools.CppUnitTestFramework.ComInterfaces.IRunSettings, Microsoft.VisualStudio.TestTools.CppUnitTestFramework.ComInterfaces.ITestLog)
   at Microsoft.VisualStudio.TestTools.CppUnitTestFramework.CppUnitTestExtension.TestExecutor.RunTests(System.Collections.Generic.IEnumerable`1<Microsoft.VisualStudio.TestPlatform.ObjectModel.TestCase>, Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.IRunContext, Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.IFrameworkHandle)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.RunTestsWithTests.InvokeExecutor(Microsoft.VisualStudio.TestPlatform.Common.ExtensionFramework.Utilities.LazyExtension`2<Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.ITestExecutor,Microsoft.VisualStudio.TestPlatform.Common.Interfaces.ITestExecutorCapabilities>, System.Tuple`2<System.Uri,System.String>, Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Adapter.RunContext, Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.IFrameworkHandle)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.BaseRunTests+<>c__DisplayClass48_0.<RunTestInternalWithExecutors>b__0()
   at Microsoft.VisualStudio.TestPlatform.PlatformAbstractions.PlatformThread+<>c__DisplayClass0_0.<Run>b__0()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

I'm using Microsoft.TestPlatform 
TestPlatformVersion: 16.7.1

Tyvm

Enri

**Comment by nohwnd** [comment]
These might be related. https://github.com/microsoft/vstest/search?q=0xc0000005&type=Issues Same access violation exception, but it might mean anything.

**Comment by EnriGrossi** [comment]
We no longer have those tests unfortunately. From my experience there could be some crasjh in the setup (and therefore not during the execution of a specific test).

Thank you

Enri

**Comment by Evangelink** [comment]
@EnriGrossi Thank you for the prompt reply. We will close this issue, feel free to reopen one if you are experiencing any other issue.
