### ISSUE TITLE
vstest hides problems when runtime libraries are broken

### ISSUE THREAD

**Issue by marek-safar** [microsoft/vstest#2614]
When vstest is used on dotnet/runtime and underlying implementation has broken networking implementation vstest fails with no details about the problem.

The error message issued is

```
Failed to negotiate protocol, waiting for response timed out after 90 seconds. This may occur due to machine slowness, please set environment variable VSTEST_CONNECTION_TIMEOUT to increase timeout.
Test Run Aborted.
```

The only detail in the verbose log is

```
TpTrace Error: 0 : 70249, 4, 2020/11/03, 14:16:15.080, 1591259884333184, vstest.console.dll, ProxyExecutionManager.StartTestRun: Failed to start test run: Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Failed to negotiate protocol, waiting for response timed out after 90 seconds. This may occur due to machine slowness, please set environment variable VSTEST_CONNECTION_TIMEOUT to increase timeout.
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.TestRequestSender.CheckVersionWithTestHost()
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, String runSettings)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyExecutionManager.StartTestRun(TestRunCriteria testRunCriteria, ITestRunEventsHandler eventHandler)
```

@jkotas

**Comment by jkotas** [comment]
cc @ViktorHofer

**Comment by ViktorHofer** [comment]
thanks for the ping. Marek and I talked about this offline and I asked him to file the issue. cc @nohwnd

**Comment by nohwnd** [comment]
If connection dies immediately, it incorrectly reports timeout, there is some bug in event completion which triggers the timeout message, rather than reporting the actual exception.

**Comment by nohwnd** [comment]
We assume that the networking works in vstest, for more flexible solution that can be made to run without network stack please go see Testing.Platform instead. https://aka.ms/testingplatform
