### ISSUE TITLE
VSTest with coverlet collector fails

### ISSUE THREAD

**Issue by arabelaa** [microsoft/vstest#2637]
## Description
I have a .NETCore 3.1 test project with  `"Microsoft.NET.Test.Sdk" 16.7.1` of and `"coverlet.collector" 1.3.0`.

I am getting an exception when running tests using VSTest - Version 16.7.0 (I can't switch to dotnet test approach, unfortunatly - there is a strong requirement to stick to vstest)

## Steps to reproduce
`vstest.console.exe --collect:"XPlat Code Coverage"  C:\Projects\test\Web.Tests\bin\Debug\Web.Tests.dll /TestAdapterPath:C:\.nuget\packages\coverlet.collector\1.3.0\build --Diag:"C:\Projects\diag.txt"`

## Actual behavior
I get the following warning in the console:
```
Data collection : Unable to find a datacollector with friendly name 'XPlat code coverage'.
Data collection : Could not find data collector 'XPlat code coverage'
```

## Diagnostic logs
And in diag.txt file I see:
```

datacollector.exe, TestPluginDiscoverer: Failed to get types from assembly 'coverlet.collector, Version=1.3.0.0, Culture=neutral, PublicKeyToken=4beb1ad7f05a1c71'.  Skipping test extension scan for this assembly.  Error: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at Microsoft.VisualStudio.TestPlatform.Common.ExtensionFramework.TestPluginDiscoverer.GetTestExtensionsFromAssembly[TPluginInfo,TExtension](Assembly assembly, Dictionary`2 pluginInfos)
TpTrace Warning: 0 : 60664, 1, 2020/11/14, 22:42:00.029, 8944115731653, datacollector.exe, LoaderExceptions: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Runtime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Runtime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
```

I followed the discussion mentioned on https://github.com/microsoft/vstest/issues/2278 but it seems like a separate issue. 
Am I am missing a configuration?

I can't figure out the source of the problem. Any help is highly appreciated. Thanks in advance.

Initially I opened an issue on coverlet repo but I think it's a VSTest issue.

**Comment by arabelaa** [comment]
Based on the answer I received on https://github.com/microsoft/vstest/issues/2278 I will close the issue.
