### ISSUE TITLE
No coverage available for IIS processes 

### ISSUE THREAD

**Issue by arabelaa** [microsoft/vstest#2639]
## Description
I have a .NETCore 3.1 test project with  `Microsoft.NET.Test.Sdk 16.7.1` that is used Azure pipeline. 
The agent has Visual Studio 2017 VSTest. 

I am getting an exception when running tests using VSTest on the agent machine. We are interested in the coverage of integration tests - we have an API that is hosted in IIS -  hence the configurations `<CollectAspDotNet>True</CollectAspDotNet>						<CollectFromChildProcesses>True</CollectFromChildProcesses>
`

## Steps to reproduce
`.\vstest.console.exe  /Settings:C:\Projects\CodeCoverage.runsettings  C:\Projects\test\Web.Tests\bin\Debug\Web.Tests.dll --Diag:"C:\Projects\diag.txt" `

CodeCoverage.runsettings has the following settings (I've excluded the ModulePaths and Attributes for simplicity).
```

<?xml version="1.0" encoding="utf-8"?>
<!-- File name extension must be .runsettings -->
<RunSettings>
	<DataCollectionRunSettings>
		<DataCollectors>
			<DataCollector friendlyName="Code Coverage" uri="datacollector://Microsoft/CodeCoverage/2.0" assemblyQualifiedName="Microsoft.VisualStudio.Coverage.DynamicCoverageDataCollector, Microsoft.VisualStudio.TraceCollector, Version=11.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a">
				<Configuration>
					<CodeCoverage>
						<UseVerifiableInstrumentation>True</UseVerifiableInstrumentation>
						<AllowLowIntegrityProcesses>True</AllowLowIntegrityProcesses>
						<CollectFromChildProcesses>True</CollectFromChildProcesses>
						<CollectAspDotNet>True</CollectAspDotNet>
					</CodeCoverage>
				</Configuration>
			</DataCollector>
		</DataCollectors>
	</DataCollectionRunSettings>
</RunSettings>

```

## Actual behavior
I get the following errors in the diag.txt file:
```
TpTrace Warning: 0 : 7512, 1, 2020/11/17, 20:30:45.661, 34619433276, datacollector.exe, LoaderExceptions: System.IO.FileNotFoundException: Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=4.0.4.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Diagnostics.DiagnosticSource, Version=4.0.4.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Microsoft.VisualStudio.TestPlatform.Common.ExtensionFramework.TestPluginCache.CurrentDomainAssemblyResolve(Object sender, AssemblyResolveEventArgs args)
   at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)
TpTrace Error: 0 : 7512, 1, 2020/11/17, 20:30:45.679, 34619622522, datacollector.exe, The type "Microsoft.VisualStudio.Coverage.DynamicCoverageDataCollector" defined in "Microsoft.VisualStudio.TraceDataCollector.dll" does not have ExtensionUri attribute.
TpTrace Error: 0 : 7512, 1, 2020/11/17, 20:30:45.679, 34619623428, datacollector.exe, The type "Microsoft.VisualStudio.TraceCollector.TestImpactDataCollector" defined in "Microsoft.VisualStudio.TraceDataCollector.dll" does not have ExtensionUri attribute.
TpTrace Error: 0 : 7512, 1, 2020/11/17, 20:30:45.679, 34619623985, datacollector.exe, The type "Microsoft.VisualStudio.TraceCollector.UnitTestIsolationDataCollector" defined in "Microsoft.VisualStudio.TraceDataCollector.dll" does not have ExtensionUri attribute.

TpTrace Information: 0 : 7512, 8, 2020/11/17, 20:30:52.299, 34685811591, datacollector.exe, ProcessDumpUtility.OutputReceivedCallback: Output received from procdump process: [20:30:52] Exception: E06D7363.PEAVEEFileLoadException@@
TpTrace Information: 0 : 7512, 8, 2020/11/17, 20:30:52.299, 34685813461, datacollector.exe, ProcessDumpUtility.OutputReceivedCallback: Output received from procdump process: [20:30:52] Exception: E0434352.CLR
TpTrace Information: 0 : 7512, 8, 2020/11/17, 20:30:52.346, 34686284067, datacollector.exe, ProcessDumpUtility.OutputReceivedCallback: Output received from procdump process: [20:30:52] Exception: E0434352.CLR
TpTrace Information: 0 : 7512, 8, 2020/11/17, 20:30:52.398, 34686802478, datacollector.exe, ProcessDumpUtility.OutputReceivedCallback: Output received from procdump process: [20:30:52] Exception: E0434352.CLR
TpTrace Information: 0 : 7512, 8, 2020/11/17, 20:30:52.406, 34686884977, datacollector.exe, ProcessDumpUtility.OutputReceivedCallback: Output received from procdump process: [20:30:52] Exception: E0434352.CLR
TpTrace Information: 0 : 7512, 8, 2020/11/17, 20:30:52.415, 34686974730, datacollector.exe, ProcessDumpUtility.OutputReceivedCallback: Output received from procdump process: [20:30:52] Exception: E0434352.CLR
TpTrace Information: 0 : 7512, 8, 2020/11/17, 20:30:52.426, 34687079765, datacollector.exe, ProcessDumpUtility.OutputReceivedCallback: Output received from procdump process: [20:30:52] Exception: E0434352.CLR
TpTrace Information: 0 : 7512, 8, 2020/11/17, 20:30:52.427, 34687093954, datacollector.exe, ProcessDumpUtility.OutputReceivedCallback: Output received from procdump process: [20:30:52] Exception: E0434352.CLR
TpTrace Information: 0 : 7512, 8, 2020/11/17, 20:30:52.522, 34688041155, datacollector.exe, ProcessDumpUtility.OutputReceivedCallback: Output received from procdump process: [20:30:52] Exception: E0434352.CLR
TpTrace Information: 0 : 7512, 8, 2020/11/17, 20:30:52.619, 34689022850, datacollector.exe, ProcessDumpUtility.OutputReceivedCallback: Output received from procdump process: [20:30:52] Exception: E0434352.CLR
TpTrace Information: 0 : 7512, 8, 2020/11/17, 20:30:53.100, 34693817524, datacollector.exe, ProcessDumpUtility.OutputReceivedCallback: Output received from procdump process: [20:30:53] Exception: E0434352.CLR
TpTrace Information: 0 : 7512, 6, 2020/11/17, 20:30:54.397, 34706787681, datacollector.exe, DataCollectionTestCaseEventHandler: Test case starting.
TpTrace Information: 0 : 7512, 6, 2020/11/17, 20:30:54.438, 34707204361, datacollector.exe, Blame Collector : Test Case Start
TpTrace Information: 0 : 7512, 6, 2020/11/17, 20:30:54.439, 34707212443, datacollector.exe, DataCollectionTestCaseEventHandler: Test case started.
TpTrace Information: 0 : 7512, 8, 2020/11/17, 20:31:29.696, 35059782708, datacollector.exe, ProcessDumpUtility.OutputReceivedCallback: Output received from procdump process: [20:31:29] Exception: E0434352.CLR
TpTrace Information: 0 : 7512, 8, 2020/11/17, 20:31:29.818, 35061008919, datacollector.exe, ProcessDumpUtility.OutputReceivedCallback: Output received from procdump process: [20:31:29] Exception: E0434352.CLR
TpTrace Information: 0 : 7512, 8, 2020/11/17, 20:31:29.821, 35061028796, datacollector.exe, ProcessDumpUtility.OutputReceivedCallback: Output received from procdump process: [20:31:29] Exception: E0434352.CLR
TpTrace Information: 0 : 7512, 6, 2020/11/17, 20:31:37.168, 35134496826, datacollector.exe, DataCollectionTestCaseEventHandler : Test case completing.
TpTrace Information: 0 : 7512, 6, 2020/11/17, 20:31:37.172, 35134542686, datacollector.exe, Blame Collector : Test Case End
TpTrace Error: 0 : 7512, 6, 2020/11/17, 20:31:42.871, 35191528558, datacollector.exe, DataCollectionAttachmentManager.GetAttachments: Fail to get attachments: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft.VisualStudio.TestPlatform.Common.DataCollector.DataCollectionAttachmentManager.GetAttachments(DataCollectionContext dataCollectionContext) 

```
An empty coverage file is generated. 

Not sure where to look next, so any help is appreciated.
Thanks.

**Comment by arabelaa** [comment]
After some further investigations I noticed that I can collect coverage if I run manually the powershell commands. 

Before test run: `CodeCoverage.exe collect /IIS /session:WebTests /output:webtests.coverage  ` .The output shows that the IIS process is restarted and that all the dll are instrumented properly. 

After test run: `CodeCoverage.exe shutdown /session:WebTests `

I didn't see any documentation if this is necessary or not. I thought that `CollectAspDotNet` restarts the IIS process and instruments the code but I looked over the https://github.com/microsoft/vstest/blob/2d58f0c2d69a99414e52b114d422559bbb9caa58/src/DataCollectors/TraceDataCollector/VanguardCollector/Vanguard.cs and I didn't see how the IIS parameter is passed to CodeCoverage tool.

**Comment by arabelaa** [comment]
It seems this approach is not working. My app - which is a .NET Core 3.1 app - (hosted in IIS) fails to load because of the following error
```

Application '/LM/W3SVC/2/ROOT' with physical root 'C:\_temp\' hit unexpected managed exception, exception code = '0xe0434352'. First 30KB characters of captured stdout and stderr logs:
Unhandled exception. System.MissingMethodException: Method not found: 'Void Microsoft.VisualStudio.CodeCoverage.Shim.4001414003__coverage_runtime_method__33525_18195__(UInt64)'.
we\_work\1\s\src\Web\Web.Host\Startup\Program.cs:line 52
   at Web.Startup.Program.Main(String[] args) in C:\or-bld-ag-5bf15a79-we\_work\1\s\src\Web\Web.Host\Startup\Program.cs:line 24
   at Web.Startup.Program.<Main>(String[] args)
```

In the output of test project I have the `Microsoft.VisualStudio.CodeCoverage.Shim.dll.` 
To be honest I don't know where to look next. 

Any hint is highly appreciated.

**Comment by jakubch1** [comment]
Please try using unverifiable probes. More info: https://github.com/microsoft/vstest/issues/2459#issuecomment-768254976

**Comment by fhnaseer** [comment]
> After some further investigations I noticed that I can collect coverage if I run manually the powershell commands.
> 
> Before test run: `CodeCoverage.exe collect /IIS /session:WebTests /output:webtests.coverage ` .The output shows that the IIS process is restarted and that all the dll are instrumented properly.
> 
> After test run: `CodeCoverage.exe shutdown /session:WebTests `
> 
> I didn't see any documentation if this is necessary or not. I thought that `CollectAspDotNet` restarts the IIS process and instruments the code but I looked over the https://github.com/microsoft/vstest/blob/2d58f0c2d69a99414e52b114d422559bbb9caa58/src/DataCollectors/TraceDataCollector/VanguardCollector/Vanguard.cs and I didn't see how the IIS parameter is passed to CodeCoverage tool.

@arabelaa Can you try running vstest.console.exe with admin rights? Or Visual Studio with admin rights? And see if you need to do this additional step or not.
