### ISSUE TITLE
Coverlet support SDK version 2.2.207

### ISSUE THREAD

**Issue by MarcoRossignoli** [microsoft/vstest#2737]
## Description
Coverlet should be supported since SDK version `2.2.300` that was released in 2019-05-21.
After that a version 2.2.8 was released with SDK `2.2.207` in 2019-11-19 and in this version coverlet is no more supported and throws exception 

## Steps to reproduce
You can follow @PureKrome repro https://github.com/coverlet-coverage/coverlet/issues/1078#issue-798889883

## Expected behavior
I think it should work because it was released after `2.2.300` version

## Actual behavior
Throws exception
```
Starting test execution, please wait...
Data collector 'XPlat code coverage' message: [coverlet]System.MissingMethodException: Make sure to use .NET core SDK Version >= 2.2.300 ---> System.MissingMethodException: Method not found: '!!0 Microsoft.VisualStudio.TestPlatform.ObjectModel.DataCollection.SessionStartEventArgs.GetPropertyValue(System.String)'.
   at Coverlet.Collector.DataCollection.CoverletCoverageCollector.GetPropertyValueWrapper(SessionStartEventArgs sessionStartEventArgs)
   at Coverlet.Collector.DataCollection.CoverletCoverageCollector.GetTestModules(SessionStartEventArgs sessionStartEventArgs) in /_/src/coverlet.collector/DataCollection/CoverletCoverageCollector.cs:line 195
   --- End of inner exception stack trace ---
   at Coverlet.Collector.DataCollection.CoverletCoverageCollector.GetTestModules(SessionStartEventArgs sessionStartEventArgs) in /_/src/coverlet.collector/DataCollection/CoverletCoverageCollector.cs:line 206
   at Coverlet.Collector.DataCollection.CoverletCoverageCollector.OnSessionStart(Object sender, SessionStartEventArgs sessionStartEventArgs) in /_/src/coverlet.collector/DataCollection/CoverletCoverageCollector.cs:line 127.
```

Ref issue https://github.com/coverlet-coverage/coverlet/issues/1078

**Comment by PureKrome** [comment]
A further note to the VSTest team: I understand that SDK 2.2.* is now classified as unsupported / EOF (and we should all be upgrading to 3.1.* or 5.*), but it feels like is an unfair regression which breaks compatability?

**Comment by jakubch1** [comment]
Based on talk with @MarcoRossignoli  closing this as won't fix.

**Comment by MarcoRossignoli** [comment]
Yep I think it's ok that SDK is also out of support.
