### ISSUE TITLE
TestResult can't be deserialized

### ISSUE THREAD

**Issue by dotMorten** [microsoft/vstest#2802]
## Description
If you save a TestResult using the datacontract defined on it, you can't deserialize it again.

## Steps to reproduce
Create a serializer for test results
```cs
var serializer = new System.Runtime.Serialization.DataContractSerializer(typeof(TestResult[]), new Type[] {
                typeof(string[]), typeof(KeyValuePair<string,string>[])
```
Next serialize some test results to a stream:
```cs
serializer.WriteObject(stream, testResults)
```
Rewind the stream and read the results back in again:
```cs
 serializer.ReadObject(stream) as TestResult[]
```

This will throw:
```
System.NullReferenceException: 'Object reference not set to an instance of an object.'

   at Microsoft.VisualStudio.TestPlatform.ObjectModel.TestObject.ProtectedSetPropertyValue(TestProperty property, Object value)
   at Microsoft.VisualStudio.TestPlatform.ObjectModel.TestResult.ProtectedSetPropertyValue(TestProperty property, Object value)
   at Microsoft.VisualStudio.TestPlatform.ObjectModel.TestObject.SetPropertyValue[T](TestProperty property, T value, CultureInfo culture)
   at Microsoft.VisualStudio.TestPlatform.ObjectModel.TestObject.set_StoreKeyValuePairs(List`1 value)
   at System.Runtime.Serialization.ClassDataContract.ReadXmlValue(XmlReaderDelegator xmlReader, XmlObjectSerializerReadContext context)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadDataContractValue(DataContract dataContract, XmlReaderDelegator reader)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator xmlReader, Int32 id, RuntimeTypeHandle declaredTypeHandle, String name, String ns)
   at System.Runtime.Serialization.CollectionDataContract.ReadXmlValue(XmlReaderDelegator xmlReader, XmlObjectSerializerReadContext context)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadDataContractValue(DataContract dataContract, XmlReaderDelegator reader)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns)
   at System.Runtime.Serialization.DataContractSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObject(XmlDictionaryReader reader)
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObject(Stream stream)
```

My guess is this is because the [internal field store](https://github.com/microsoft/vstest/blob/master/src/Microsoft.TestPlatform.ObjectModel/TestObject.cs#L29) isn't being initialized in an `[OnDeserializing]` method (The datacontract deserializer does not call the constructor so that code doesn't execute)

## Expected behavior
Test results can roundtrip just fine.

## Actual behavior
Nullreference exception.

**Comment by Evangelink** [comment]
Hi @dotMorten,

Sorry for the long delay. I have just tried with v17.5 and it seems to be round-tripping fine. I guess the issue was fixed in the meantime so I will move forward by closing this issue.

Please feel free to comment if you are still experiencing some issue or if I didn't test correctly:

```csharp
var serializer = new System.Runtime.Serialization.DataContractSerializer(
    typeof(TestResult[]), 
    new Type[] 
    { 
        typeof(string[]), 
        typeof(KeyValuePair<string, string>[])
    });

var stream = new MemoryStream();
var testResults = new TestResult[]
{
    new TestResult(new TestCase("A.B.C.D", new Uri("executor://A"), "source")),
};
serializer.WriteObject(stream, testResults);
stream.Position = 0;
var deserialized = serializer.ReadObject(stream) as TestResult[];
```

**Comment by dotMorten** [comment]
Yup looks like it was fixed here where it now initializes it upfront:
https://github.com/microsoft/vstest/pull/4450/files
