### ISSUE TITLE
VSTest task erroring out attempting to fetch environment variables

### ISSUE THREAD

**Issue by SinZ163** [microsoft/vstest#2822]
## Description
In one of my Azure DevOps build pipelines, VS Test has been running fine, but randomly today it started erroring out regarding initializing the code coverage functionality.

## Steps to reproduce
Don't have a sample reproducible project this happens that I can distribute

## Expected behavior
Unit tests run as normal with code coverage being tracked

## Actual behavior
VS Test is exiting with code 1 prior to any tests actually running

## Diagnostic logs
```
TpTrace Verbose: 0 : 6236, 1, 2021/03/16, 02:43:44.700, 5504831348, datacollector.exe, DataCollectionManager.AddCollectionEnvironmentVariables: Adding Environment variable 'COR_ENABLE_PROFILING' value '1'
TpTrace Verbose: 0 : 6236, 1, 2021/03/16, 02:43:44.701, 5504837793, datacollector.exe, DataCollectionManager.AddCollectionEnvironmentVariables: Adding Environment variable 'COR_PROFILER' value '{9317ae81-bcd8-47b7-aaa1-a28062e41c71}'
TpTrace Verbose: 0 : 6236, 1, 2021/03/16, 02:43:44.702, 5504843148, datacollector.exe, DataCollectionManager.AddCollectionEnvironmentVariables: Adding Environment variable 'INTELLITRACE_PROFILER_DIRECTORY' value 'C:\hostedtoolcache\windows\VsTest\16.9.1\x64\tools\net451\Common7\IDE\CommonExtensions\Microsoft\IntelliTrace'
TpTrace Verbose: 0 : 6236, 1, 2021/03/16, 02:43:44.702, 5504843741, datacollector.exe, DataCollectionManager.AddCollectionEnvironmentVariables: Adding Environment variable 'VSLOGGER_CPLAN' value 'C:\Users\VssAdministrator\AppData\Local\Microsoft\VisualStudio\16.0\TraceDebugger\Settings\rmzd1qsg.ujv'
TpTrace Verbose: 0 : 6236, 1, 2021/03/16, 02:43:44.702, 5504843980, datacollector.exe, DataCollectionManager.AddCollectionEnvironmentVariables: Adding Environment variable 'VSTS_PROFILER_NOT_CLEAR_ENVVARS' value '1'
TpTrace Error: 0 : 6236, 1, 2021/03/16, 02:43:44.736, 5505188912, datacollector.exe, Data collector 'datacollector://microsoft/CodeCoverage/2.0' logged the following error: Data collector 'Code Coverage' failed to provide initialization information. Error: System.ArgumentNullException: Value cannot be null.
Parameter name: first
   at System.Linq.Enumerable.Concat[TSource](IEnumerable`1 first, IEnumerable`1 second)
   at Microsoft.VisualStudio.Coverage.DynamicCoverageDataCollector.GetEnvironmentVariables()
   at Microsoft.VisualStudio.TestPlatform.Common.DataCollector.DataCollectorInformation.SetTestExecutionEnvironmentVariables()
   at Microsoft.VisualStudio.TestPlatform.Common.DataCollector.DataCollectionManager.GetEnvironmentVariables(Boolean& unloadedAnyCollector)
TpTrace Error: 0 : 6236, 1, 2021/03/16, 02:43:44.737, 5505202229, datacollector.exe, DataCollectionManager.GetEnvironmentVariables: Failed to get variable for Collector 'Code Coverage': System.ArgumentNullException: Value cannot be null.
Parameter name: first
   at System.Linq.Enumerable.Concat[TSource](IEnumerable`1 first, IEnumerable`1 second)
   at Microsoft.VisualStudio.Coverage.DynamicCoverageDataCollector.GetEnvironmentVariables()
   at Microsoft.VisualStudio.TestPlatform.Common.DataCollector.DataCollectorInformation.SetTestExecutionEnvironmentVariables()
   at Microsoft.VisualStudio.TestPlatform.Common.DataCollector.DataCollectionManager.GetEnvironmentVariables(Boolean& unloadedAnyCollector)
TpTrace Verbose: 0 : 6236, 1, 2021/03/16, 02:43:44.739, 5505213383, datacollector.exe, dataCollectorInfo.DisposeDataCollector: calling Dispose() on Microsoft.VisualStudio.Coverage.DynamicCoverageDataCollector
TpTrace Information: 0 : 6236, 1, 2021/03/16, 02:43:44.740, 5505223882, datacollector.exe, UnmanaegVanguard.Stop: Stopping Vanguard.
TpTrace Information: 0 : 6236, 1, 2021/03/16, 02:43:44.741, 5505238288, datacollector.exe, UnmanagedVanguard.Dispose: Disposing vanguard process.
TpTrace Error: 0 : 6236, 1, 2021/03/16, 02:43:44.746, 5505292159, datacollector.exe, Data collector 'datacollector://microsoft/TestImpact/1.0' logged the following error: No diagnostics or data will be collected because the diagnostic data adapters did not initialize.
TpTrace Verbose: 0 : 6236, 1, 2021/03/16, 02:43:44.748, 5505306820, datacollector.exe, PERF: TestImpactDataCollector OnSessionStart: took 2.2393 ms
TpTrace Verbose: 0 : 6236, 1, 2021/03/16, 02:43:44.748, 5505307329, datacollector.exe, PERF WARNING: TestImpactDataCollector OnSessionStart: took 2.2393 ms
TpTrace Error: 0 : 6236, 1, 2021/03/16, 02:43:44.766, 5505492201, datacollector.exe, DataCollectionEvents.SessionStart: Exception occurred while calling handler of type Microsoft.VisualStudio.Coverage.DynamicCoverageDataCollector for SessionStartEventArgs: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.Coverage.DynamicCoverageDataCollector.SessionStart(Object sender, SessionStartEventArgs e)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at Microsoft.VisualStudio.TestPlatform.Utilities.MulticastDelegateUtilities.SafeInvoke(Delegate delegates, Object sender, EventArgs args, String traceDisplayName)
   ```

## Environment
Azure Pipelines agent `windows-2019`.
Tried with both "Latest" visual studio, but also using the "Visual Studio Test Platform Installer" installing stable (16.9.1) and marked the test tasks to use it.

[AB#1300621](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1300621)

**Comment by nohwnd** [comment]
@jakubch1 have you seen this?

**Comment by jakubch1** [comment]
@SinZ163 could you please try to use https://dev.azure.com/dnceng/public/_packaging?_a=package&feed=test-tools&package=Microsoft.TestPlatform&protocolType=NuGet&version=16.10.0-release-20210325-03&view=overview and let me know if this is fixed?

**Comment by SinZ163** [comment]
@jakubch1 sorry about the delay.

That build appears to be working great, though I did turn Test Impact Analysis off beforehand.

**Comment by jakubch1** [comment]
Thanks, closing it.
