### ISSUE TITLE
Logger not working with .Netstandard 2.1

### ISSUE THREAD

**Issue by davidguidali** [microsoft/vstest#3185]
I am using a logger written in c# as a .netstandard 2.0 project. I run this logger against some netcoreapp3.1 tests.
Everything works fine so far, but after updating the logger to .netstandard 2.1, suddenly the tests can't be executed anymore.
Test execution fails with the message:

_Could not find a test logger with AssemblyQualifiedName, URI or FriendlyName 'JsonTestLogger'_

After reverting back the change to use .netstandard 2.0, test execution works again. I faced this locally as well as in CI / CD. The only change made was updating the loggers .netstandard version.

Is this a known issue?

**Comment by nohwnd** [comment]
Please run the tests with diag logs (--diag:log.txt), and post them if you can.

**Comment by davidguidali** [comment]
Thanks for your reply. I copied the relevant piece of code from the logs:

`pTrace Warning: 0 : 2732, 1, 2021/11/22, 16:22:34.413, 773551968173, vstest.console.exe, TestPluginDiscoverer: Failed to load extensions from file 'C:\sources\system-tests\source\CompanyName.IoT.Integration.SystemTests.Platform\bin\Release\netcoreapp3.1\CompanyName.IoT.TestFramework.JsonTestLogger.dll'.  Skipping test extension scan for this file.  Error: System.IO.FileNotFoundException: Could not load file or assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
File name: 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' ---> System.IO.FileNotFoundException: Could not load file or assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
File name: 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Microsoft.VisualStudio.TestPlatform.Common.ExtensionFramework.TestPluginCache.CurrentDomainAssemblyResolve(Object sender, AssemblyResolveEventArgs args)
   at Microsoft.VisualStudio.TestPlatform.PlatformAbstractions.PlatformAssemblyResolver.AssemblyResolverEvent(Object sender, Object eventArgs)
   at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

   at System.ModuleHandle.ResolveType(RuntimeModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type)
   at System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
   at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(CustomAttributeRecord caRecord, MetadataImport scope, Assembly& lastAptcaOkAssembly, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, Object[] attributes, IList derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctor, Boolean& ctorHasParameters, Boolean& isVarArg)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecoratedTargetSecurityTransparent)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeAssembly assembly, RuntimeType caType)
   at System.Reflection.RuntimeAssembly.GetCustomAttributes(Type attributeType, Boolean inherit)
   at System.Attribute.GetCustomAttributes(Assembly element, Boolean inherit)
   at Microsoft.VisualStudio.TestPlatform.ObjectModel.Utilities.AssemblyHelper.GetCustomAttributes(Assembly assembly, String fullyQualifiedName)
   at Microsoft.VisualStudio.TestPlatform.Common.Utilities.TypesToLoadUtilities.GetTypesToLoad(Assembly assembly)
   at Microsoft.VisualStudio.TestPlatform.Common.ExtensionFramework.TestPluginDiscoverer.GetTestExtensionsFromAssembly[TPluginInfo,TExtension](Assembly assembly, Dictionary`2 pluginInfos)
   at Microsoft.VisualStudio.TestPlatform.Common.ExtensionFramework.TestPluginDiscoverer.GetTestExtensionsFromFiles[TPluginInfo,TExtension](String[] files, Dictionary`2 pluginInfos)`

**Comment by nohwnd** [comment]
I don't have a repro, but from the log, the logger is loaded into vstest.console.exe, which is (in some cases, as when you run under VS, or under vs developer console, or under vstest task), a .NET Framework based app. .NET Standard 2.1 does not support .NET Framework, so it cannot load.  https://docs.microsoft.com/en-us/dotnet/standard/net-standard

Are you able to run those same tests with the logger by using `dotnet test`? There the test console should be .NET (Core), based.

**Comment by davidguidali** [comment]
Thanks, makes sense. Running the tests with dotnet test works. I need to update my CI / CD to use dotnet test, I was initially using the vstest task of azure pipelines.

I was also using VSTEST_RUNNER_DEBUG environment variable to debug the logger by attaching to the test process, will this still work with dotnet test?

**Comment by nohwnd** [comment]
Yes, `VSTEST_RUNNER_DEBUG` for debugging vstest.console still works.
