### ISSUE TITLE
VSTest crashes after 30 second timeout even though all tests completed

### ISSUE THREAD

**Issue by AArnott** [microsoft/vstest#3223]
## Description

In [this Azure Pipeline run](https://dev.azure.com/andrewarnott/OSS/_build/results?buildId=5776&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=ea74d3ec-af51-57bf-65e6-f50dd234a1e5&l=32) we see the same set of tests ran 3 times. In the netcoreapp3.1 run, the tests all ran (and passed, evidently) but the test host hung for 30 seconds afterward anyway and then took a dump of itself after that timeout. 

## Steps to reproduce

Run [the pipeline](https://dev.azure.com/andrewarnott/OSS/_build?definitionId=14&_a=summary) on commit [d9e11fe71c245453e65ad0da6d0b081410bf289f](https://github.com/AArnott/Nerdbank.Streams/commit/d9e11fe71c245453e65ad0da6d0b081410bf289f) (or probably any other) enough to hit what seems to be a sporadic failure.

## Expected behavior

The test host exits after all tests have been run.

## Actual behavior

```
Test run for D:\a\1\s\bin\Nerdbank.Streams.Tests\Release\netcoreapp3.1\Nerdbank.Streams.Tests.dll (.NETCoreApp,Version=v3.1)
Microsoft (R) Test Execution Command Line Tool Version 17.0.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
Logging Vstest Diagnostics in file: D:\a\1\a\test_logs\netcoreapp3.1.txt
A total of 1 test files matched the specified pattern.
Blame: Attaching crash dump utility to process testhost (6632).
The active test run was aborted. Reason: Test host process crashed
Data collector 'Blame' message: The specified inactivity time of 30 seconds has elapsed. Collecting hang dumps from testhost and its child processes.
Data collector 'Blame' message: Dumping 6632 - testhost.
Data collector 'Blame' message: All tests finished running, Sequence file will not be generated.
Results File: D:\a\_temp\VssAdministrator_WIN-DUPVMCTGT2G_2021-12-14_21_42_05.trx

Attachments:
  D:\a\_temp\6af6cec4-09ed-4637-8a06-2b39aaf01e85\testhost_6632_20211214T214153_hangdump.dmp
Test Run Aborted with error System.Exception: One or more errors occurred.
 ---> System.Exception: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
 ---> System.Exception: An existing connection was forcibly closed by the remote host.
   at System.Net.Sockets.NetworkStream.Read(Span`1 buffer)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Span`1 buffer)
   at System.Net.Sockets.NetworkStream.ReadByte()
   at System.IO.BinaryReader.Read7BitEncodedInt()
   at System.IO.BinaryReader.ReadString()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.LengthPrefixCommunicationChannel.NotifyDataAvailable()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.TcpClientExtensions.MessageLoopAsync(TcpClient client, ICommunicationChannel channel, Action`1 errorHandler, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---.
     1>Done Building Project "D:\a\1\s\Nerdbank.Streams.sln" (VSTest target(s)) -- FAILED.
```

## Diagnostic logs

[Logs and dump file](https://microsoft-my.sharepoint.com/:u:/p/andarno/EWbgrlN1CfZDqogrin1lnG4B2Aotw5GSbRjntvdMARbXnw?e=6kDeYu)

## Environment

Windows Azure Pipelines hosted agent
.NET 6.0.100 SDK

**Comment by nohwnd** [comment]
I don't think the tests run in this case.

Looking at your logs, I can see that xunit report run start, then there are some first chance exceptions happening in testhost (where xunit is also loaded), then there is silence, then finally 2 seconds before your 30s timeout, some libraries start to load and test discovery is kicked off. Tests are discovered barely before the 30s timeout runs out and hang dumps the process. Imho this works as expected, and you are running into some other issue which makes the discovery stall. If your tests run each under 10s try shortening the timeout to 25, hopefully it will catch the system in hanging state.

**Comment by AArnott** [comment]
Thank you for your analysis. I would like to understand which log file(s) led you to this conclusion so I can self-diagnose next time. If this particular thing happens again, I'll reduce the timeout to 25 seconds to see what I get.

**Comment by nohwnd** [comment]
Reposting the logs here, because they are okay to publish. They are annotated with the seconds, and duration since the last timer reset (hang dump collector resets timer every time it gets an event, the timeout was set to 30s for this run.)

The log entries are a combination of *.datacollector.* log, and *.host.* log. Each line has the "executable" in the line, datacollector log has datacollector.dll and host log has testhost.dll. 

There is third log. vstest.console log, that has information about vstest.console and all the messages sent to it by host and datacollectors, but that is irrelevant here. 

```

>>>:23 +0s inactivity timer is reset TpTrace Verbose: 0 : 4880, 1, 2021/12/14, 21:41:23.370, 7905770549, datacollector.dll, Reset the inactivity timer since an event was received.
>>>:29 +6s data collector is setup and starts observing testhost for crashes: TpTrace Information: 0 : 4880, 7, 2021/12/14, 21:41:29.576, 7967831854, datacollector.dll, Accepted Client request and set the flag
>>>:36 +13s tests start according to xunit TpTrace Verbose: 0 : 6632, 5, 2021/12/14, 21:41:36.821, 8040273439, testhost.dll, BaseRunTests.RunTestInternalWithExecutors: Running tests for executor://xunit/VsTestRunner2/netcoreapp
TpTrace Information: 0 : 6632, 5, 2021/12/14, 21:41:36.886, 8040929402, testhost.dll, [xUnit.net 00:00:00.03] xUnit.net VSTest Adapter v2.4.3+1b45f5407b (64-bit .NET Core 3.1.22)
TpTrace Verbose: 0 : 6632, 5, 2021/12/14, 21:41:36.887, 8040939085, testhost.dll, TestRequestHandler.SendData:  sending data from testhost: {"Version":5,"MessageType":"TestSession.Message","Payload":{"MessageLevel":0,"Message":"[xUnit.net 00:00:00.03] xUnit.net VSTest Adapter v2.4.3+1b45f5407b (64-bit .NET Core 3.1.22)"}}
>>>:36 +13s some file load exceptions are thrown, and some exception is thrown (these are all first chance) TpTrace Information: 0 : 4880, 10, 2021/12/14, 21:41:35.966, 8031730505, datacollector.dll, ProcDumpCrashDumper.OutputReceivedCallback: Output received from procdump process: [21:41:35] Exception: E06D7363.PEAVEEFileLoadException@@
TpTrace Information: 0 : 4880, 10, 2021/12/14, 21:41:36.091, 8032973769, datacollector.dll, ProcDumpCrashDumper.OutputReceivedCallback: Output received from procdump process: [21:41:36] Exception: E06D7363.msc
TpTrace Information: 0 : 4880, 10, 2021/12/14, 21:41:36.108, 8033145674, datacollector.dll, ProcDumpCrashDumper.OutputReceivedCallback: Output received from procdump process: [21:41:36] Exception: E06D7363.PEAVEEFileLoadException@@
TpTrace Information: 0 : 4880, 10, 2021/12/14, 21:41:36.108, 8033147255, datacollector.dll, ProcDumpCrashDumper.OutputReceivedCallback: Output received from procdump process: [21:41:36] Exception: E06D7363.msc
TpTrace Information: 0 : 4880, 10, 2021/12/14, 21:41:36.109, 8033156852, datacollector.dll, ProcDumpCrashDumper.OutputReceivedCallback: Output received from procdump process: [21:41:36] Exception: E06D7363.PEAVEEFileLoadException@@
TpTrace Information: 0 : 4880, 11, 2021/12/14, 21:41:36.253, 8034600192, datacollector.dll, ProcDumpCrashDumper.OutputReceivedCallback: Output received from procdump process: [21:41:36] Exception: E0434352.CLR
>>>:37 +14s nothing happens as we wait for something to report but xunit never gives us anything TpTrace Verbose: 0 : 6632, 7, 2021/12/14, 21:41:37.743, 8049503406, testhost.dll, TcpClientExtensions.MessageLoopAsync: Polling on remoteEndPoint: [::ffff:127.0.0.1]:54820 localEndPoint: [::ffff:127.0.0.1]:54822
TpTrace Verbose: 0 : 6632, 7, 2021/12/14, 21:41:38.745, 8059522193, testhost.dll, TcpClientExtensions.MessageLoopAsync: Polling on remoteEndPoint: [::ffff:127.0.0.1]:54820 localEndPoint: [::ffff:127.0.0.1]:54822
TpTrace Verbose: 0 : 6632, 7, 2021/12/14, 21:41:39.747, 8069541610, testhost.dll, TcpClientExtensions.MessageLoopAsync: Polling on remoteEndPoint: [::ffff:127.0.0.1]:54820 localEndPoint: [::ffff:127.0.0.1]:54822
TpTrace Verbose: 0 : 6632, 7, 2021/12/14, 21:41:40.749, 8079557334, testhost.dll, TcpClientExtensions.MessageLoopAsync: Polling on remoteEndPoint: [::ffff:127.0.0.1]:54820 localEndPoint: [::ffff:127.0.0.1]:54822
TpTrace Verbose: 0 : 6632, 7, 2021/12/14, 21:41:41.751, 8089573297, testhost.dll, TcpClientExtensions.MessageLoopAsync: Polling on remoteEndPoint: [::ffff:127.0.0.1]:54820 localEndPoint: [::ffff:127.0.0.1]:54822
TpTrace Verbose: 0 : 6632, 7, 2021/12/14, 21:41:42.752, 8099587740, testhost.dll, TcpClientExtensions.MessageLoopAsync: Polling on remoteEndPoint: [::ffff:127.0.0.1]:54820 localEndPoint: [::ffff:127.0.0.1]:54822
TpTrace Verbose: 0 : 6632, 7, 2021/12/14, 21:41:43.753, 8109597879, testhost.dll, TcpClientExtensions.MessageLoopAsync: Polling on remoteEndPoint: [::ffff:127.0.0.1]:54820 localEndPoint: [::ffff:127.0.0.1]:54822
TpTrace Verbose: 0 : 6632, 7, 2021/12/14, 21:41:44.758, 8119649888, testhost.dll, TcpClientExtensions.MessageLoopAsync: Polling on remoteEndPoint: [::ffff:127.0.0.1]:54820 localEndPoint: [::ffff:127.0.0.1]:54822
TpTrace Verbose: 0 : 6632, 7, 2021/12/14, 21:41:45.760, 8129663637, testhost.dll, TcpClientExtensions.MessageLoopAsync: Polling on remoteEndPoint: [::ffff:127.0.0.1]:54820 localEndPoint: [::ffff:127.0.0.1]:54822
TpTrace Verbose: 0 : 6632, 7, 2021/12/14, 21:41:46.761, 8139673383, testhost.dll, TcpClientExtensions.MessageLoopAsync: Polling on remoteEndPoint: [::ffff:127.0.0.1]:54820 localEndPoint: [::ffff:127.0.0.1]:54822
TpTrace Verbose: 0 : 6632, 7, 2021/12/14, 21:41:47.762, 8149681643, testhost.dll, TcpClientExtensions.MessageLoopAsync: Polling on remoteEndPoint: [::ffff:127.0.0.1]:54820 localEndPoint: [::ffff:127.0.0.1]:54822
TpTrace Verbose: 0 : 6632, 7, 2021/12/14, 21:41:48.762, 8159685393, testhost.dll, TcpClientExtensions.MessageLoopAsync: Polling on remoteEndPoint: [::ffff:127.0.0.1]:54820 localEndPoint: [::ffff:127.0.0.1]:54822
TpTrace Verbose: 0 : 6632, 7, 2021/12/14, 21:41:49.763, 8169689484, testhost.dll, TcpClientExtensions.MessageLoopAsync: Polling on remoteEndPoint: [::ffff:127.0.0.1]:54820 localEndPoint: [::ffff:127.0.0.1]:54822
TpTrace Verbose: 0 : 6632, 7, 2021/12/14, 21:41:50.764, 8179702774, testhost.dll, TcpClientExtensions.MessageLoopAsync: Polling on remoteEndPoint: [::ffff:127.0.0.1]:54820 localEndPoint: [::ffff:127.0.0.1]:54822
>>>:51 +28s Some 14 seconds of waiting and still nothing happens TpTrace Verbose: 0 : 6632, 7, 2021/12/14, 21:41:51.765, 8189707806, testhost.dll, TcpClientExtensions.MessageLoopAsync: Polling on remoteEndPoint: [::ffff:127.0.0.1]:54820 localEndPoint: [::ffff:127.0.0.1]:54822
>>>:52 +29s Assemblies start to resolve TpTrace Information: 0 : 6632, 5, 2021/12/14, 21:41:52.425, 8196308528, testhost.dll, AssemblyResolver.OnResolve: xunit.runner.reporters.netcoreapp10: Resolving assembly.
TpTrace Information: 0 : 6632, 5, 2021/12/14, 21:41:52.425, 8196316506, testhost.dll, AssemblyResolver.OnResolve: xunit.runner.reporters.netcoreapp10: Searching in: 'D:\a\1\s\bin\Nerdbank.Streams.Tests\Release\netcoreapp3.1'.
TpTrace Information: 0 : 6632, 5, 2021/12/14, 21:41:52.426, 8196323054, testhost.dll, AssemblyResolver.OnResolve: xunit.runner.reporters.netcoreapp10: Loading assembly 'D:\a\1\s\bin\Nerdbank.Streams.Tests\Release\netcoreapp3.1\xunit.runner.reporters.netcoreapp10.dll'.
TpTrace Information: 0 : 6632, 5, 2021/12/14, 21:41:52.427, 8196335904, testhost.dll, AssemblyResolver.OnResolve: Resolved assembly: xunit.runner.reporters.netcoreapp10, from path: D:\a\1\s\bin\Nerdbank.Streams.Tests\Release\netcoreapp3.1\xunit.runner.reporters.netcoreapp10.dll
TpTrace Verbose: 0 : 6632, 7, 2021/12/14, 21:41:52.766, 8199716865, testhost.dll, TcpClientExtensions.MessageLoopAsync: Polling on remoteEndPoint: [::ffff:127.0.0.1]:54820 localEndPoint: [::ffff:127.0.0.1]:54822
TpTrace Information: 0 : 6632, 5, 2021/12/14, 21:41:53.362, 8205679008, testhost.dll, [xUnit.net 00:00:16.52]   Discovering: Nerdbank.Streams.Tests
TpTrace Verbose: 0 : 6632, 5, 2021/12/14, 21:41:53.363, 8205689898, testhost.dll, TestRequestHandler.SendData:  sending data from testhost: {"Version":5,"MessageType":"TestSession.Message","Payload":{"MessageLevel":0,"Message":"[xUnit.net 00:00:16.52]   Discovering: Nerdbank.Streams.Tests"}
>>>:53 +30s timeout, hang dumping testhost TpTrace Warning: 0 : 4880, 10, 2021/12/14, 21:41:53.383, 8205891016, datacollector.dll, The specified inactivity time of 30 seconds has elapsed. Collecting hang dumps from testhost and its child processes
```
