### ISSUE TITLE
Testhost exited with exitcode: 255 error: ''

### ISSUE THREAD

**Issue by luizgrs** [microsoft/vstest#3292]
[Attempt--1_4i42ce.diag.txt](https://github.com/microsoft/vstest/files/7959077/Attempt--1_4i42ce.diag.txt)
## Description
VSTest Azure Pipelines task fails when using  vstest platform 17.0.0 with message Testhost processId: 7568 exited with exitcode: 255 error: ''.

It was working fine Jan 11th ago with same version (vstest task, vstest platform and app source), so it may not be related to vstest specifically but such error message is not helpful and we cannot proceed troubleshooting/investigation on our side. Any suggestions?

Thanks!

## Steps to reproduce
- install vstest platform 17.0.0
- vstest.console.exe "D:\agent1\405\s\MyProject\bin\Release\net6.0\MyProject.dll" /Settings:"D:\agent1\_temp\lwkqmegjeuo.tmp.runsettings" /Logger:"trx" /TestAdapterPath:"D:\agent1\405\s" /Diag:"D:\agent1\_temp\"

## Expected behavior
Tests are ran and status is reported

## Actual behavior
Execution halts, no tests related output

## Diagnostic logs
(attached)

## Environment
VsTest 17.0.0 x64
Window Server 2012 R2

**Comment by nohwnd** [comment]
Based on your log it takes 3.5s before testhost exits and vstest.console does not connect to it in the meantime. Could you check your eventlog to see if there are any app crashes reported for testhost? 

TpTrace Verbose: 0 : 8468, 8, 2022/01/28, 13:55:**22.181,** 1147754274743, vstest.console.exe, DotnetTestHostManager: Starting process 'D:\agent1\405\s\MyProject\bin\Release\net6.0\testhost.exe' with command line ' --runtimeconfig "D:\agent1\405\s\MyProject\bin\Release\net6.0\MyProject.runtimeconfig.json" --depsfile "D:\agent1\405\s\MyProject\bin\Release\net6.0\MyProject.deps.json" --port 60898 --endpoint 127.0.0.1:060898 --role client --parentprocessid 8468 --diag "D:\agent1\_temp\Attempt--1_4i42ce.host.22-01-28_13-55-22_16632_4.diag" --tracelevel 4 --datacollectionport 60897 --telemetryoptedin false'
TpTrace Verbose: 0 : 8468, 8, 2022/01/28, 13:55:22.181, 1147754296770, vstest.console.exe, Test Runtime launched
TpTrace Verbose: 0 : 8468, 4, 2022/01/28, 13:55:22.181, 1147754298472, vstest.console.exe, TestRequestSender.WaitForRequestHandlerConnection: waiting for connection with timeout: 600000
TpTrace Warning: 0 : 8468, 10, 2022/01/28, 13:55:25.884, 1147763666511, vstest.console.exe, TestHostManagerCallbacks.ErrorReceivedCallback Test host standard error line: 
TpTrace Verbose: 0 : 8468, 9, 2022/01/28, 13:55:25.884, 1147763685424, vstest.console.exe, TestHostProvider.ExitCallBack: Host exited starting callback.
TpTrace Error: 0 : 8468, 9, 2022/01/28, 13:55:**25.884,** 1147763686965, vstest.console.exe, TestHostManagerCallbacks.ExitCallBack: Testhost processId: 7568 exited with exitcode: 255 error: ''

![image](https://user-images.githubusercontent.com/5735905/151562909-c13568ab-6333-4573-8d7c-714055b088c4.png)

It does not seem like you are missing the right runtime. That would probably exit quicker. Do you have local dumps enabled this seems like the app crashes and it takes some time before it exits because dump is being created in the meantime. 

You can also try running with `--blame-crash`, to see if you get any dump.

**Comment by luizgrs** [comment]
Good call, there are two events there.

It seems something went wrong socket connection.

 I got a miniump from testhost.exe but that captured no exceptions, I will try some other options and the argument you suggested, will also check antivirus.

Thanks

```
at 2022-01-28T12:55:25.000000000Z

Faulting application name: testhost.exe, version: 15.0.0.0, time stamp: 0x607877a2
Faulting module name: ntdll.dll, version: 6.3.9600.20144, time stamp: 0x615be9b3
Exception code: 0xc0000005
Fault offset: 0x0000000000019d26
Faulting process id: 0x1d90
Faulting application start time: 0x01d814464f851ce9
Faulting application path: D:\agent1\405\s\MyApplication\bin\Release\net6.0\testhost.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report Id: 8ee5e027-8039-11ec-80fb-0050568f7381
Faulting package full name: 
Faulting package-relative application ID: 
```

```
at 2022-01-28T12:55:22.000000000Z

Application: testhost.exe
CoreCLR Version: 6.0.21.52210
.NET Version: 6.0.0
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0000005, exception address 00007FFBD2C69D26
Stack:
   at Interop+Winsock.<EnsureInitialized>g__Initialize|55_0()
   at System.Net.SocketProtocolSupportPal.IsSupported(System.Net.Sockets.AddressFamily)
   at System.Net.SocketProtocolSupportPal..cctor()
   at System.Net.Sockets.Socket..ctor(System.Net.Sockets.SocketType, System.Net.Sockets.ProtocolType)
   at System.Net.Sockets.TcpClient.InitializeClientSocket()
   at System.Net.Sockets.TcpClient..ctor(System.Net.Sockets.AddressFamily)
   at System.Net.Sockets.TcpClient..ctor()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.SocketClient..ctor(System.Func`2<System.IO.Stream,Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.Interfaces.ICommunicationChannel>)
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.SocketClient..ctor()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.CommunicationEndpointFactory.Create(Microsoft.VisualStudio.TestPlatform.ObjectModel.ConnectionRole)
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.TestRequestHandler.InitializeCommunication()
   at Microsoft.VisualStudio.TestPlatform.TestHost.DefaultEngineInvoker.Invoke(System.Collections.Generic.IDictionary`2<System.String,System.String>)
   at Microsoft.VisualStudio.TestPlatform.TestHost.Program.Run(System.String[])
   at Microsoft.VisualStudio.TestPlatform.TestHost.Program.Main(System.String[])
```

**Comment by luizgrs** [comment]
News on this:
- It works when Code Coverage is not enabled
- Same happens for 17.0.0 and 16.11.10
- Works fine in Azure Hosted agents (fails in our internal build server)
- Fails for .NET 4.7.2 and 6
- Still fails with Antivirus unloaded and uninstalled
- Server has
   - VS2017 Enterprise
   - VS2019 build tools
   - VS2022 build tools
   - Test Platform installed/setup during build

No luck with /Blame (as I'm not using dotnet test) or with dumps, the ones I got show same ACCESS_DENIED error.

ring any bells?

**Comment by nohwnd** [comment]
Looks like access violation exception in the sockets code. I am not sure how exactly you run your tests, but from the commandline above it looks like you are using VSTest task in AzDo, in the classical graphical interface? There is check box for Collect dumps in case of catastrophic failure (or something like that, it says catastrophic for sure :D ).

If that is the case you should have everything in place to be able to collect dumps, it deploys proc dump for you.


> just show same ACCESS_DENIED error.

Same to what, I can't find where you were referring to it before, nor can I find it in logs. (Or did you mean ACCESS_VIOLATION ?)

**Comment by luizgrs** [comment]
My bad, that's 0xC0000005 - ACCESS_VIOLATION 

This is it by the way:
```
Dump Summary
------------
Dump File:	testhost.net472.x86_6972_20220203T144715_crashdump.dmp : C:\Users\Desktop\testhost.net472.x86_6972_20220203T144715_crashdump.dmp
Last Write Time:	03/02/2022 14:47:17
Process Name:	testhost.net472.x86.exe : D:\agent1\_tool\VsTest\16.11.0\x64\tools\net451\Common7\IDE\Extensions\TestPlatform\testhost.net472.x86.exe
Process Architecture:	x86
Exception Code:	0xC0000005
Exception Information:	The thread tried to read from or write to a virtual address for which it does not have the appropriate access.
Heap Information:	Not Present

System Information
------------------
OS Version:	6.3.9600
CLR Version(s):	4.8.4380.0

Modules
-------
Module Name	Module Path	Module Version
-----------	-----------	--------------
testhost.net472.x86.exe	D:\agent1\_tool\VsTest\16.11.0\x64\tools\net451\Common7\IDE\Extensions\TestPlatform\testhost.net472.x86.exe	15.0.0.0
ntdll.dll	C:\Windows\System32\ntdll.dll	6.3.9600.20144
mscoree.dll	C:\Windows\System32\mscoree.dll	6.3.9600.16384
kernel32.dll	C:\Windows\System32\kernel32.dll	6.3.9600.20237
KERNELBASE.dll	C:\Windows\System32\KERNELBASE.dll	6.3.9600.19724
TmUmSnsr.dll	C:\Windows\System32\TmLWE\TmUmSnsr\1.0.0.1079\TmUmSnsr.dll	1.0.0.1079
psapi.dll	C:\Windows\System32\psapi.dll	6.3.9600.16384
advapi32.dll	C:\Windows\System32\advapi32.dll	6.3.9600.20244
msvcrt.dll	C:\Windows\System32\msvcrt.dll	7.0.9600.16384
sechost.dll	C:\Windows\System32\sechost.dll	6.3.9600.20239
rpcrt4.dll	C:\Windows\System32\rpcrt4.dll	6.3.9600.20237
sspicli.dll	C:\Windows\System32\sspicli.dll	6.3.9600.18454
CRYPTBASE.dll	C:\Windows\System32\CRYPTBASE.dll	6.3.9600.16384
bcryptPrimitives.dll	C:\Windows\System32\bcryptPrimitives.dll	6.3.9600.18895
version.dll	C:\Windows\System32\version.dll	6.3.9600.16384
mscoreei.dll	C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscoreei.dll	4.8.4180.0
shlwapi.dll	C:\Windows\System32\shlwapi.dll	6.3.9600.16384
combase.dll	C:\Windows\System32\combase.dll	6.3.9600.20144
user32.dll	C:\Windows\System32\user32.dll	6.3.9600.19920
gdi32.dll	C:\Windows\System32\gdi32.dll	6.3.9600.20239
kernel.appcore.dll	C:\Windows\System32\kernel.appcore.dll	6.3.9600.16384
clr.dll	C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll	4.8.4380.0
VCRUNTIME140_CLR0400.dll	C:\Windows\System32\VCRUNTIME140_CLR0400.dll	14.10.25028.0
ucrtbase_clr0400.dll	C:\Windows\System32\ucrtbase_clr0400.dll	14.10.25028.0
ole32.dll	C:\Windows\System32\ole32.dll	6.3.9600.20144
Microsoft.IntelliTrace.ProfilerProxy.dll	D:\agent1\_tool\VsTest\16.11.0\x64\tools\net451\Common7\IDE\CommonExtensions\Microsoft\IntelliTrace\ProfilerProxy\x86\Microsoft.IntelliTrace.ProfilerProxy.dll	15.0.18198.1
msvcp140.dll	D:\agent1\_tool\VsTest\16.11.0\x64\tools\net451\Common7\IDE\CommonExtensions\Microsoft\IntelliTrace\ProfilerProxy\x86\msvcp140.dll	14.29.30133.0
VCRUNTIME140.dll	D:\agent1\_tool\VsTest\16.11.0\x64\tools\net451\Common7\IDE\CommonExtensions\Microsoft\IntelliTrace\ProfilerProxy\x86\VCRUNTIME140.dll	14.29.30133.0
api-ms-win-crt-runtime-l1-1-0.dll	C:\Windows\System32\api-ms-win-crt-runtime-l1-1-0.dll	10.0.14393.2247
api-ms-win-crt-heap-l1-1-0.dll	C:\Windows\System32\api-ms-win-crt-heap-l1-1-0.dll	10.0.14393.2247
api-ms-win-crt-string-l1-1-0.dll	C:\Windows\System32\api-ms-win-crt-string-l1-1-0.dll	10.0.14393.2247
api-ms-win-crt-locale-l1-1-0.dll	C:\Windows\System32\api-ms-win-crt-locale-l1-1-0.dll	10.0.14393.2247
api-ms-win-crt-stdio-l1-1-0.dll	C:\Windows\System32\api-ms-win-crt-stdio-l1-1-0.dll	10.0.14393.2247
api-ms-win-crt-filesystem-l1-1-0.dll	C:\Windows\System32\api-ms-win-crt-filesystem-l1-1-0.dll	10.0.14393.2247
api-ms-win-crt-time-l1-1-0.dll	C:\Windows\System32\api-ms-win-crt-time-l1-1-0.dll	10.0.14393.2247
api-ms-win-crt-environment-l1-1-0.dll	C:\Windows\System32\api-ms-win-crt-environment-l1-1-0.dll	10.0.14393.2247
api-ms-win-crt-math-l1-1-0.dll	C:\Windows\System32\api-ms-win-crt-math-l1-1-0.dll	10.0.14393.2247
api-ms-win-crt-convert-l1-1-0.dll	C:\Windows\System32\api-ms-win-crt-convert-l1-1-0.dll	10.0.14393.2247
api-ms-win-crt-utility-l1-1-0.dll	C:\Windows\System32\api-ms-win-crt-utility-l1-1-0.dll	10.0.14393.2247
ucrtbase.dll	C:\Windows\System32\ucrtbase.dll	10.0.14393.2990
Microsoft.IntelliTrace.Profiler.dll	D:\agent1\_tool\VsTest\16.11.0\x64\tools\net451\Common7\IDE\CommonExtensions\Microsoft\IntelliTrace\Microsoft.IntelliTrace.Profiler.dll	16.0.31528.385
oleaut32.dll	C:\Windows\System32\oleaut32.dll	6.3.9600.20016
shell32.dll	C:\Windows\System32\shell32.dll	6.3.9600.20237
authz.dll	C:\Windows\System32\authz.dll	6.3.9600.18790
covrun32.dll	D:\agent1\_tool\VsTest\16.11.0\x64\tools\net451\Team Tools\Dynamic Code Coverage Tools\covrun32.dll	16.0.21270.30394
crypt32.dll	C:\Windows\System32\crypt32.dll	6.3.9600.19913
powrprof.dll	C:\Windows\System32\powrprof.dll	6.3.9600.17031
msasn1.dll	C:\Windows\System32\msasn1.dll	6.3.9600.16384
msxml6.dll	C:\Windows\System32\msxml6.dll	6.30.9600.19846
mscorlib.ni.dll	C:\Windows\assembly\NativeImages_v4.0.30319_32\mscorlib\bc041466ab6cea3300f763227cbe456f\mscorlib.ni.dll	4.8.4380.0
clrjit.dll	C:\Windows\Microsoft.NET\Framework\v4.0.30319\clrjit.dll	4.8.4380.0
cryptsp.dll	C:\Windows\System32\cryptsp.dll	6.3.9600.16384
msdia140.dll	D:\agent1\_tool\VsTest\16.11.0\x64\tools\net451\Team Tools\Dynamic Code Coverage Tools\msdia140.dll	14.29.30032.0
rsaenh.dll	C:\Windows\System32\rsaenh.dll	6.3.9600.20031
bcrypt.dll	C:\Windows\System32\bcrypt.dll	6.3.9600.18541
System.ni.dll	C:\Windows\assembly\NativeImages_v4.0.30319_32\System\f3ff95d699554a7ecc8f2f915c6300ca\System.ni.dll	4.8.4380.0
System.Core.ni.dll	C:\Windows\assembly\NativeImages_v4.0.30319_32\System.Core\4da2582ad61fee848fb8dd3c36cb9927\System.Core.ni.dll	4.8.4380.0
Newtonsoft.Json.ni.dll	C:\Windows\assembly\NativeImages_v4.0.30319_32\Newtonsoft.Json\c517c7793d478e79acddb4abf038f789\Newtonsoft.Json.ni.dll	9.0.1.19813
clbcatq.dll	C:\Windows\System32\clbcatq.dll	2001.12.10530.16384
System.Configuration.ni.dll	C:\Windows\assembly\NativeImages_v4.0.30319_32\System.Configuration\1e0b1abecd7f90ba54d8599036889790\System.Configuration.ni.dll	4.8.4190.0
System.Xml.ni.dll	C:\Windows\assembly\NativeImages_v4.0.30319_32\System.Xml\c73ef8b9c5ddfed09021e89ec8af60da\System.Xml.ni.dll	4.8.3761.0
SHCore.dll	C:\Windows\System32\SHCore.dll	6.3.9600.19750
profapi.dll	C:\Windows\System32\profapi.dll	6.3.9600.16384

```

We now found out it works in Microsoft Hosted Agents (VM they spinup to run builds), so more and more it looks like something in our environment, we are going to test in a new VM soon.

**Comment by nohwnd** [comment]
The processes (vstest.console and testhost) talk on 127.0.0.1 (IPAddress.Loopback) using sockets and tcpip. Maybe you have some setup that allows you to control loopback and that prevents this from happening?
