### ISSUE TITLE
Is the vstest task ready for support .net 6 projects? 

### ISSUE THREAD

**Issue by stomtom** [microsoft/vstest#3654]
## Description
After migration test project from netcoreapp3.1 to net6.0 we run into issues while running tests using vstest task based on latest stable test platform installed.
1. Newly added tests are not added to results. Similar case to [#16341](https://github.com/microsoft/azure-pipelines-tasks/issues/16341).
2. Fail to upload .trx results because of mismatch in Microsoft.Azure.Storage.Common library.

## Logs
Original log from Azure DevOps
```2022-05-19T11:20:24.1416024Z Adding trx file C:\agent\_work\_temp\TestResults\test_results.trx to run attachments
2022-05-19T11:20:24.1555525Z **************** Completed test execution *********************
2022-05-19T11:20:24.7992512Z Result Attachments will be stored in LogStore
2022-05-19T11:20:24.8507542Z Publishing test results to test run '3463356'.
2022-05-19T11:20:24.8553669Z TestResults To Publish 37, Test run id:3463356
2022-05-19T11:20:24.8621443Z Test results publishing 37, remaining: 0. Test run id: 3463356
2022-05-19T11:20:24.9977613Z Published test case results: 37
2022-05-19T11:20:25.0346088Z Result Attachments will be stored in LogStore
2022-05-19T11:20:25.0347922Z Run Attachments will be stored in LogStore
2022-05-19T11:20:25.1706305Z ##[warning]Failed to upload file test_results.trx to Blob , exception message System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Azure.Storage.Common, Version=***.***.0.0, Culture=neutral, PublicKeyToken=3***bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80***3***040)
2022-05-19T11:20:25.1726368Z File name: 'Microsoft.Azure.Storage.Common, Version=***.***.0.0, Culture=neutral, PublicKeyToken=3***bf3856ad364e35'
2022-05-19T11:20:25.1729114Z    at Microsoft.TeamFoundation.TestClient.PublishTestResults.TestLogStore.<_executeWithRetry>d__33.MoveNext()
2022-05-19T11:20:25.1731653Z --- End of stack trace from previous location where exception was thrown ---
2022-05-19T11:20:25.1734512Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2022-05-19T11:20:25.1736356Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2022-05-19T11:20:25.1738375Z    at Microsoft.TeamFoundation.TestClient.PublishTestResults.TestLogStore.<UploadInternalAsync>d__***9.MoveNext()
2022-05-19T11:20:25.1739281Z 
2022-05-19T11:20:25.1740777Z Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework64\v4.0.303***9\clr.dll
2022-05-19T11:20:25.1742845Z Running under executable  C:\agent\_work\_tasks\VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9\2.202.0\Modules\DTAExecutionHost.exe
2022-05-19T11:20:25.1744632Z --- A detailed error log follows. 
2022-05-19T11:20:25.1745201Z 
2022-05-19T11:20:25.1746392Z === Pre-bind state information ===
2022-05-19T11:20:25.1750057Z LOG: DisplayName = Microsoft.Azure.Storage.Common, Version=***.***.0.0, Culture=neutral, PublicKeyToken=3***bf3856ad364e35
2022-05-19T11:20:25.1751887Z  (Fully-specified)
2022-05-19T11:20:25.1753504Z LOG: Appbase = file:///C:/agent/_work/_tasks/VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9/2.202.0/Modules/
2022-05-19T11:20:25.1755104Z LOG: Initial PrivatePath = NULL
2022-05-19T11:20:25.1756861Z Calling assembly : Microsoft.Azure.Storage.DataMovement, Version=***.***.0.0, Culture=neutral, PublicKeyToken=3***bf3856ad364e35.
2022-05-19T11:20:25.1758502Z ===
2022-05-19T11:20:25.1759812Z LOG: This bind starts in default load context.
2022-05-19T11:20:25.1761715Z LOG: Using application configuration file: C:\agent\_work\_tasks\VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9\2.202.0\Modules\DTAExecutionHost.exe.Config
2022-05-19T11:20:25.1763587Z LOG: Using host configuration file: 
2022-05-19T11:20:25.1765336Z LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.303***9\config\machine.config.
2022-05-19T11:20:25.1767437Z LOG: Post-policy reference: Microsoft.Azure.Storage.Common, Version=***.***.0.0, Culture=neutral, PublicKeyToken=3***bf3856ad364e35
2022-05-19T11:20:25.1769628Z LOG: Attempting download of new URL file:///C:/agent/_work/_tasks/VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9/2.202.0/Modules/Microsoft.Azure.Storage.Common.DLL.
2022-05-19T11:20:25.1771646Z WRN: Comparing the assembly name resulted in the mismatch: Minor Version
2022-05-19T11:20:25.1773448Z ERR: Failed to complete setup of assembly (hr = 0x80***3***040). Probing terminated.
2022-05-19T11:20:25.1774219Z 
2022-05-19T11:20:25.1775678Z Failed to upload run logs to LogStore, Trying to upload to FileService
2022-05-19T11:20:25.3863040Z Failed to publish Telemetry Exception: Object reference not set to an instance of an object.
2022-05-19T11:20:25.3879322Z [RunStatistics] Total anticipated execution time: unknown Total actual execution time: 363507.3429
2022-05-19T11:21:51.5754814Z Received the command : Stop
2022-05-19T11:21:51.5757819Z TestExecutionHost.ProcessCommand. Stop Command handled
2022-05-19T11:21:51.5759807Z SliceFetch Aborted. Moving to the TestHostEnd phase
2022-05-19T11:21:51.6567981Z Please use this link to analyze the test run : https://dev.azure.com/abb-es/Product_Name/_TestManagement/Runs#_a=resultQuery&runId=3463356&queryPath=Recent+Run%2FRun3463356
2022-05-19T11:21:51.6570608Z Test run '3463356' is in 'Completed' state with 'Total Tests' : *** and 'Passed Tests' : ***09.
```

Agent readed FusionLogs for Microsoft.Azure.Storage.Common v 11.1.0:
```
Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
Running under executable  C:\agent\_work\_tasks\VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9\2.202.0\Modules\DTAExecutionHost.exe
--- A detailed error log follows. 

=== Pre-bind state information ===
LOG: DisplayName = Microsoft.Azure.Storage.Common, Version=11.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
 (Fully-specified)
LOG: Appbase = file:///C:/agent/_work/_tasks/VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9/2.202.0/Modules/
LOG: Initial PrivatePath = NULL
LOG: Dynamic Base = NULL
LOG: Cache Base = NULL
LOG: AppName = DTAExecutionHost.exe
Calling assembly : Microsoft.Azure.Storage.DataMovement, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\agent\_work\_tasks\VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9\2.202.0\Modules\DTAExecutionHost.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Post-policy reference: Microsoft.Azure.Storage.Common, Version=11.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
LOG: GAC Lookup was unsuccessful.
LOG: Attempting download of new URL file:///C:/agent/_work/_tasks/VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9/2.202.0/Modules/Microsoft.Azure.Storage.Common.DLL.
LOG: Assembly download was successful. Attempting setup of file: C:\agent\_work\_tasks\VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9\2.202.0\Modules\Microsoft.Azure.Storage.Common.dll
LOG: Entering run-from-source setup phase.
LOG: Assembly Name is: Microsoft.Azure.Storage.Common, Version=11.2.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
WRN: Comparing the assembly name resulted in the mismatch: Minor Version
ERR: The assembly reference did not match the assembly definition found.
ERR: Run-from-source setup phase failed with hr = 0x80131040.
ERR: Failed to complete setup of assembly (hr = 0x80131040). Probing terminated.
```

## Environment
Agent installed on Windows 10 Pro.
Visual Studio Test Platform Installer task in version 1.151.3
Visual studio test task in version 2.202.0

**Comment by stomtom** [comment]
Not connected to .net 6 I guess. The main issue is described in [#16341](https://github.com/microsoft/azure-pipelines-tasks/issues/16341) so there is no need to duplicate topics.
