### ISSUE TITLE
TestPlatform V2 swallows the error from test execution

### ISSUE THREAD

**Issue by genlu** [Microsoft/vstest#410]
## Description
When request to run discovered tests from the attached solution, TestPlatform swallow the error and returns no result back (this is found while dogfooding LUT), whereas V1 actually shows the error:
```
------ Run test started ------
[xUnit.net 00:00:00.3643369] Unable to de-serialize test case CustomDiscovererExample.Tests.Test1: System.InvalidOperationException: Could not de-serialize type 'CustomDiscovererExample.XunitExtensions.AlternateTestCase' because it lacks a parameterless constructor.

Server stack trace: 
   at Xunit.Serialization.XunitSerializationInfo.DeserializeSerializable(Type type, String serializedValue) in C:\BuildAgent\work\82a56c38c02ce641\src\common\XunitSerializationInfo.cs:line 210
   at Xunit.Serialization.XunitSerializationInfo.Deserialize(Type type, String serializedValue) in C:\BuildAgent\work\82a56c38c02ce641\src\common\XunitSerializationInfo.cs:line 110
   at Xunit.Sdk.SerializationHelper.Deserialize[T](String serializedValue) in C:\BuildAgent\work\82a56c38c02ce641\src\common\SerializationHelper.cs:line 37
   at Xunit.Sdk.TestFrameworkExecutor`1.Deserialize(String value) in C:\BuildAgent\work\82a56c38c02ce641\src\xunit.execution\Sdk\Frameworks\TestFrameworkExecutor.cs:line 66
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Xunit.Abstractions.ITestFrameworkExecutor.Deserialize(String value)
   at Xunit.Xunit2.Deserialize(String value) in C:\BuildAgent\work\82a56c38c02ce641\src\xunit.runner.utility\Frameworks\v2\Xunit2.cs:line 54
   at Xunit.XunitFrontController.Deserialize(String value) in C:\BuildAgent\work\82a56c38c02ce641\src\xunit.runner.utility\Frameworks\XunitFrontController.cs:line 123
   at Xunit.Runner.VisualStudio.TestAdapter.VsTestRunner.Deserialize(LoggerHelper logger, ITestFrameworkExecutor executor, TestCase testCase) in C:\BuildAgent\work\b97dadc0a591f9a\xunit.runner.visualstudio.desktop\VsTestRunner.cs:line 144
[xUnit.net 00:00:00.4166892]   Starting:    CustomDiscovererExample
[xUnit.net 00:00:00.5269434]   Finished:    CustomDiscovererExample
========== Run test finished: 0 run (0:00:00.857) ==========

```
Here's the code for repro:
https://1drv.ms/f/s!AkbPBE3d3Hv-hLoar6dEgD7F1-Ftqw

## Steps to reproduce
To repro, open the solution provided above in VS2017 RC, try run tests in Test Explorer and LUT, you will see the difference: TE shows an error (in Tests output window) but LUT shows nothing (it discovered the test, request to run it, but no result is returned)

@saikrishnav

**Comment by codito** [comment]
Same as https://github.com/Microsoft/vstest/issues/300?

**Comment by genlu** [comment]
Looks lile it is.

**Comment by sbaid** [comment]
#300 is already addressed. Closing this.
