### ISSUE TITLE
OutOfMemoryException running tests after migration to csproj from project.json

### ISSUE THREAD

**Issue by david-driscoll** [Microsoft/vstest#422]
## Description
I've recently been trying to upgrade some side projects from `project.json` to `csproj` and encountered an issue where I start getting a OutOfMemoryException when I run the tests for the `csproj` version.  When I switch back to my old branch (`project.json`) the tests pass again.

## Steps to reproduce
* Run dotnet test for the project `ReadySelect.EventSourcing.GetEventStore.Tests`
  * `project.json` all tests pass
  * `csproj` 15 tests fail with the following exception.

NOTE: At the time when these tests are failing my desktop is sitting with 11.4 GB RAM in use and 22.3 available.  During the test run, memory does not visibly spike abnormally.

```
System.OutOfMemoryException : Insufficient memory to continue the execution of the program.
Stack Trace:
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at ReflectionAbstractionExtensions.<>c__DisplayClass0_0.<CreateTestClass>b__0()
   at ReflectionAbstractionExtensions.CreateTestClass(ITest test, Type testClassType, Object[] constructorArguments, IMessageBus messageBus, ExecutionTimer timer, CancellationTokenSource cancellationTokenSource)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)Error Message:
 System.OutOfMemoryException : Insufficient memory to continue the execution of the program.
Stack Trace:
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
```

I've shared uploaded the repository in a building state with the tests passing (`project.json`) and with the tests failing (`csproj`).  Also in the shared folder is a log as requested on the mailing list.

https://1drv.ms/f/s!AgLkTq4Fa162kosSPe5vGUu3IIAusg

## Expected behavior
Tests pass

## Actual behavior
15 Tests fail

## Environment
* Project - https://1drv.ms/f/s!AgLkTq4Fa162kosSPe5vGUu3IIAusg

`dotnet --version`
```
1.0.0-rc3-004530

  Microsoft .NET Core Shared Framework Host

  Version  : 1.1.0
  Build    : 928f77c4bc3f49d892459992fb6e1d5542cb5e86
```

**Comment by codito** [comment]
@smadala can you please investigate?

This stack frame seems to repeat:
```
at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
```

Possibly there's a loop in creation of objects.

**Comment by smadala** [comment]
Looks like `CreateInMemChunk()` try to allocate more memory than 32-bit process(testhost.x86) can,  which can be solved by running `dotnet test  -- RunConfiguration.TargetPlatform="x64"` (running testhost). 

In `project.json` scenario it must be launching 64-bit dotnet process. 

I'm unable to download `EventSourcing-projectjson-passing.7z `  because "OneDrive is unable to scan EventSourcing-projectjson-passing.7z for viruses."

When running with x64 process, I see `System.Reflection.ReflectionTypeLoadException : Unable to load one or more of the requested types`, which is due to not able to GetType() from `xunit.runner.visualstudio.testadapter` assembly which is not strong named. Ignoring the assembly makes all tests passed.

Stack trace observed for Insufficient memory to continue the execution of the program.

`at System.Runtime.InteropServices.Marshal.AllocHGlobal(IntPtr cb)
   at EventStore.Core.TransactionLog.Chunks.TFChunk.TFChunk.CreateInMemChunk(ChunkHeader chunkHeader, Int32 fileSize)
   at EventStore.Core.TransactionLog.Chunks.TFChunk.TFChunk.InitNew(ChunkHeader chunkHeader, Int32 fileSize)
   at EventStore.Core.TransactionLog.Chunks.TFChunk.TFChunk.CreateWithHeader(String filename, ChunkHeader header, Int32 fileSize, Boolean inMem)
   at EventStore.Core.TransactionLog.Chunks.TFChunk.TFChunk.CreateNew(String filename, Int32 chunkSize, Int32 chunkStartNumber, Int32 chunkEndNumber, Boolean isScavenged, Boolean inMem)
   at EventStore.Core.TransactionLog.Chunks.TFChunkManager.AddNewChunk()
   at EventStore.Core.TransactionLog.Chunks.TFChunkDb.Open(Boolean verifyHash, Boolean readOnly)
   at EventStore.Core.ClusterVNode..ctor(TFChunkDb db, ClusterVNodeSettings vNodeSettings, IGossipSeedSource gossipSeedSource, InfoController infoController, ISubsystem[] subsystems)
   at EventStore.Core.VNodeBuilder.Build(IOptions options, IPersistentSubscriptionConsumerStrategyFactory[] consumerStrategies)
   at ReadySelect.EventSourcing.GetEventStore.Tests.Integration.Framework.EmbeddedEventStore.Start() 
   at ReadySelect.EventSourcing.GetEventStore.Tests.Integration.ConnectToEventStore..ctor() 
   at ReadySelect.EventSourcing.GetEventStore.Tests.Integration.Framework.RepositoryScenarioBuilder..ctor() 
   at ReadySelect.EventSourcing.GetEventStore.Tests.Integration.AsyncRepositoryTests.WithStreamPresentInStore..ctor() 
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)`

**Comment by smadala** [comment]
xunit/xunit#1086 raised issue for xunit.runner.visualstudio.testadapter being not strong-named.
