### ISSUE TITLE
Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.JsonDataSerializer Failed to load NewtonSoft.Json if the test binary was create with SDK 17.4.x

### ISSUE THREAD

**Issue by shpengmsft** [microsoft/vstest#4254]
## Description
Test binary (.dll) create with SDK 17.3.1 has no problem at run time.
dotnet test xxxxx.dll  is fine

Once we upgrade the SDK to 17.4.0 or 17.4.1, the test is broken.

## Steps to reproduce
1, build test binary (xxxxxx.dll) with SDK 17.4.0 or 17.4.1
2. dotnet test xxxxxxx.dll
## Expected behavior
Running tests

## Actual behavior

Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.JsonDataSerializer Failed to load NewtonSoft.Json

## Diagnostic logs
2023-01-11T19:23:41.7190792Z C:\hostedtoolcache\windows/dotnet/dotnet test D:\a\r1\a/Backend_CI/Tests/Integration/\**\Tests.Integration.dll --filter  "IntegrationTestRunTarget=BuildValidationGate" --verbosity detailed --logger trx --results-directory D:\a\_temp
2023-01-11T19:23:42.0091601Z ========================== Starting Command Output ===========================
2023-01-11T19:23:42.0436281Z ##[command]"C:\Windows\system32\cmd.exe" /D /E:ON /V:OFF /S /C "CALL "D:\a\_temp\ccc128b5-973e-4f71-8889-cf360779249c.cmd""
2023-01-11T19:23:43.4993695Z 
2023-01-11T19:23:43.5134855Z Welcome to .NET 7.0!
2023-01-11T19:23:43.5135777Z ---------------------
2023-01-11T19:23:43.5136318Z SDK Version: 7.0.101
2023-01-11T19:23:43.5136464Z 
2023-01-11T19:23:43.5140240Z Telemetry
2023-01-11T19:23:43.5140970Z ---------
2023-01-11T19:23:43.5142098Z The .NET tools collect usage data in order to help us improve your experience. It is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.
2023-01-11T19:23:43.5142817Z 
2023-01-11T19:23:43.5143744Z Read more about .NET CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry
2023-01-11T19:23:43.5144062Z 
2023-01-11T19:23:43.5144462Z ----------------
2023-01-11T19:23:43.5144964Z Installed an ASP.NET Core HTTPS development certificate.
2023-01-11T19:23:43.5145618Z To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only).
2023-01-11T19:23:43.5146234Z Learn about HTTPS: https://aka.ms/dotnet-https
2023-01-11T19:23:43.5146714Z ----------------
2023-01-11T19:23:43.5147209Z Write your first app: https://aka.ms/dotnet-hello-world
2023-01-11T19:23:43.5147771Z Find out what's new: https://aka.ms/dotnet-whats-new
2023-01-11T19:23:43.5148326Z Explore documentation: https://aka.ms/dotnet-docs
2023-01-11T19:23:43.5148922Z Report issues and find source on GitHub: https://github.com/dotnet/core
2023-01-11T19:23:43.5149584Z Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli
2023-01-11T19:23:43.5150268Z --------------------------------------------------------------------------------------
2023-01-11T19:23:44.6628162Z Microsoft (R) Test Execution Command Line Tool Version 17.4.0 (x64)
2023-01-11T19:23:44.6630021Z Copyright (c) Microsoft Corporation.  All rights reserved.
2023-01-11T19:23:44.6709570Z 
2023-01-11T19:23:45.5376683Z Starting test execution, please wait...
2023-01-11T19:23:45.6103070Z A total of 1 test files matched the specified pattern.
2023-01-11T19:23:45.6104423Z D:\a\r1\a/Backend_CI/Tests/Integration/Tests.Integration.dll
2023-01-11T19:23:47.8044402Z Testhost process for source(s) 'D:\a\r1\a/Backend_CI/Tests/Integration/Tests.Integration.dll' exited with error: Unhandled exception. System.TypeInitializationException: The type initializer for 'Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.JsonDataSerializer' threw an exception.
2023-01-11T19:23:47.8046683Z  ---> System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
2023-01-11T19:23:47.8049925Z File name: 'Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
2023-01-11T19:23:47.8050878Z    at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.JsonDataSerializer..cctor()
2023-01-11T19:23:47.8051756Z    --- End of inner exception stack trace ---
2023-01-11T19:23:47.8052691Z    at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.JsonDataSerializer.get_Instance()
2023-01-11T19:23:47.8053639Z    at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.TestRequestHandler..ctor()
2023-01-11T19:23:47.8054523Z    at Microsoft.VisualStudio.TestPlatform.TestHost.DefaultEngineInvoker..ctor()
2023-01-11T19:23:47.8055442Z    at Microsoft.VisualStudio.TestPlatform.TestHost.Program.GetEngineInvoker(IDictionary`2 argsDictionary)
2023-01-11T19:23:47.8056438Z    at Microsoft.VisualStudio.TestPlatform.TestHost.Program.Run(String[] args, UiLanguageOverride uiLanguageOverride)
2023-01-11T19:23:47.8057366Z    at Microsoft.VisualStudio.TestPlatform.TestHost.Program.Run(String[] args)
2023-01-11T19:23:47.8058210Z    at Microsoft.VisualStudio.TestPlatform.TestHost.Program.Main(String[] args)
2023-01-11T19:23:47.8058992Z . Please check the diagnostic logs for more information.
2023-01-11T19:23:47.8720404Z 
2023-01-11T19:23:47.8770711Z Test Run Aborted.
2023-01-11T19:23:47.9210746Z Results File: D:\a\_temp\VssAdministrator_WIN-8G6AVJB078M_2023-01-11_19_23_47.trx

## Environment
.NET 7.0
NewtonSoft.Json version 13.0.1

**Comment by shpengmsft** [comment]
Same issue in 17.5.0-preview-20221221-03 pkg.

**Comment by nohwnd** [comment]
@shpengmsft I am using dotnet new to create a new project, and changed the sdk version, and I don't see the problem happening.

```csproj
<!-- file mstest60.csproj -->
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.4.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="2.2.10" />
    <PackageReference Include="MSTest.TestFramework" Version="2.2.10" />
    <PackageReference Include="coverlet.collector" Version="3.1.2" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
  </ItemGroup>

</Project>

```

```cs
// file UnitTest1.cs
namespace mstest60;

[TestClass]
public class UnitTest1
{
    [TestMethod]
    public void TestMethod1()
    {
    }
}
```

```cs
// file Usings.cs
global using Microsoft.VisualStudio.TestTools.UnitTesting;
```

What testing framework are you using and what version of vstest (you can see that on the top of your console output: Microsoft (R) Test Execution Command Line Tool Version 17.5.0-preview-20221130-01 (x64)).

Thanks.

**Comment by shpengmsft** [comment]
This happened with one of my DevOps pipeline right after I changed the Test.SDK version to 17.4.x. If I change it back to 17.3.1, it works.  Please note, the build has no problem. Issue happens at "dotnet test xxx".

I past all the information below please help to take a look. Downgrading the build environment to 17.3.1 will have impact on other project, I wish we can fix it in 17.4.x. Thanks!

2023-01-17T05:18:12.8724317Z ##[section]Starting: Run Post-Deployment Tests
2023-01-17T05:18:12.8945413Z ==============================================================================
2023-01-17T05:18:12.8946236Z Task         : Command line
2023-01-17T05:18:12.8946866Z Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
2023-01-17T05:18:12.8947474Z Version      : 2.212.0
2023-01-17T05:18:12.8947639Z Author       : Microsoft Corporation
2023-01-17T05:18:12.8947874Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
2023-01-17T05:18:12.8948150Z ==============================================================================
2023-01-17T05:18:14.8926124Z Generating script.
2023-01-17T05:18:14.9125076Z Script contents: shell
2023-01-17T05:18:14.9163565Z dotnet test D:\a\r1\a/_drop/Tests/Integration/\**\Integration.dll --filter  "IntegrationTestRunTarget=BuildValidationGate | IntegrationTestRunTarget=BuildValidationGateMaster | IntegrationTestRunTarget=All" --verbosity detailed --logger trx --results-directory D:\a\_temp
2023-01-17T05:18:14.9706601Z ========================== Starting Command Output ===========================
2023-01-17T05:18:15.0159985Z ##[command]"C:\Windows\system32\cmd.exe" /D /E:ON /V:OFF /S /C "CALL "D:\a\_temp\6e18abdf-e2fa-4e70-bf43-d7bea4dd9e67.cmd""
2023-01-17T05:18:18.6985723Z 
2023-01-17T05:18:18.7085831Z Welcome to .NET 7.0!
2023-01-17T05:18:18.7086655Z ---------------------
2023-01-17T05:18:18.7087321Z SDK Version: 7.0.101
2023-01-17T05:18:18.7087544Z 
2023-01-17T05:18:18.7088102Z Telemetry
2023-01-17T05:18:18.7088667Z ---------
2023-01-17T05:18:18.7090006Z The .NET tools collect usage data in order to help us improve your experience. It is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.
2023-01-17T05:18:18.7090998Z 
2023-01-17T05:18:18.7091761Z Read more about .NET CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry
2023-01-17T05:18:18.7092037Z 
2023-01-17T05:18:18.7092399Z ----------------
2023-01-17T05:18:18.7092927Z Installed an ASP.NET Core HTTPS development certificate.
2023-01-17T05:18:18.7093547Z To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only).
2023-01-17T05:18:18.7094138Z Learn about HTTPS: https://aka.ms/dotnet-https
2023-01-17T05:18:18.7094587Z ----------------
2023-01-17T05:18:18.7095055Z Write your first app: https://aka.ms/dotnet-hello-world
2023-01-17T05:18:18.7095593Z Find out what's new: https://aka.ms/dotnet-whats-new
2023-01-17T05:18:18.7096120Z Explore documentation: https://aka.ms/dotnet-docs
2023-01-17T05:18:18.7096688Z Report issues and find source on GitHub: https://github.com/dotnet/core
2023-01-17T05:18:18.7097306Z Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli
2023-01-17T05:18:18.7097963Z --------------------------------------------------------------------------------------
2023-01-17T05:18:20.3109566Z Microsoft (R) Test Execution Command Line Tool Version 17.4.0 (x64)
2023-01-17T05:18:20.3110727Z Copyright (c) Microsoft Corporation.  All rights reserved.
2023-01-17T05:18:20.3219786Z 
2023-01-17T05:18:21.3259176Z Starting test execution, please wait...
2023-01-17T05:18:21.4174799Z A total of 1 test files matched the specified pattern.
2023-01-17T05:18:21.4176092Z D:\a\r1\a/_drop/Tests/Integration/Integration.dll
2023-01-17T05:18:23.3365661Z Testhost process for source(s) 'D:\a\r1\a/_drop/Tests/Integration/Integration.dll' exited with error: Unhandled exception. System.TypeInitializationException: The type initializer for 'Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.JsonDataSerializer' threw an exception.
2023-01-17T05:18:23.3368481Z  ---> System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
2023-01-17T05:18:23.3371491Z File name: 'Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
2023-01-17T05:18:23.3372237Z    at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.JsonDataSerializer..cctor()
2023-01-17T05:18:23.3372855Z    --- End of inner exception stack trace ---
2023-01-17T05:18:23.3373478Z    at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.JsonDataSerializer.get_Instance()
2023-01-17T05:18:23.3374210Z    at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.TestRequestHandler..ctor()
2023-01-17T05:18:23.3374905Z    at Microsoft.VisualStudio.TestPlatform.TestHost.DefaultEngineInvoker..ctor()
2023-01-17T05:18:23.3375631Z    at Microsoft.VisualStudio.TestPlatform.TestHost.Program.GetEngineInvoker(IDictionary`2 argsDictionary)
2023-01-17T05:18:23.3376447Z    at Microsoft.VisualStudio.TestPlatform.TestHost.Program.Run(String[] args, UiLanguageOverride uiLanguageOverride)
2023-01-17T05:18:23.3377189Z    at Microsoft.VisualStudio.TestPlatform.TestHost.Program.Run(String[] args)
2023-01-17T05:18:23.3377824Z    at Microsoft.VisualStudio.TestPlatform.TestHost.Program.Main(String[] args)
2023-01-17T05:18:23.3378418Z . Please check the diagnostic logs for more information.
2023-01-17T05:18:23.4135135Z 
2023-01-17T05:18:23.4185771Z Test Run Aborted.
2023-01-17T05:18:23.4617588Z Results File: D:\a\_temp\VssAdministrator_WIN-7M9M1SBDDD6_2023-01-17_05_18_23.trx
2023-01-17T05:18:23.6093572Z ##[error]Cmd.exe exited with code '1'.
2023-01-17T05:18:23.6570658Z ##[section]Finishing: Run Post-Deployment Tests

**Comment by nohwnd** [comment]
I tried this exactly. I am using `dotnet test` and 7.0.101 dotnet sdk as you do, and it still works for me just fine. Do you see any differences? What are the references of your test project? Are you installing a specific version of Newtonsoft.Json or something like that? 

Here is what I am using:

[mstest62.zip](https://github.com/microsoft/vstest/files/10444227/mstest62.zip)


```json
# file global.json
{
  "sdk": {
    "version": "7.0.101"
  }
}
```

```csproj
<!-- file mstest62.csproj -->
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.4.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="2.2.10" />
    <PackageReference Include="MSTest.TestFramework" Version="2.2.10" />
    <PackageReference Include="coverlet.collector" Version="3.1.2" />
  </ItemGroup>

</Project>

```

```cs
// file UnitTest1.cs
namespace mstest62;

[TestClass]
public class UnitTest1
{
    [TestMethod]
    public void TestMethod1()
    {
    }
}
```

```cs
// file Usings.cs
global using Microsoft.VisualStudio.TestTools.UnitTesting;
```

**Comment by shpengmsft** [comment]
Thanks for your help! 

Finally, I think we figured it out.  The failure actually caused NOT by the *restore (or build)*, it was actually caused by the publish step after restore/build. 

We found that the publish step copied the wrong NewtonSoft.Json.dll version (9.0.1) to the drop folder.  

I'm closing this issue. 

Again, thank you for all the help and repro efforts.
