### ISSUE TITLE
Test runner crashes during test run

### ISSUE THREAD

**Issue by fearthecowboy** [Microsoft/vstest#450]
## Description
I have a test project that we have previously running using xunit, and are porting to the latest dotnet-cli tools.

When we run the suite, it crashes the test runner

## Steps to reproduce
- clone the project `https://github.com/Azure/autorest/`
- checkout the `coreclr` branch
- `dotnet restore src\modeler\AutoRest.Swagger.Tests`
- `dotnet test  .\src\modeler\AutoRest.Swagger.Tests\AutoRest.Swagger.Tests.csproj`

After 70ish or so tests, it crashes :

```
C:\work\github\autorest-coreclr [coreclr +2 ~2 -0 !]PS>dotnet test  .\src\modeler\AutoRest.Swagger.Tests\AutoRest.Swagger.Tests.csproj
Build started, please wait...
Build completed.

Test run for C:\work\github\autorest-coreclr\src\modeler\AutoRest.Swagger.Tests\bin\Debug\netcoreapp1.0\AutoRest.Swagger.Tests.dll(.NETCoreApp,Version=v1.0)
Microsoft (R) Test Execution Command Line Tool Version 15.0.0.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
Passed   AutoRest.Swagger.Tests.SwaggerModelerCompareTests.GobalParamTypeConstraintsChanged
Passed   AutoRest.Swagger.Tests.SwaggerModelerCompareTests.GobalParamArrayFormatChanged
Passed   AutoRest.Swagger.Tests.SwaggerModelerXmlTests.TestRealPathIrregular
Passed   AutoRest.Swagger.Tests.SwaggerModelerXmlTests.TestRealPathRegular
Passed   AutoRest.Swagger.Tests.SwaggerModelerCompareTests.PropertyTypeChanged
Passed   AutoRest.Swagger.Tests.SwaggerModelerXmlTests.TestNameOverrideRules
Passed   AutoRest.Swagger.Tests.SwaggerModelerCompareTests.ResponseHeaderTypeChanged
Passed   AutoRest.Swagger.Tests.SwaggerModelerTests.TestYamlParsing
Passed   AutoRest.Swagger.Tests.SwaggerModelerValidationTests.LongRunningResponseDefined
Passed   AutoRest.Swagger.Tests.SwaggerModelerValidationTests.NonAppJsonTypeOperationForProduces
Passed   AutoRest.Swagger.Tests.SwaggerModelerCompareTests.PathRemoved
Passed   AutoRest.Swagger.Tests.SwaggerModelerCompareTests.ResponseRemoved
Passed   AutoRest.Swagger.Tests.SwaggerModelerTests.GlobalResponsesReference
Passed   AutoRest.Swagger.Tests.SwaggerModelerValidationTests.VersionFormatValidation
Passed   AutoRest.Swagger.Tests.SwaggerModelerCompareTests.RequestArrayFormatChanged
Passed   AutoRest.Swagger.Tests.SwaggerModelerCompareTests.ProtocolMissing
Passed   AutoRest.Swagger.Tests.SwaggerModelerCompareTests.SameMajorVersionNumberStrict
Passed   AutoRest.Swagger.Tests.SwaggerModelerCompareTests.RequiredRequestHeaderRemoved
Passed   AutoRest.Swagger.Tests.SwaggerModelerValidationTests.SkuModelValidation
Passed   AutoRest.Swagger.Tests.SwaggerModelerCompareTests.OperationIdChanged
Passed   AutoRest.Swagger.Tests.SwaggerModelerCompareTests.RequiredParameterRemoved
Passed   AutoRest.Swagger.Tests.SwaggerModelerValidationTests.OperationsApiValidation
Passed   AutoRest.Swagger.Tests.SwaggerModelerCompareTests.ParameterStatusMore
Passed   AutoRest.Swagger.Tests.SwaggerModelerTests.TestcodeModelWithInheritance
Passed   AutoRest.Swagger.Tests.SwaggerModelerCompareTests.UnreferencedTypeChanged
Passed   AutoRest.Swagger.Tests.SwaggerModelerCompareTests.ParameterMoved
Passed   AutoRest.Swagger.Tests.SwaggerModelerCompareTests.OperationRemoved
Passed   AutoRest.Swagger.Tests.SwaggerModelerValidationTests.TrackedResource4Validation
Passed   AutoRest.Swagger.Tests.SwaggerModelerValidationTests.NoResponsesValidation
Passed   AutoRest.Swagger.Tests.SwaggerModelerCompareTests.ResponseTypeConstraintsChanged
Passed   AutoRest.Swagger.Tests.SwaggerModelerValidationTests.PageableNextLinkNotModeledValidation
Passed   AutoRest.Swagger.Tests.SwaggerModelerCompareTests.ResponseArrayFormatChanged
Passed   AutoRest.Swagger.Tests.SwaggerModelerValidationTests.AvoidMsdnReferencesValidation
Passed   AutoRest.Swagger.Tests.SwaggerModelerCompareTests.RequestTypeConstraintsChanged
Passed   AutoRest.Swagger.Tests.SwaggerModelerValidationTests.ResourceModelValidation
Passed   AutoRest.Swagger.Tests.SwaggerModelerCompareTests.GlobalResponseTypeConstraintsChanged
Passed   AutoRest.Swagger.Tests.SwaggerModelerValidationTests.OperationGroupSingleUnderscoreValidation
Passed   AutoRest.Swagger.Tests.SwaggerModelerCompareTests.UpdatedMinorVersionNumberNotStrict
Passed   AutoRest.Swagger.Tests.SwaggerModelerValidationTests.NestedPropertiesValidation
Passed   AutoRest.Swagger.Tests.SwaggerModelerTests.TestcodeModelWithNoContent
Passed   AutoRest.Swagger.Tests.SwaggerModelerCompareTests.ParameterSchemaNameChanged
Passed   AutoRest.Swagger.Tests.SwaggerModelerValidationTests.MutabilityNotModeledWithReadOnlyValidation
Passed   AutoRest.Swagger.Tests.SwaggerModelerCompareTests.ResponseTypeChanged
Passed   AutoRest.Swagger.Tests.SwaggerModelerCompareTests.UpdatedMajorVersionNumberNotStrict
Passed   AutoRest.Swagger.Tests.SwaggerModelerValidationTests.AnonymousSchemasDiscouragedValidation
Passed   AutoRest.Swagger.Tests.SwaggerModelerCompareTests.ResponseHeaderRemoved
Passed   AutoRest.Swagger.Tests.SwaggerModelerValidationTests.LongRunningResponseForDeleteValidation
Passed   AutoRest.Swagger.Tests.SwaggerModelerTests.TestExternalReferencesWithReferencesInProperties
Passed   AutoRest.Swagger.Tests.SwaggerModelerCompareTests.RequestFormatMissing
Passed   AutoRest.Swagger.Tests.SwaggerModelerValidationTests.UniqueResourcePathsValidation
Passed   AutoRest.Swagger.Tests.SwaggerModelerCompareTests.ResponseFormatAdded
Passed   AutoRest.Swagger.Tests.SwaggerModelerCompareTests.PropertyTypeFormatChanged
Passed   AutoRest.Swagger.Tests.SwaggerModelerValidationTests.GuidUsageValidation
Passed   AutoRest.Swagger.Tests.SwaggerModelerTests.TestcodeModelPolymorhism
Passed   AutoRest.Swagger.Tests.SwaggerModelerCompareTests.ParameterSchemaContentsChanged
Passed   AutoRest.Swagger.Tests.SwaggerModelerCompareTests.UnreferencedDefinitionRemoved
Passed   AutoRest.Swagger.Tests.SwaggerModelerValidationTests.OperationParametersValidation
Passed   AutoRest.Swagger.Tests.SwaggerModelerCompareTests.ResponseAdded
Passed   AutoRest.Swagger.Tests.SwaggerModelerValidationTests.LongRunningResponseForPutValidation
Passed   AutoRest.Swagger.Tests.SwaggerModelerValidationTests.ServiceDefinitionParametersValidation
Passed   AutoRest.Swagger.Tests.SwaggerModelerTests.TestcodeModelFromSimpleSwagger
Passed   AutoRest.Swagger.Tests.SwaggerModelerCompareTests.ParameterConstantChanged
Passed   AutoRest.Swagger.Tests.SwaggerModelerValidationTests.NonAppJsonTypeOperationForConsumes
Passed   AutoRest.Swagger.Tests.SwaggerModelerCompareTests.RequiredParameterAdded
Passed   AutoRest.Swagger.Tests.SwaggerModelerValidationTests.MissingDescriptionValidation
Passed   AutoRest.Swagger.Tests.SwaggerModelerCompareTests.DefinitionRemoved
Passed   AutoRest.Swagger.Tests.SwaggerModelerValidationTests.RequiredPropertiesValidation
Passed   AutoRest.Swagger.Tests.SwaggerModelerCompareTests.ParameterStatusLess
Passed   AutoRest.Swagger.Tests.SwaggerModelerCompareTests.ResponseHeaderAdded
Passed   AutoRest.Swagger.Tests.SwaggerModelerCompareTests.ReversedVersionNumberChange
Passed   AutoRest.Swagger.Tests.SwaggerModelerCompareTests.GobalResponseArrayFormatChanged
Passed   AutoRest.Swagger.Tests.SwaggerModelerValidationTests.TrackedResource3Validation
Passed   AutoRest.Swagger.Tests.SwaggerModelerCompareTests.RequiredRequestHeaderAdded
Error: The active Test Run was aborted.


Test Run Failed.

Total tests: 73. Passed: 73. Failed: 0. Skipped: 0.
Test execution time: 6.3276 Seconds

C:\work\github\autorest-coreclr [coreclr +2 ~2 -0 !]PS>

```

> Please share the setup, commandline for vstest.console, sample project, target
> framework etc.

.NET Command Line Tools (1.0.0-rc4-004769)

## Expected behavior
I'm no rocket scientist, but I'm expecting it not to crash :D

## Actual behavior
Crashes, ... I also captured diag information: 

```
TpTrace Verbose: 0 : 22060, 1, 2017/02/06, 15:03:46.385, 42388814082, vstest.console.dll, TestPluginCache: Discovering the extensions using extension path.
TpTrace Information: 0 : 22060, 1, 2017/02/06, 15:03:46.414, 42388908762, vstest.console.dll, AssemblyResolver: Microsoft.VisualStudio.TestPlatform.Extensions.TrxLogger: Resolving assembly.
TpTrace Information: 0 : 22060, 1, 2017/02/06, 15:03:46.416, 42388914538, vstest.console.dll, AssemblyResolver: Microsoft.VisualStudio.TestPlatform.Extensions.TrxLogger: Resolved assembly. 
TpTrace Verbose: 0 : 22060, 1, 2017/02/06, 15:03:46.422, 42388933801, vstest.console.dll, TestPluginCache: Discovered the extensions using extension path ''.
TpTrace Verbose: 0 : 22060, 1, 2017/02/06, 15:03:46.423, 42388938478, vstest.console.dll, TestPluginCache: Discoverers are ''.
TpTrace Verbose: 0 : 22060, 1, 2017/02/06, 15:03:46.423, 42388939231, vstest.console.dll, TestPluginCache: Executors are ''.
TpTrace Verbose: 0 : 22060, 1, 2017/02/06, 15:03:46.423, 42388939454, vstest.console.dll, TestPluginCache: Setting providers are ''.
TpTrace Verbose: 0 : 22060, 1, 2017/02/06, 15:03:46.423, 42388939599, vstest.console.dll, TestPluginCache: Loggers are 'logger://Microsoft/TestPlatform/TrxLogger/v2'.
TpTrace Information: 0 : 22060, 1, 2017/02/06, 15:03:46.455, 42389047156, vstest.console.dll, RunTestsArgumentProcessor:Execute: Test run is starting.
TpTrace Verbose: 0 : 22060, 1, 2017/02/06, 15:03:46.473, 42389109772, vstest.console.dll, Using effective platform:X86 effective framework:.NETCoreApp,Version=v1.0
TpTrace Verbose: 0 : 22060, 1, 2017/02/06, 15:03:46.498, 42389195020, vstest.console.dll, RunTestsArgumentProcessor:Execute: Queuing Test run.
TpTrace Verbose: 0 : 22060, 1, 2017/02/06, 15:03:46.514, 42389249835, vstest.console.dll, TestEngine: Initializing Parallel Execution as MaxCpuCount is set to: 1
TpTrace Verbose: 0 : 22060, 1, 2017/02/06, 15:03:46.533, 42389315737, vstest.console.dll, TestRunRequest.ExecuteAsync: Creating test run request.
TpTrace Verbose: 0 : 22060, 1, 2017/02/06, 15:03:46.537, 42389328081, vstest.console.dll, TestRunRequest.ExecuteAsync: Starting.
TpTrace Information: 0 : 22060, 1, 2017/02/06, 15:03:46.538, 42389331065, vstest.console.dll, TestRunRequest.ExecuteAsync: Starting run with settings:TestRunCriteria:
   KeepAlive=False,FrequencyOfRunStatsChangeEvent=10,RunStatsChangeEventTimeout=00:00:01.5000000,TestCaseFilter=,TestExecutorLauncher=
   Settingsxml=<RunSettings>
  <RunConfiguration>
    <ResultsDirectory>C:\work\github\autorest-coreclr\src\modeler\AutoRest.Swagger.Tests\TestResults</ResultsDirectory>
    <TargetPlatform>X86</TargetPlatform>
    <TargetFrameworkVersion>.NETCoreApp,Version=v1.0</TargetFrameworkVersion>
  </RunConfiguration>
</RunSettings>

TpTrace Verbose: 0 : 22060, 1, 2017/02/06, 15:03:46.538, 42389331303, vstest.console.dll, TestRunRequest.ExecuteAsync: Wait for the first run request is over.
TpTrace Information: 0 : 22060, 1, 2017/02/06, 15:03:46.542, 42389344540, vstest.console.dll, TestRunRequest.ExecuteAsync: Started.
TpTrace Verbose: 0 : 22060, 1, 2017/02/06, 15:03:46.542, 42389346273, vstest.console.dll, TestRunRequest.WaitForCompletion: Waiting with timeout -1.
TpTrace Information: 0 : 22060, 5, 2017/02/06, 15:03:46.546, 42389361412, vstest.console.dll, ProxyParallelExecutionManager: Triggering test run for next source: C:\work\github\autorest-coreclr\src\modeler\AutoRest.Swagger.Tests\bin\Debug\netcoreapp1.0\AutoRest.Swagger.Tests.dll
TpTrace Verbose: 0 : 22060, 5, 2017/02/06, 15:03:46.550, 42389374918, vstest.console.dll, ProxyExecutionManager: Test host is non shared. Lazy initialize.
TpTrace Information: 0 : 22060, 5, 2017/02/06, 15:03:46.569, 42389437288, vstest.console.dll, Listening on port : 42544
TpTrace Verbose: 0 : 22060, 5, 2017/02/06, 15:03:46.583, 42389485028, vstest.console.dll, DotnetTestHostmanager: Full path of dotnet.exe is C:\Program Files\dotnet\dotnet.exe
TpTrace Verbose: 0 : 22060, 5, 2017/02/06, 15:03:46.583, 42389485481, vstest.console.dll, DotnetTestHostmanager: Adding  --runtimeconfig "C:\work\github\autorest-coreclr\src\modeler\AutoRest.Swagger.Tests\bin\Debug\netcoreapp1.0\AutoRest.Swagger.Tests.runtimeconfig.json" in args
TpTrace Verbose: 0 : 22060, 5, 2017/02/06, 15:03:46.583, 42389486061, vstest.console.dll, DotnetTestHostmanager: Adding  --depsfile "C:\work\github\autorest-coreclr\src\modeler\AutoRest.Swagger.Tests\bin\Debug\netcoreapp1.0\AutoRest.Swagger.Tests.deps.json" in args
TpTrace Verbose: 0 : 22060, 5, 2017/02/06, 15:03:46.589, 42389505995, vstest.console.dll, DotnetTestHostmanager: Reading file C:\work\github\autorest-coreclr\src\modeler\AutoRest.Swagger.Tests\bin\Debug\netcoreapp1.0\AutoRest.Swagger.Tests.deps.json to get path of testhost.dll
TpTrace Verbose: 0 : 22060, 5, 2017/02/06, 15:03:46.665, 42389767168, vstest.console.dll, DotnetTestHostmanager: Relative path of testhost.dll with respect to package folder is microsoft.testplatform.testhost/15.0.0-preview-20161123-03\lib/netstandard1.5/testhost.dll
TpTrace Verbose: 0 : 22060, 5, 2017/02/06, 15:03:46.681, 42389821462, vstest.console.dll, DotnetTestHostmanager: Looking for path microsoft.testplatform.testhost/15.0.0-preview-20161123-03\lib/netstandard1.5/testhost.dll in folder C:\Users\garre\.nuget\packages
TpTrace Verbose: 0 : 22060, 5, 2017/02/06, 15:03:46.681, 42389822331, vstest.console.dll, DotnetTestHostmanager: Full path of testhost.dll is C:\Users\garre\.nuget\packages\microsoft.testplatform.testhost/15.0.0-preview-20161123-03\lib/netstandard1.5/testhost.dll
TpTrace Verbose: 0 : 22060, 5, 2017/02/06, 15:03:46.683, 42389827480, vstest.console.dll, ProcessHelper: Starting process 'C:\Program Files\dotnet\dotnet.exe' with command line 'exec --runtimeconfig "C:\work\github\autorest-coreclr\src\modeler\AutoRest.Swagger.Tests\bin\Debug\netcoreapp1.0\AutoRest.Swagger.Tests.runtimeconfig.json" --depsfile "C:\work\github\autorest-coreclr\src\modeler\AutoRest.Swagger.Tests\bin\Debug\netcoreapp1.0\AutoRest.Swagger.Tests.deps.json" "C:\Users\garre\.nuget\packages\microsoft.testplatform.testhost/15.0.0-preview-20161123-03\lib/netstandard1.5/testhost.dll" --port 42544 --parentprocessid 22060 --diag .\out.host.17-02-06_15-03-46_57711_5.txt'
TpTrace Information: 0 : 22060, 6, 2017/02/06, 15:03:46.877, 42390491695, vstest.console.dll, Accepted Client request and set the flag
TpTrace Verbose: 0 : 22060, 4, 2017/02/06, 15:03:48.790, 42397043035, vstest.console.dll, TestRunRequest:SendTestRunStatsChange: Starting.
TpTrace Verbose: 0 : 22060, 4, 2017/02/06, 15:03:48.794, 42397057392, vstest.console.dll, InProgress is AutoRest.Swagger.Tests.SwaggerModelerValidationTests.LongRunningResponseDefined
TpTrace Verbose: 0 : 22060, 4, 2017/02/06, 15:03:48.794, 42397057805, vstest.console.dll, InProgress is AutoRest.Swagger.Tests.SwaggerModelerCompareTests.ResponseHeaderTypeChanged
TpTrace Verbose: 0 : 22060, 4, 2017/02/06, 15:03:48.794, 42397057974, vstest.console.dll, InProgress is AutoRest.Swagger.Tests.SwaggerModelerTests.GlobalResponsesReference
TpTrace Information: 0 : 22060, 4, 2017/02/06, 15:03:48.798, 42397071668, vstest.console.dll, TestRunRequest:SendTestRunStatsChange: Completed.
TpTrace Verbose: 0 : 22060, 4, 2017/02/06, 15:03:48.805, 42397094648, vstest.console.dll, TestRunRequest:SendTestRunStatsChange: Starting.
TpTrace Verbose: 0 : 22060, 4, 2017/02/06, 15:03:48.805, 42397095045, vstest.console.dll, InProgress is AutoRest.Swagger.Tests.SwaggerModelerTests.TestcodeModelWithInheritance
TpTrace Verbose: 0 : 22060, 4, 2017/02/06, 15:03:48.805, 42397095234, vstest.console.dll, InProgress is AutoRest.Swagger.Tests.SwaggerModelerValidationTests.SkuModelValidation
TpTrace Verbose: 0 : 22060, 4, 2017/02/06, 15:03:48.805, 42397095396, vstest.console.dll, InProgress is AutoRest.Swagger.Tests.SwaggerModelerCompareTests.RequestArrayFormatChanged
TpTrace Information: 0 : 22060, 4, 2017/02/06, 15:03:48.805, 42397095707, vstest.console.dll, TestRunRequest:SendTestRunStatsChange: Completed.
TpTrace Verbose: 0 : 22060, 4, 2017/02/06, 15:03:48.811, 42397115405, vstest.console.dll, TestRunRequest:SendTestRunStatsChange: Starting.
TpTrace Verbose: 0 : 22060, 4, 2017/02/06, 15:03:48.811, 42397115983, vstest.console.dll, InProgress is AutoRest.Swagger.Tests.SwaggerModelerValidationTests.TrackedResource4Validation
TpTrace Verbose: 0 : 22060, 4, 2017/02/06, 15:03:48.811, 42397116127, vstest.console.dll, InProgress is AutoRest.Swagger.Tests.SwaggerModelerTests.TestcodeModelWithNoContent
TpTrace Verbose: 0 : 22060, 4, 2017/02/06, 15:03:48.811, 42397116232, vstest.console.dll, InProgress is AutoRest.Swagger.Tests.SwaggerModelerCompareTests.OperationIdChanged
TpTrace Information: 0 : 22060, 4, 2017/02/06, 15:03:48.812, 42397116405, vstest.console.dll, TestRunRequest:SendTestRunStatsChange: Completed.
TpTrace Verbose: 0 : 22060, 4, 2017/02/06, 15:03:48.840, 42397213270, vstest.console.dll, TestRunRequest:SendTestRunStatsChange: Starting.
TpTrace Verbose: 0 : 22060, 4, 2017/02/06, 15:03:48.840, 42397213541, vstest.console.dll, InProgress is AutoRest.Swagger.Tests.SwaggerModelerValidationTests.AvoidMsdnReferencesValidation
TpTrace Verbose: 0 : 22060, 4, 2017/02/06, 15:03:48.840, 42397213651, vstest.console.dll, InProgress is AutoRest.Swagger.Tests.SwaggerModelerCompareTests.OperationRemoved
TpTrace Information: 0 : 22060, 4, 2017/02/06, 15:03:48.840, 42397213803, vstest.console.dll, TestRunRequest:SendTestRunStatsChange: Completed.
TpTrace Verbose: 0 : 22060, 4, 2017/02/06, 15:03:48.901, 42397422609, vstest.console.dll, TestRunRequest:SendTestRunStatsChange: Starting.
TpTrace Verbose: 0 : 22060, 4, 2017/02/06, 15:03:48.901, 42397422896, vstest.console.dll, InProgress is AutoRest.Swagger.Tests.SwaggerModelerCompareTests.ResponseArrayFormatChanged
TpTrace Verbose: 0 : 22060, 4, 2017/02/06, 15:03:48.901, 42397423012, vstest.console.dll, InProgress is AutoRest.Swagger.Tests.SwaggerModelerTests.TestExternalReferencesWithReferencesInProperties
TpTrace Verbose: 0 : 22060, 4, 2017/02/06, 15:03:48.901, 42397423106, vstest.console.dll, InProgress is AutoRest.Swagger.Tests.SwaggerModelerValidationTests.MutabilityNotModeledWithReadOnlyValidation
TpTrace Information: 0 : 22060, 4, 2017/02/06, 15:03:48.901, 42397423253, vstest.console.dll, TestRunRequest:SendTestRunStatsChange: Completed.
TpTrace Verbose: 0 : 22060, 4, 2017/02/06, 15:03:48.962, 42397630572, vstest.console.dll, TestRunRequest:SendTestRunStatsChange: Starting.
TpTrace Verbose: 0 : 22060, 4, 2017/02/06, 15:03:48.962, 42397630876, vstest.console.dll, InProgress is AutoRest.Swagger.Tests.SwaggerModelerTests.TestcodeModelPolymorhism
TpTrace Verbose: 0 : 22060, 4, 2017/02/06, 15:03:48.962, 42397630998, vstest.console.dll, InProgress is AutoRest.Swagger.Tests.SwaggerModelerCompareTests.UpdatedMinorVersionNumberNotStrict
TpTrace Verbose: 0 : 22060, 4, 2017/02/06, 15:03:48.962, 42397631106, vstest.console.dll, InProgress is AutoRest.Swagger.Tests.SwaggerModelerValidationTests.UniqueResourcePathsValidation
TpTrace Information: 0 : 22060, 4, 2017/02/06, 15:03:48.962, 42397631262, vstest.console.dll, TestRunRequest:SendTestRunStatsChange: Completed.
TpTrace Verbose: 0 : 22060, 4, 2017/02/06, 15:03:49.022, 42397838259, vstest.console.dll, TestRunRequest:SendTestRunStatsChange: Starting.
TpTrace Verbose: 0 : 22060, 4, 2017/02/06, 15:03:49.022, 42397838567, vstest.console.dll, InProgress is AutoRest.Swagger.Tests.SwaggerModelerTests.TestcodeModelFromSimpleSwagger
TpTrace Verbose: 0 : 22060, 4, 2017/02/06, 15:03:49.022, 42397838695, vstest.console.dll, InProgress is AutoRest.Swagger.Tests.SwaggerModelerValidationTests.OperationParametersValidation
TpTrace Verbose: 0 : 22060, 4, 2017/02/06, 15:03:49.023, 42397838815, vstest.console.dll, InProgress is AutoRest.Swagger.Tests.SwaggerModelerCompareTests.ResponseHeaderRemoved
TpTrace Information: 0 : 22060, 4, 2017/02/06, 15:03:49.023, 42397839016, vstest.console.dll, TestRunRequest:SendTestRunStatsChange: Completed.
TpTrace Verbose: 0 : 22060, 4, 2017/02/06, 15:03:49.064, 42397980469, vstest.console.dll, TestRunRequest:SendTestRunStatsChange: Starting.
TpTrace Verbose: 0 : 22060, 4, 2017/02/06, 15:03:49.064, 42397980763, vstest.console.dll, InProgress is AutoRest.Swagger.Tests.SwaggerModelerTests.codeModelWithCircularDependencyThrowsError
TpTrace Verbose: 0 : 22060, 4, 2017/02/06, 15:03:49.064, 42397980891, vstest.console.dll, InProgress is AutoRest.Swagger.Tests.SwaggerModelerCompareTests.PropertyTypeFormatChanged
TpTrace Verbose: 0 : 22060, 4, 2017/02/06, 15:03:49.064, 42397981012, vstest.console.dll, InProgress is AutoRest.Swagger.Tests.SwaggerModelerValidationTests.NonAppJsonTypeOperationForConsumes
TpTrace Information: 0 : 22060, 4, 2017/02/06, 15:03:49.064, 42397981164, vstest.console.dll, TestRunRequest:SendTestRunStatsChange: Completed.
TpTrace Verbose: 0 : 22060, 4, 2017/02/06, 15:03:49.182, 42398386473, vstest.console.dll, TestRunRequest:SendTestRunStatsChange: Starting.
TpTrace Verbose: 0 : 22060, 4, 2017/02/06, 15:03:49.183, 42398386921, vstest.console.dll, InProgress is AutoRest.Swagger.Tests.SwaggerModelerValidationTests.TrackedResource3Validation
TpTrace Verbose: 0 : 22060, 4, 2017/02/06, 15:03:49.183, 42398387130, vstest.console.dll, InProgress is AutoRest.Swagger.Tests.SwaggerModelerCompareTests.RequiredParameterAdded
TpTrace Information: 0 : 22060, 4, 2017/02/06, 15:03:49.183, 42398387400, vstest.console.dll, TestRunRequest:SendTestRunStatsChange: Completed.
TpTrace Information: 0 : 22060, 9, 2017/02/06, 15:03:52.490, 42409710914, vstest.console.dll, AssemblyResolver: System.Core: Resolving assembly.
TpTrace Error: 0 : 22060, 9, 2017/02/06, 15:03:52.504, 42409760459, vstest.console.dll, SocketCommunicationManager ReceiveMessage: failed to receive message System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.IO.Stream.ReadByte()
   at System.IO.BinaryReader.ReadByte()
   at System.IO.BinaryReader.Read7BitEncodedInt()
   at System.IO.BinaryReader.ReadString()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.SocketCommunicationManager.TryReceiveRawMessage(CancellationToken cancellationToken)
TpTrace Error: 0 : 22060, 4, 2017/02/06, 15:03:52.504, 42409761107, vstest.console.dll, Unable to receive message from testhost
TpTrace Information: 0 : 22060, 4, 2017/02/06, 15:03:52.505, 42409763340, vstest.console.dll, AssemblyResolver: Microsoft.TestPlatform.CommunicationUtilities.resources: Resolving assembly.
TpTrace Information: 0 : 22060, 4, 2017/02/06, 15:03:52.506, 42409764616, vstest.console.dll, AssemblyResolver: Microsoft.TestPlatform.CommunicationUtilities.resources: Resolving assembly.
TpTrace Error: 0 : 22060, 4, 2017/02/06, 15:03:52.507, 42409769817, vstest.console.dll, Server: TestExecution: Aborting test run because System.IO.IOException: Unable to communicate with test execution process.
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.TestRequestSender.TryReceiveRawMessage()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.TestRequestSender.ListenAndReportTestResults(ITestRunEventsHandler testRunEventsHandler)
TpTrace Verbose: 0 : 22060, 4, 2017/02/06, 15:03:52.508, 42409772707, vstest.console.dll, TestRunRequest:SendTestRunMessage: Starting.
TpTrace Information: 0 : 22060, 4, 2017/02/06, 15:03:52.509, 42409776081, vstest.console.dll, TestRunRequest:SendTestRunMessage: Completed.
TpTrace Information: 0 : 22060, 3, 2017/02/06, 15:03:52.514, 42409795198, vstest.console.dll, AssemblyResolver: Microsoft.TestPlatform.CoreUtilities.resources: Resolving assembly.
TpTrace Information: 0 : 22060, 3, 2017/02/06, 15:03:52.515, 42409798366, vstest.console.dll, AssemblyResolver: Microsoft.TestPlatform.CoreUtilities.resources: Resolving assembly.
TpTrace Error: 0 : 22060, 4, 2017/02/06, 15:03:52.530, 42409848735, vstest.console.dll, Connection has been broken: not sending SessionEnd message
TpTrace Error: 0 : 22060, 10, 2017/02/06, 15:03:52.532, 42409854293, vstest.console.dll, Connection has been broken: not sending SessionEnd message
TpTrace Verbose: 0 : 22060, 4, 2017/02/06, 15:03:52.542, 42409888816, vstest.console.dll, TestRunRequest:TestRunComplete: Starting. IsAborted:True IsCanceled:False.
TpTrace Information: 0 : 22060, 4, 2017/02/06, 15:03:52.553, 42409928665, vstest.console.dll, TestRunRequest:TestRunComplete: Completed.
TpTrace Verbose: 0 : 22060, 1, 2017/02/06, 15:03:52.556, 42409938242, vstest.console.dll, TestRunRequest.Dispose: Starting.
TpTrace Information: 0 : 22060, 1, 2017/02/06, 15:03:52.556, 42409938549, vstest.console.dll, TestRunRequest.Dispose: Completed.
TpTrace Information: 0 : 22060, 1, 2017/02/06, 15:03:52.556, 42409938680, vstest.console.dll, RunTestsArgumentProcessor:Execute: Test run is completed.
TpTrace Verbose: 0 : 22060, 1, 2017/02/06, 15:03:52.556, 42409938815, vstest.console.dll, Executor.Execute: Exiting with exit code of 1

```

## Environment
Win10 (15021)

**Comment by AbhitejJohn** [comment]
@fearthecowboy : Can you please share with us the crash stack trace from Event viewer? You can possibly also [turn on user mode crash dumps ](https://msdn.microsoft.com/en-us/library/windows/desktop/bb787181(v=vs.85).aspx)and get the call stack.

**Comment by smadala** [comment]
[codeModelWithCircularDependencyThrowsError](https://github.com/Azure/autorest/blob/coreclr/src/modeler/AutoRest.Swagger.Tests/SwaggerModelerTests.cs#L256) test causing Stackoverflow exception. The reason should be log properly once #281 is fixed.

**Comment by fandango-babak** [comment]
I'm having the same issue with VS 2017 Community  Version 15.2 (26430.13) Release.
I see the following in the event viewer

```
Faulting application name: dotnet.exe, version: 1.1.0.1179, time stamp: 0x5820b092
Faulting module name: KERNELBASE.dll, version: 10.0.15063.296, time stamp: 0xa0527b0c
Exception code: 0xe0434352
Fault offset: 0x0000000000069e08
Faulting process id: 0x345c
Faulting application start time: 0x01d2e4cfb369c71b
Faulting application path: C:\Program Files\dotnet\dotnet.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: acb5d009-7dd2-413c-beb9-f704c304d589
Faulting package full name: 
Faulting package-relative application ID: 
```
