### ISSUE TITLE
Diag switch : Exception not getting caught, eventually crashing the process

### ISSUE THREAD

**Issue by singhsarab** [Microsoft/vstest#452]
## Description
> UnauthorizedAccessException not getting handled while creating the log file when diag is enabled.

## Steps to reproduce
>Start dotnet vstest with diag switch and give any path which requires elevated privileges.
>> dotnet vstest /port:123 /diag:C:\log.txt

## Expected behavior
> The error should be handled properly and process should not crash. 

## Actual behavior
> The process exits with following exception

```
Unhandled Exception: System.UnauthorizedAccessException: Access to the path 'c:\foo.txt' is denied.
   at System.IO.Win32FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
   at System.IO.Win32FileSystem.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.File.Open(String path, FileMode mode, FileAccess access, FileShare share)
   at Microsoft.VisualStudio.TestPlatform.ObjectModel.RollingFileTraceListener.OpenTextWriter(String fileName)
   at Microsoft.VisualStudio.TestPlatform.ObjectModel.RollingFileTraceListener..ctor(String fileName, String name, Int32 rollSizeKB)
   at Microsoft.VisualStudio.TestPlatform.ObjectModel.EqtTrace.EnsureTraceIsInitialized()
   at Microsoft.VisualStudio.TestPlatform.ObjectModel.EqtTrace.WriteLine(TraceLevel level, String message)
   at Microsoft.VisualStudio.TestPlatform.ObjectModel.EqtTrace.Error(String format, Object[] args)
   at Microsoft.VisualStudio.TestPlatform.CommandLine.Processors.ArgumentProcessorFactory.<>c__DisplayClass20_0.<WrapLazyProcessorToInitializeOnInstantiation>b__0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at Microsoft.VisualStudio.TestPlatform.CommandLine.Executor.GetArgumentProcessors(String[] args, List`1& processors)
   at Microsoft.VisualStudio.TestPlatform.CommandLine.Executor.Execute(String[] args)
   at Microsoft.VisualStudio.TestPlatform.CommandLine.Program.Main(String[] args)
```

**Comment by Faizan2304** [comment]
Fixed!!
