### ISSUE TITLE
Azure CI pipelines becomes unreliable after update to 17.6.2 (17.6.1 and 17.6.0 were fine)

### ISSUE THREAD

**Issue by vbaderks** [microsoft/vstest#4536]
## Description

I have an open source project that wraps a native image codec and is available as NuGet component.
https://github.com/team-charls/charls-native-dotnet

This project targets Windows, Linux and macOs for .NET Framework 4.8, .NET 6.0 and .NET 7.0.
It has a test project based on NUnit and a Dependabot action configured to update the dependencies.

Dependabot created a pull request to update Microsoft.NET.Test.Sdk from 17.6.1 to 17.6.2.
With 17.6.2 some unit test tasks often fail on the Azure CI build pipeline.

## Steps to reproduce

1. Checkout https://github.com/team-charls/charls-native-dotnet
2. Create a branch
3. Update Microsoft.NET.Test.Sdk from 17.6.1 to 17.6.2
4. Check in the branch and create a PR.

## Expected behavior

All test pass reliable.

## Actual behavior

The unit test process for .NET 6.0 and .NET 7.0 on Window fail. It is mostly the release x86 project.
A re-run may sometimes work and all test pass then.
The Linux, macOS and .NET Framework 4.8 configuration all work fine with 17.6.2.
Older versions: v17.6.0 and v17.6.1 were also working fine.

## Diagnostic logs

The PR of dependabot can be found at:
https://github.com/team-charls/charls-native-dotnet/pull/52
and the several build attempts and log are at:
https://dev.azure.com/team-charls/charls-native-dotnet/_build?definitionId=4

## Environment

The environment on which the tests are failing is the standard "windows-latest" VM image of the Azure CI pipeline.

Building locally and running the tests with:
vstest.console.exe CharLS.Native.Test.dll --Framework:".NETCoreApp,Version=v7.0" --Platform:x86 --Parallel /EnableCodeCoverage
works fine. Running in the Visual Studio 2202 17.6 also works fine.

**Comment by nohwnd** [comment]
Thanks, will have a look.

**Comment by vbaderks** [comment]
@nohwnd If you need more information or help, please let me know.

**Comment by nohwnd** [comment]
@vbaderks Most of the crashes have this stack: 

```
Running all tests in D:\a\1\s\build\bin\Release\net7.0\CharLS.Native.Test.dll
   NUnit3TestExecutor discovered 90 of 90 NUnit test cases using Current Discovery mode, Non-Explicit run
##[error]The active test run was aborted. Reason: Test host process crashed : **Fatal error. 0xC0000005**
##[error]   **at CharLS.Native.Interop.<CharLSValidateSpiffHeader>g____PInvoke|5_0(CharLS.Native.SpiffHeaderNative*, CharLS.Native.FrameInfoNative*)**
##[error]   at CharLS.Native.Interop.CharLSValidateSpiffHeader(CharLS.Native.SpiffHeaderNative ByRef, CharLS.Native.FrameInfoNative ByRef)
##[error]   at CharLS.Native.JpegLSDecoder.ValidateSpiffHeader(CharLS.Native.SpiffHeader)
##[error]   at CharLS.Native.JpegLSDecoder.ReadHeader(Boolean)
##[error]   at CharLS.Native.Test.JpegLSDecoderTest+<>c__DisplayClass21_0.<ReadBadSpiffHeaderThrows>b__0()
##[error]   at NUnit.Framework.Assert.Throws(NUnit.Framework.Constraints.IResolveConstraint, NUnit.Framework.TestDelegate, System.String, System.Object[])
```

This looks like your code is crashing.

There are no changes between 17.6.0 and 17.6.1 test sdk that touch testhost (where your test code is running), the only change is a different version of Nuget.Frameworks library, which I don't think is causing this issue. 

To me it looks more like the built-in version of VS on the azdo image got updated to 17.6.0, and you started building in CI with 17.6.0 vstest.console rather than  17.5.0 vstest.console. Which happened just in time where dependabot was pusing new changes on you to update to 17.6.2. 

Could you possibly disable code coverage and re-run the lastest build on ci to see if that still crashes? I looked at the history of your code and don't see any functional changes, just updates to infrastructure.

**Comment by nohwnd** [comment]
I can see the crash when running locally against 17.6.0 vstest.console. You don't mention if you built locally as Release, which I need to do in order to see the crash.

**Comment by nohwnd** [comment]
Not sure if I wrote that above, disabling code coverage fixes the problem for me. Reported to @jakubch1

**Comment by vbaderks** [comment]
I can confirm that disabling code coverage seems indeed to result in stable builds (did a couple of tests).

I was not able to reproduce a crash locally on a Release or Debug build (with code coverage active). Did you use any special environment settings?

**Comment by nohwnd** [comment]
Nothing at all, just developer console of VS 17.6, up to date. And then I called vstest.console with the parameters above, but I used net6.0 tfm because that was crashing in your CI. It usually crashed 1 in 4 tries, but I also had occasion where it just refused to crash for 20 runs.

**Comment by jakubch1** [comment]
I am investigating issue but can't reproduce it locally. I will try to repro in CI and fetch some additional information. From my initial investigation it looks like native binary `charls-2-x86.dll` under code coverage is causing issue. Especially method `_charls_validate_spiff_header@8`. You can try to exclude this binary or method.

I recommend also to swith to use static native instrumentation. In your case you probably just need to enable https://learn.microsoft.com/en-us/cpp/build/reference/profile-performance-tools-profiler?view=msvc-170. More info here: https://learn.microsoft.com/en-us/visualstudio/test/customizing-code-coverage-analysis?view=vs-2022#static-and-dynamic-native-instrumentation

**Comment by vbaderks** [comment]
@jakubch1 Thanks for the info. I am in the process of adding a CodeCoverage.runsettings file to only include the C# assembly for code coverage.
I am also not able to reproduce the problem locally. It seems that the CI uses the 17.5 C++ compiler (toolset = 14.35.32215) , but using that version still makes the problem not reproducible on my dev machine.

Note: feel free to close this issue as it not a problem of the Microsoft.NET.Test.Sdk assembly.
