### ISSUE TITLE
Error running unit tests - failed to initialize client proxy

### ISSUE THREAD

**Issue by piotrpMSFT** [Microsoft/vstest#467]
Moving from dotnet/cli#5672 on behalf of @JamesNK

-----

## Steps to reproduce

Source code: https://github.com/JamesNK/Newtonsoft.Json/tree/vs2017

```
"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\msbuild.exe" Newtonsoft.Json.Tests.Roslyn.csproj /t:restore
"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\msbuild.exe" Newtonsoft.Json.Tests.Roslyn.csproj /t:build
dotnet test Newtonsoft.Json.Tests.Roslyn.csproj -f netcoreapp1.0
```

## Expected  behavior
Tests execute

## Actual behavior
```
C:\Development\Source\Newtonsoft.Json\Src\Newtonsoft.Json.Tests>dotnet test Newtonsoft.Json.Tests.Roslyn.csproj -f netcoreapp1.0
Build started, please wait...
C:\Program Files\dotnet\sdk\1.0.0-rc4-004771\Microsoft.Common.CurrentVersion.targets(1956,5): warning MSB3277: Found conflicts between different versi
ons of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to det
ailed. [C:\Development\Source\Newtonsoft.Json\Src\Newtonsoft.Json.Tests\Newtonsoft.Json.Tests.Roslyn.csproj]
Build completed.

Test run for C:\Development\Source\Newtonsoft.Json\Src\Newtonsoft.Json.Tests\bin\Debug\netcoreapp1.0\Newtonsoft.Json.Tests.dll(.NETCoreApp,Version=v1.0)
Microsoft (R) Test Execution Command Line Tool Version 15.0.0.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
Error: Failed to initialize client proxy: could not connect to test process.
```

## Environment data
```
C:\Development\Source\Newtonsoft.Json\Src\Newtonsoft.Json.Tests>dotnet --info
.NET Command Line Tools (1.0.0-rc4-004771)

Product Information:
 Version:            1.0.0-rc4-004771
 Commit SHA-1 hash:  4228198f0e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-rc4-004771
```

**Comment by codito** [comment]
@JamesNK This could be due to missing shared runtime. Here are the troubleshooting steps:

* Run `dotnet test -d:log.txt`
* In the `log.txt` file generated, find the command line of dotnet exe invocation (search for `exec ` or `dotnet)
* Copy the command line and run it directly in command prompt
* You will see an error message on which shared runtime version is missing. Install it from https://www.microsoft.com/net/download/core#/runtime

Related to #281.

**Comment by JamesNK** [comment]
I run this:

```
C:\Development\Source\Newtonsoft.Json\Src\Newtonsoft.Json.Tests>dotnet exec --runtimeconfig "C:\Development\Source\Newtonsoft.Json\Src\Newtonsoft.Json.Tests\bin\Debug\netcoreapp1.0\Newtonsoft.Json.Tests.runtimeconfig.json" --depsfile "C:\Development\Source\Newtonsoft.Json\Src\Newtonsoft.Json.Tests\bin\Debug\netcoreapp1.0\Newtonsoft.Json.Tests.deps.json" "C:\Users\James\.nuget\packages\microsoft.testplatform.testhost/15.0.0-preview-20170210-02\lib
/netstandard1.5/testhost.dll" --port 3066 --parentprocessid 13476 --diag log.host.17-02-11_17-09-59_17962_5.txt
```

And I didn't get any output in the console.

I did take a look inside the log.host.date.txt file and saw this:

```
TpTrace Error: 0 : 10324, 1, 2017/02/11, 17:12:37.460, 608551461389, testhost.dll, TestHost: Error occured during initialization of TestHost : System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.JsonDataSerializer..ctor()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.JsonDataSerializer.get_Instance()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.TestRequestHandler..ctor()
   at Microsoft.VisualStudio.TestPlatform.TestHost.DefaultEngineInvoker.Invoke(IDictionary`2 argsDictionary)
   at Microsoft.VisualStudio.TestPlatform.TestHost.Program.Main(String[] args)
TpTrace Error: 0 : 14948, 1, 2017/02/11, 17:12:59.982, 608606319240, testhost.dll, TestHost: Error occured during initialization of TestHost : System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.JsonDataSerializer..ctor()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.JsonDataSerializer.get_Instance()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.TestRequestHandler..ctor()
   at Microsoft.VisualStudio.TestPlatform.TestHost.DefaultEngineInvoker.Invoke(IDictionary`2 argsDictionary)
   at Microsoft.VisualStudio.TestPlatform.TestHost.Program.Main(String[] args)
```

The assembly I'm testing also happens to be Newtonsoft.Json.

**Comment by codito** [comment]
What's the version of json.net under test? If it's a higher version, the dependency closure should ensure it always picks the highest version.

Testhost requires `9.0.1`. Can you please share `C:\Development\Source\Newtonsoft.Json\Src\Newtonsoft.Json.Tests\bin\Debug\netcoreapp1.0\Newtonsoft.Json.Tests.deps.json`?

**Comment by JamesNK** [comment]
Ah success. Increasing the version number to be higher than 9.0.1 worked.

FYI for future trouble shooting: deps.json only shows package versions, not assembly versions, which is what mattered here.
