### ISSUE TITLE
Could not load file or assembly 'Microsoft.VisualStudio.CodeCoverage.Shim'

### ISSUE THREAD

**Issue by ibiglari** [microsoft/vstest#4818]
## Description

I am unable to run tests with VS Professional version 17.8.4. I get the below error message:

```
========== Starting test run ==========
Testhost process for source(s) 'C:\Users\xxx\IntegrationTests.dll' exited with error: Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.CodeCoverage.Shim, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
   at Microsoft.VisualStudio.TestPlatform.ObjectModel.EqtTrace.Error(String format, Object[] args)
   at Microsoft.VisualStudio.TestPlatform.TestHost.Program.Main(String[] args) in /_/src/testhost.x86/Program.cs:line 41
. Please check the diagnostic logs for more information.
Testhost process for source(s) 'C:\Users\xxx\IntegrationTests.dll' exited with error: Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.CodeCoverage.Shim, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
   at Microsoft.VisualStudio.TestPlatform.ObjectModel.EqtTrace.Error(String format, Object[] args)
   at Microsoft.VisualStudio.TestPlatform.TestHost.Program.Main(String[] args) in /_/src/testhost.x86/Program.cs:line 41
. Please check the diagnostic logs for more information.
========== Test run aborted: 0 Tests (0 Passed, 0 Failed, 0 Skipped) run in < 1 ms ==========

```

I am using `Microsoft::VisualStudio::CppUnitTestFramework`. The only way to get around is by using this [comment](https://github.com/microsoft/vstest/issues/3382#issuecomment-1043053889).

I am a little confused as my tests are native and not managed code. What can I do to get the test runner to behave?
## Expected behavior

I'd like to be able to run and debug my tests and gather code coverage.

## Actual behavior

Tests are aborted

## Diagnostic logs

Not sure how to force test runner to produce logs from inside Visual Studio.

## Environment

Windows 11
vstest version 17.800.23.46802

**Comment by jakubch1** [comment]
Please collect logs: https://github.com/microsoft/vstest/blob/main/docs/troubleshooting.md#visual-studio
You can also open report here: https://developercommunity.visualstudio.com/VisualStudio and provide privately your solution so we can reproduce it.

**Comment by ibiglari** [comment]
[logs.datacollector.24-01-11_18-46-07_32450_7.txt](https://github.com/microsoft/vstest/files/13899000/logs.datacollector.24-01-11_18-46-07_32450_7.txt)
[logs.txt](https://github.com/microsoft/vstest/files/13899001/logs.txt)
```
[1/11/2024 6:45:53.732 PM]  Log level is set to Trace (Includes Platform logs).
[1/11/2024 6:45:53.763 PM]  Logging Test Platform diagnostic logs under 'C:\Users\user\AppData\Local\Temp\TestPlatformLogs\2024_01_11_18_45_53_11904'
[1/11/2024 6:45:53.771 PM]  Connected to test environment '< Local Windows Environment >'
[1/11/2024 6:46:06.973 PM]  Interrupt: Enqueueing RunSelectedOperation
[1/11/2024 6:46:06.974 PM]  Enqueue operation 'RunSelectedOperation', hashcode:59538345 
[1/11/2024 6:46:06.974 PM]  Operation left in the the queue: 1
[1/11/2024 6:46:06.974 PM]  	'RunSelectedOperation', hashcode:59538345
[1/11/2024 6:46:06.974 PM]  

[1/11/2024 6:46:06.974 PM]  Operation Dequeue : 'RunSelectedOperation'
[1/11/2024 6:46:06.976 PM]  Building Test Projects
[1/11/2024 6:46:07.006 PM]  Update Test run progress to 0/100.
[1/11/2024 6:46:07.007 PM]  Triggering build for 1 IProjectBasedTestContainers.
[1/11/2024 6:46:07.108 PM]  No IBuildableTestContainers were found.
[1/11/2024 6:46:07.108 PM]  Completed building containers.
[1/11/2024 6:46:07.108 PM]  Start updating 1 containers.
[1/11/2024 6:46:07.108 PM]  Updating container C:\Users\user\source\repos\software\Debug\IntegrationTests.dll.
[1/11/2024 6:46:07.112 PM]  Completed updating containers.
[1/11/2024 6:46:07.137 PM]  Test run animation has started.
[1/11/2024 6:46:07.143 PM]  Test run progress has started.
[1/11/2024 6:46:07.188 PM]  ========== Starting test run ==========
[1/11/2024 6:46:07.191 PM]  Tests run settings for C:\Users\user\source\repos\software\Debug\IntegrationTests.dll:
 <RunSettings>
  <Catch2Adapter>
    <FilenameFilter>^EftsrvHQUnitTest</FilenameFilter>
  </Catch2Adapter>
  <BoostTestInternalSettings xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <VSProcessId>16144</VSProcessId>
  </BoostTestInternalSettings>
  <RunConfiguration>
    <ResultsDirectory>C:\Users\user\source\repos\software\TestResults</ResultsDirectory>
    <SolutionDirectory>C:\Users\user\source\repos\software\</SolutionDirectory>
    <TestAdaptersPaths>C:\Users\user\AppData\Local\FineCodeCoverage\msCodeCoverage\17.1.0\build\netstandard1.0</TestAdaptersPaths>
    <CollectSourceInformation>True</CollectSourceInformation>
  </RunConfiguration>
  <GoogleTestAdapterSettings xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <SolutionSettings>
      <Settings>
        <PrintTestOutput>false</PrintTestOutput>
        <TestDiscoveryRegex />
        <TestDiscoveryTimeoutInSeconds>30</TestDiscoveryTimeoutInSeconds>
        <WorkingDir>$(ExecutableDir)</WorkingDir>
        <PathExtension />
        <CatchExceptions>true</CatchExceptions>
        <BreakOnFailure>false</BreakOnFailure>
        <RunDisabledTests>false</RunDisabledTests>
        <NrOfTestRepetitions>1</NrOfTestRepetitions>
        <ShuffleTests>false</ShuffleTests>
        <ShuffleTestsSeed>0</ShuffleTestsSeed>
        <TraitsRegexesBefore />
        <TraitsRegexesAfter />
        <TestNameSeparator />
        <DebugMode>false</DebugMode>
        <TimestampOutput>false</TimestampOutput>
        <ShowReleaseNotes>false</ShowReleaseNotes>
        <ParseSymbolInformation>true</ParseSymbolInformation>
        <AdditionalTestDiscoveryParam />
        <AdditionalTestExecutionParam />
        <ParallelTestExecution>false</ParallelTestExecution>
        <MaxNrOfThreads>0</MaxNrOfThreads>
        <BatchForTestSetup />
        <BatchForTestTeardown />
        <KillProcessesOnCancel>false</KillProcessesOnCancel>
        <UseNewTestExecutionFramework>true</UseNewTestExecutionFramework>
        <DebuggingNamedPipeId>7b2d3d5e-95b0-45a4-ab16-f325e362c2c2</DebuggingNamedPipeId>
      </Settings>
    </SolutionSettings>
    <ProjectSettings />
  </GoogleTestAdapterSettings>
  <DataCollectionRunSettings>
    <DataCollectors>
      <DataCollector friendlyName="Code Coverage" enabled="true">
        <Configuration>
          <CodeCoverage>
            <ModulePaths>
              <Exclude>
              </Exclude>
              <Include>
              </Include>
            </ModulePaths>
            <Functions>
              <Exclude>
              </Exclude>
              <Include>
              </Include>
            </Functions>
            <Attributes>
              <Exclude>
              </Exclude>
              <Include>
              </Include>
            </Attributes>
            <Sources>
              <Exclude>
              </Exclude>
              <Include>
              </Include>
            </Sources>
            <CompanyNames>
              <Exclude>
              </Exclude>
              <Include>
              </Include>
            </CompanyNames>
            <PublicKeyTokens>
              <Exclude>
              </Exclude>
              <Include>
              </Include>
            </PublicKeyTokens>
          </CodeCoverage>
          <Format>Cobertura</Format>
          <FCCGenerated />
        </Configuration>
      </DataCollector>
    </DataCollectors>
  </DataCollectionRunSettings>
</RunSettings>.
[1/11/2024 6:46:11.668 PM] [Error] Testhost process for source(s) 'C:\Users\user\source\repos\software\Debug\IntegrationTests.dll' exited with error: Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.CodeCoverage.Shim, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
   at Microsoft.VisualStudio.TestPlatform.ObjectModel.EqtTrace.Error(String format, Object[] args)
   at Microsoft.VisualStudio.TestPlatform.TestHost.Program.Main(String[] args) in /_/src/testhost.x86/Program.cs:line 41
. Please check the diagnostic logs for more information.
[1/11/2024 6:46:11.669 PM] [Error] Testhost process for source(s) 'C:\Users\user\source\repos\software\Debug\IntegrationTests.dll' exited with error: Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.CodeCoverage.Shim, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
   at Microsoft.VisualStudio.TestPlatform.ObjectModel.EqtTrace.Error(String format, Object[] args)
   at Microsoft.VisualStudio.TestPlatform.TestHost.Program.Main(String[] args) in /_/src/testhost.x86/Program.cs:line 41
. Please check the diagnostic logs for more information.
[1/11/2024 6:46:11.713 PM]  Attachments processing not needed
[1/11/2024 6:46:11.715 PM]  ========== Test run aborted: 0 Tests (0 Passed, 0 Failed, 0 Skipped) run in < 1 ms ==========
[1/11/2024 6:46:11.827 PM]  Update Test run progress to 100/100.
[1/11/2024 6:46:12.409 PM]  Test run animation has stopped.
[1/11/2024 6:46:12.424 PM]  Test run progress has stopped.

```

**Comment by ibiglari** [comment]
Unfortunately I cannot provide the solution as it is my employer's IP. I will try to create a new minimal application and test suit to reproduce the issue, but it might take a little bit of time.

**Comment by jakubch1** [comment]
From logs I can see you have code coverage enabled:

```
<DataCollector friendlyName="Code Coverage" enabled="true">
        <Configuration>
          <CodeCoverage>
            <ModulePaths>
              <Exclude>
              </Exclude>
              <Include>
              </Include>
            </ModulePaths>
            <Functions>
              <Exclude>
              </Exclude>
              <Include>
              </Include>
            </Functions>
            <Attributes>
              <Exclude>
              </Exclude>
              <Include>
              </Include>
            </Attributes>
            <Sources>
              <Exclude>
              </Exclude>
              <Include>
              </Include>
            </Sources>
            <CompanyNames>
              <Exclude>
              </Exclude>
              <Include>
              </Include>
            </CompanyNames>
            <PublicKeyTokens>
              <Exclude>
              </Exclude>
              <Include>
              </Include>
            </PublicKeyTokens>
          </CodeCoverage>
          <Format>Cobertura</Format>
          <FCCGenerated />
        </Configuration>
      </DataCollector>
```

`<FCCGenerated />` suggests that those settings are generated by FineCodeCoverage extension. I suggests to open issue on this repo and ask them to generate settings with: `<UseVerifiableInstrumentation>False</UseVerifiableInstrumentation>`. From our point of view all is good as code coverage is not part of VS Professional so `Microsoft.VisualStudio.CodeCoverage.Shim` is not available.
