### ISSUE TITLE
VSTest target should be bound by a condition

### ISSUE THREAD

**Issue by carlossanlop** [microsoft/vstest#4953]
## Description

When running the dotnet/maintenance-packages tests using `dotnet test`, we expect some tests to be excluded from executing because the `SkipTests` property is set to `true` for those cases. Unfortunately, the `VSTest` target ignores it completely and executes regardless because it does not check for any customer-set conditions.

It would be nice if `VSTest` had a condition added so that it does not get executed when the user does not want it executed. For example, if `SkipTests` is set to `true`.

https://github.com/microsoft/vstest/blob/1c07d46672669b0f7e4a367d66ab9ef9ed6cdb4b/src/Microsoft.TestPlatform.Build/Microsoft.TestPlatform.targets#L30

## Steps to reproduce

We found this problem when testing this PR in a local Ubuntu machine: https://github.com/dotnet/maintenance-packages/pull/59

The test assembly added in that PR has net462 as the sole target framework. The tests should be skipped when using that TFM  and the OS is not Windows_NT (via the `SkipTests` property being set to `true`). In that repo, SkipTests is set in Directory.Build.targets.

VSTest ignores it and attempts to run anyway, which fails because there is no mono installation (and we don't want to install one).
## Expected behavior

VSTest should respect SkipTests or some other properly named property that the user can set.

## Actual behavior

Here's the output when running the tests in an Ubuntu local machine using `dotnet test`:

```
$ dotnet test src/System.Runtime.CompilerServices.Unsafe/tests/System.Runtime.CompilerServices.Unsafe.Tests.csproj 
  Determining projects to restore...
  All projects are up-to-date for restore.
  System.Runtime.CompilerServices.Unsafe -> /home/carlos/maintenance-packages/artifacts/bin/System.Runtime.CompilerServices.Unsafe/Debug/net462/System.Runtime.CompilerServices.Unsafe.dll
  System.Runtime.CompilerServices.Unsafe.Tests -> /home/carlos/maintenance-packages/artifacts/bin/System.Runtime.CompilerServices.Unsafe.Tests/Debug/net462/System.Runtime.CompilerServices.Unsafe.Tests.dll
Test run for /home/carlos/maintenance-packages/artifacts/bin/System.Runtime.CompilerServices.Unsafe.Tests/Debug/net462/System.Runtime.CompilerServices.Unsafe.Tests.dll (.NETFramework,Version=v4.6.2)
Microsoft (R) Test Execution Command Line Tool Version 17.8.0 (x64)
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
System.IO.FileNotFoundException: Could not find 'mono' host. Make sure that 'mono' is installed on the machine and is available in PATH environment variable.
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Helpers.DotnetHostHelper.GetMonoPath() in /_/src/Microsoft.TestPlatform.CoreUtilities/Helpers/DotnetHostHelper.cs:line 93
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DefaultTestHostManager.GetTestHostProcessStartInfo(IEnumerable`1 sources, IDictionary`2 environmentVariables, TestRunnerConnectionInfo connectionInfo) in /_/src/Microsoft.TestPlatform.TestHostProvider/Hosting/DefaultTestHostManager.cs:line 217
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, String runSettings) in /_/src/Microsoft.TestPlatform.CrossPlatEngine/Client/ProxyOperationManager.cs:line 226
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyExecutionManager.InitializeTestRun(TestRunCriteria testRunCriteria, IInternalTestRunEventsHandler eventHandler) in /_/src/Microsoft.TestPlatform.CrossPlatEngine/Client/ProxyExecutionManager.cs:line 182
WARNING: Overwriting results file: /home/carlos/maintenance-packages/artifacts/TestResults/Debug/System.Runtime.CompilerServices.Unsafe.Tests_net462_x64.trx
Results File: /home/carlos/maintenance-packages/artifacts/TestResults/Debug/System.Runtime.CompilerServices.Unsafe.Tests_net462_x64.trx
Html test results file : /home/carlos/maintenance-packages/artifacts/TestResults/Debug/System.Runtime.CompilerServices.Unsafe.Tests_net462_x64.html

Test Run Aborted.
```

## Diagnostic logs

Here's the binlog. The assembly name is System.Runtime.CompilerServices.Unsafe, so I named the zip file Unsafe.zip, don't get scared:
[Unsafe.zip](https://github.com/microsoft/vstest/files/14796580/Unsafe.zip)

## Environment

```
$ uname -a
Linux CALOPEPC2 5.15.146.1-microsoft-standard-WSL2 #1 SMP Thu Jan 11 04:09:03 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.4 LTS
Release:        22.04
Codename:       jammy
```
```
$ dotnet --info
.NET SDK:
 Version:           8.0.101
 Commit:            6eceda187b
 Workload version:  8.0.100-manifests.69afb982

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /home/carlos/.dotnet/sdk/8.0.101/

.NET workloads installed:
 Workload version: 8.0.100-manifests.69afb982
There are no installed workloads to display.

Host:
  Version:      8.0.1
  Architecture: x64
  Commit:       bf5e279d92

.NET SDKs installed:
  6.0.418 [/home/carlos/.dotnet/sdk]
  7.0.100 [/home/carlos/.dotnet/sdk]
  8.0.101 [/home/carlos/.dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.26 [/home/carlos/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0 [/home/carlos/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.1 [/home/carlos/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.26 [/home/carlos/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0 [/home/carlos/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.1 [/home/carlos/.dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  /home/carlos/maintenance-packages/global.json

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by carlossanlop** [comment]
cc @ViktorHofer @ericstj @akoeplinger

**Comment by ericstj** [comment]
One note about above - a fix for this should work if the project sets `SkipTests` in the outer build or in a subset of inner builds.  So a project can choose to disable just one target of many TargetFrameworks or all and should also work for non-multi-targeting projects.

**Comment by nohwnd** [comment]
VSTest already checks `IsTestProject` property, setting it to false will skip the test project.

https://github.com/microsoft/vstest/blob/main/src/Microsoft.TestPlatform.Build/Microsoft.TestPlatform.targets#L109
