### ISSUE TITLE
`VsTestConsoleWrapper` failed to initialize with `LogFilePath` set for .NET Core test projects

### ISSUE THREAD

**Issue by genlu** [Microsoft/vstest#734]
## Description
Creating a `VsTestConsoleWrapper` with `LogFilePath` set will throw exception for .NET core test project.
This was found in dogfooding LiveUnitTesting.

```
Microsoft.TestPlatform.VsTestConsole.TranslationLayer.TransationLayerException: Error connecting to Vstest Command Line
   at Microsoft.TestPlatform.VsTestConsole.TranslationLayer.VsTestConsoleWrapper.EnsureInitialized()
   at Microsoft.TestPlatform.VsTestConsole.TranslationLayer.VsTestConsoleWrapper.InitializeExtensions(IEnumerable`1 pathToAdditionalExtensions)
   at Microsoft.CodeAnalysis.LiveUnitTesting.TestDriver.CreateVsTestConsoleWrapper(String vsTestConsolePath, IEnumerable`1 vsTestAdapterPaths, String logFilePath)
   at Microsoft.CodeAnalysis.LiveUnitTesting.TestDriver.<>c__DisplayClass35_0.<CreateVsTestConsoleWrapperPool>b__0(Int32 index)
   at Microsoft.CodeAnalysis.LiveUnitTesting.TestExecution.ResourcePool`1..ctor(Func`2 createResource, Action`1 destroyResource, Int32 count)
   at Microsoft.CodeAnalysis.LiveUnitTesting.TestDriver.CreateVsTestConsoleWrapperPool(String vsTestConsolePath, IEnumerable`1 vsTestAdapterPaths, String workDirectoryPath, Int32 count, Logger logger)
   at Microsoft.CodeAnalysis.LiveUnitTesting.TestDriver.<>c__DisplayClass34_0.<.ctor>b__1()
   at Microsoft.CodeAnalysis.LiveUnitTesting.TestDriver.<>c.<.ctor>b__34_0(Action action)
   at Microsoft.CodeAnalysis.LiveUnitTesting.Threading.EventPump`1.ProcessEvent(T enqueuedEvent)
```

## Steps to reproduce
1. Install latest LiveUnitTesting dogfooding build.
2. Set environmental variable `LiveUnitTesting_TestPlatformLog` to `1`.
3. Create a .NET Core Unit Test Project in VS 2017.
4. Start LiveUnitTesting

You should be able to repro w/o LUT, we simply use the following API to create a wrapper, and then call `InitializeExtensions`.
```cs
public VsTestConsoleWrapper(string vstestConsolePath, ConsoleParameters consoleParameters)
```

## Expected behavior
Test should run and pass.

## Actual behavior
See exception above.

## Environment
VS2017 26417.0 internal preview - dogfood

@Microsoft/testimpact

**Comment by ManishJayaswal** [comment]
@codito @sbaid - FYI

**Comment by Faizan2304** [comment]
Fixed!!

**Comment by ManishJayaswal** [comment]
thanks!
