### ISSUE TITLE
running netcoreapp2.0 test in container: Could not find testhost.dll

### ISSUE THREAD

**Issue by tmds** [Microsoft/vstest#761]
I am trying to run a netcoreapp2.0 xunit project.
I have installed the `2.0.0-preview1-005783` cli.

I create a `dotnet new xunit` project and adjust the NuGet.Config file and csproj file to use the `15.1.0-preview-20170414-10` Sdk.

When I run this on a RHEL7 machine, tests are discovered.
When I run this in a RHEL7 container, I get a message:

> Could not find testhost.dll for source '/tmp/test/bin/Debug/netcoreapp2.0/test1.dll'. Make sure test project has a nuget reference of package "microsoft.testplatform.testhost".

In the container, the restore completes successfully and contained this line:
```
  Installing Microsoft.TestPlatform.TestHost 15.1.0-preview-20170414-10.
```

When I manually start the vstest.console in the container and set the logging verbosity to normal the error message changes:

```
$ dotnet exec /opt/dotnet/sdk/2.0.0-preview1-005783/vstest.console.dll --framework:.NETCoreApp,Version=v2.0 --logger:console;verbosity=normal  /tmp/testapp/bin/Debug/netcoreapp2.0/testapp.dll
```

> No test source files were specified.

dotnet info:
```
$ dotnet --info
.NET Command Line Tools (2.0.0-preview1-005783)

Product Information:
 Version:            2.0.0-preview1-005783
 Commit SHA-1 hash:  8bd15c7ec0

Runtime Environment:
 OS Name:     rhel
 OS Version:  7
 OS Platform: Linux
 RID:         rhel.7-x64
 Base Path:   /opt/dotnet/sdk/2.0.0-preview1-005783/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview1-001961-00
  Build    : 884c69a4ac461a5e1fad31f60f2e01871371c288
```

cc @smadala

**Comment by smadala** [comment]
@tmds Can you please check `microsoft.testplatform.testhost` exists in values specified for additionalProbingPaths in bin/Debug/netcoreapp2.0/<test_project_name>.runtimeconfig.dev.json.

> $ dotnet exec /opt/dotnet/sdk/2.0.0-preview1-005783/vstest.console.dll --framework:.NETCoreApp,Version=v2.0 --logger:console;verbosity=normal  /tmp/testapp/bin/Debug/netcoreapp2.0/testapp.dll

Add `"` to logger value like following: `--logger:"console;verbosity=normal"`

**Comment by codito** [comment]
Diagnostics output will help. It can be enabled with `dotnet test -d:log.txt`, it will generate `log.*.txt` files with additional information.

**Comment by tmds** [comment]
@singhsarab the runtime.dev.config has additionalProbingPaths `.nuget/packages` and `.dotnet/NuGetFallbackFolder`.
Under the .nuget folder, there is a testhost.dll at `microsoft.testplatform.testhost/15.0.0/lib/netstandard1.5/testhost.dll` and at `microsoft.testplatform.testhost/15.1.0-preview-20170414-10/lib/netstandard1.5/testhost.dll`.

When I add `"` back to the logger, I get back the first error message.

log.txt:
```
TpTrace Information: 0 : 315, 2, 2017/04/26, 16:00:44.641, 32091198984743, vstest.console.dll, Using .Net Framework version:.NETCoreApp,Version=v2.0
TpTrace Verbose: 0 : 315, 2, 2017/04/26, 16:00:44.660, 32091214567345, vstest.console.dll, TestPluginCache: Discovering the extensions using extension path.
TpTrace Information: 0 : 315, 2, 2017/04/26, 16:00:44.709, 32091263223260, vstest.console.dll, AssemblyResolver: Microsoft.VisualStudio.TestPlatform.Extensions.TrxLogger: Resolving assembly.
TpTrace Information: 0 : 315, 2, 2017/04/26, 16:00:44.710, 32091263978065, vstest.console.dll, AssemblyResolver: Microsoft.VisualStudio.TestPlatform.Extensions.TrxLogger: Resolved assembly. 
TpTrace Verbose: 0 : 315, 2, 2017/04/26, 16:00:44.712, 32091265872269, vstest.console.dll, TestPluginCache: Discovered the extensions using extension path ''.
TpTrace Verbose: 0 : 315, 2, 2017/04/26, 16:00:44.712, 32091266124297, vstest.console.dll, TestPluginCache: Discoverers are ''.
TpTrace Verbose: 0 : 315, 2, 2017/04/26, 16:00:44.712, 32091266251543, vstest.console.dll, TestPluginCache: Executors are ''.
TpTrace Verbose: 0 : 315, 2, 2017/04/26, 16:00:44.712, 32091266380043, vstest.console.dll, TestPluginCache: Setting providers are ''.
TpTrace Verbose: 0 : 315, 2, 2017/04/26, 16:00:44.712, 32091266500473, vstest.console.dll, TestPluginCache: Loggers are 'logger://Microsoft/TestPlatform/TrxLogger/v2'.
TpTrace Information: 0 : 315, 2, 2017/04/26, 16:00:44.720, 32091274549034, vstest.console.dll, RunTestsArgumentProcessor:Execute: Test run is starting.
TpTrace Verbose: 0 : 315, 2, 2017/04/26, 16:00:44.721, 32091274818844, vstest.console.dll, RunTestsArgumentProcessor:Execute: Queuing Test run.
TpTrace Information: 0 : 315, 2, 2017/04/26, 16:00:44.721, 32091275101787, vstest.console.dll, TestRequestManager.RunTests: run tests started.
TpTrace Verbose: 0 : 315, 2, 2017/04/26, 16:00:44.730, 32091283637579, vstest.console.dll, TestEngine: Initializing Parallel Execution as MaxCpuCount is set to: 1
TpTrace Verbose: 0 : 315, 2, 2017/04/26, 16:00:44.739, 32091293460369, vstest.console.dll, TestRunRequest.ExecuteAsync: Creating test run request.
TpTrace Verbose: 0 : 315, 2, 2017/04/26, 16:00:44.740, 32091294395877, vstest.console.dll, TestRunRequest.ExecuteAsync: Starting.
TpTrace Information: 0 : 315, 2, 2017/04/26, 16:00:44.741, 32091294741090, vstest.console.dll, TestRunRequest.ExecuteAsync: Starting run with settings:TestRunCriteria:
   KeepAlive=False,FrequencyOfRunStatsChangeEvent=10,RunStatsChangeEventTimeout=00:00:01.5000000,TestCaseFilter=,TestExecutorLauncher=
   Settingsxml=<?xml version="1.0" encoding="utf-16"?>
<RunSettings>
  <RunConfiguration>
    <ResultsDirectory>/tmp/testapp/TestResults</ResultsDirectory>
    <TargetPlatform>X86</TargetPlatform>
    <TargetFrameworkVersion>.NETCoreApp,Version=v2.0</TargetFrameworkVersion>
  </RunConfiguration>
</RunSettings>

TpTrace Verbose: 0 : 315, 2, 2017/04/26, 16:00:44.741, 32091294865832, vstest.console.dll, TestRunRequest.ExecuteAsync: Wait for the first run request is over.
TpTrace Information: 0 : 315, 2, 2017/04/26, 16:00:44.742, 32091296599756, vstest.console.dll, TestRunRequest.ExecuteAsync: Started.
TpTrace Verbose: 0 : 315, 2, 2017/04/26, 16:00:44.743, 32091296993387, vstest.console.dll, TestRunRequest.WaitForCompletion: Waiting with timeout -1.
TpTrace Information: 0 : 315, 4, 2017/04/26, 16:00:44.743, 32091297402996, vstest.console.dll, ProxyParallelExecutionManager: Triggering test run for next source: /tmp/testapp/bin/Debug/netcoreapp2.0/testapp.dll
TpTrace Verbose: 0 : 315, 4, 2017/04/26, 16:00:44.744, 32091297796622, vstest.console.dll, ProxyExecutionManager: Test host is non shared. Lazy initialize.
TpTrace Information: 0 : 315, 4, 2017/04/26, 16:00:44.789, 32091343198990, vstest.console.dll, Listening on port : 59034
TpTrace Verbose: 0 : 315, 4, 2017/04/26, 16:00:44.814, 32091368171773, vstest.console.dll, DotnetTestHostmanager: Full path of dotnet.exe is /opt/dotnet/dotnet
TpTrace Verbose: 0 : 315, 4, 2017/04/26, 16:00:44.814, 32091368531637, vstest.console.dll, DotnetTestHostmanager: Adding  --runtimeconfig "/tmp/testapp/bin/Debug/netcoreapp2.0/testapp.runtimeconfig.json" in args
TpTrace Verbose: 0 : 315, 4, 2017/04/26, 16:00:44.815, 32091368638328, vstest.console.dll, DotnetTestHostmanager: Adding  --depsfile "/tmp/testapp/bin/Debug/netcoreapp2.0/testapp.deps.json" in args
TpTrace Verbose: 0 : 315, 4, 2017/04/26, 16:00:44.815, 32091369177871, vstest.console.dll, DotnetTestHostmanager: Reading file /tmp/testapp/bin/Debug/netcoreapp2.0/testapp.deps.json to get path of testhost.dll
TpTrace Verbose: 0 : 315, 4, 2017/04/26, 16:00:44.882, 32091436557271, vstest.console.dll, DotnetTestHostmanager: Looking for path  in folder /opt/app-root/.nuget/packages
TpTrace Verbose: 0 : 315, 4, 2017/04/26, 16:00:44.883, 32091436783195, vstest.console.dll, DotnetTestHostmanager: Looking for path  in folder /opt/app-root/.dotnet/NuGetFallbackFolder
TpTrace Verbose: 0 : 315, 4, 2017/04/26, 16:00:44.883, 32091436932663, vstest.console.dll, DotnetTestHostManager: Assume published test project, with test host path = /tmp/testapp/bin/Debug/netcoreapp2.0/testhost.dll.
TpTrace Information: 0 : 315, 4, 2017/04/26, 16:00:44.883, 32091437300685, vstest.console.dll, AssemblyResolver: Microsoft.TestPlatform.CrossPlatEngine.resources: Resolving assembly.
TpTrace Information: 0 : 315, 4, 2017/04/26, 16:00:44.884, 32091438027129, vstest.console.dll, AssemblyResolver: Microsoft.TestPlatform.CrossPlatEngine.resources: Resolving assembly.
TpTrace Information: 0 : 315, 4, 2017/04/26, 16:00:44.884, 32091438318168, vstest.console.dll, AssemblyResolver: Microsoft.TestPlatform.CrossPlatEngine.resources: Resolving assembly.
TpTrace Verbose: 0 : 315, 4, 2017/04/26, 16:00:44.884, 32091438563115, vstest.console.dll, DotnetTestHostmanager: Could not find testhost.dll for source '/tmp/testapp/bin/Debug/netcoreapp2.0/testapp.dll'. Make sure test project has a nuget reference of package "microsoft.testplatform.testhost".
TpTrace Error: 0 : 315, 4, 2017/04/26, 16:00:44.886, 32091439925255, vstest.console.dll, ProxyExecutionManager.StartTestRun: Failed to start test run: System.IO.FileNotFoundException: Could not find testhost.dll for source '/tmp/testapp/bin/Debug/netcoreapp2.0/testapp.dll'. Make sure test project has a nuget reference of package "microsoft.testplatform.testhost".
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DotnetTestHostManager.GetTestHostProcessStartInfo(IEnumerable`1 sources, IDictionary`2 environmentVariables, TestRunnerConnectionInfo connectionInfo)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyExecutionManager.InitializeExtensions(IEnumerable`1 sources)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyExecutionManager.StartTestRun(TestRunCriteria testRunCriteria, ITestRunEventsHandler eventHandler)
TpTrace Verbose: 0 : 315, 4, 2017/04/26, 16:00:44.886, 32091440268879, vstest.console.dll, TestRunRequest:SendTestRunMessage: Starting.
TpTrace Information: 0 : 315, 4, 2017/04/26, 16:00:44.887, 32091440736885, vstest.console.dll, TestRunRequest:SendTestRunMessage: Completed.
TpTrace Verbose: 0 : 315, 4, 2017/04/26, 16:00:45.069, 32091622920968, vstest.console.dll, TestRunRequest:TestRunComplete: Starting. IsAborted:False IsCanceled:False.
TpTrace Information: 0 : 315, 4, 2017/04/26, 16:00:45.071, 32091625097717, vstest.console.dll, TestRunRequest:TestRunComplete: Completed.
TpTrace Verbose: 0 : 315, 2, 2017/04/26, 16:00:45.071, 32091625502572, vstest.console.dll, TestRunRequest.Dispose: Starting.
TpTrace Information: 0 : 315, 2, 2017/04/26, 16:00:45.072, 32091625638016, vstest.console.dll, TestRunRequest.Dispose: Completed.
TpTrace Information: 0 : 315, 2, 2017/04/26, 16:00:45.072, 32091625733266, vstest.console.dll, TestRequestManager.RunTests: run tests completed, sucessful: True.
TpTrace Information: 0 : 315, 2, 2017/04/26, 16:00:45.072, 32091625814728, vstest.console.dll, RunTestsArgumentProcessor:Execute: Test run is completed.
TpTrace Verbose: 0 : 315, 2, 2017/04/26, 16:00:45.072, 32091625922290, vstest.console.dll, Executor.Execute: Exiting with exit code of 1
```

This line is interesting:
```
Looking for path  in folder /opt/app-root/.nuget/packages
```
The path is empty.

**Comment by smadala** [comment]
@tmds Are you saying `/opt/app-root/.nuget/packages` is empty? 
What is full path  for `microsoft.testplatform.testhost/15.1.0-preview-20170414-10/lib/netstandard1.5/testhost.dll`?

**Comment by tmds** [comment]
> @tmds Are you saying /opt/app-root/.nuget/packages is empty?

No, there are two packages there:  testhost.dll at `microsoft.testplatform.testhost/15.0.0/lib/netstandard1.5/testhost.dll` and at `microsoft.testplatform.testhost/15.1.0-preview-20170414-10/lib/netstandard1.5/testhost.dll`.

The path is empty in this line in the log file:

>Looking for path  in folder /opt/app-root/.nuget/packages

**Comment by Faizan2304** [comment]
@tmds : Can you please share the csproj file of your test project.

**Comment by tmds** [comment]
@Faizan2304 Yes, those are the exact steps.

I don't think the problem is with the files since they work when not running in a container.

Do you have an idea why there is an empty path here: `Looking for path <empty_string> in folder /opt/app-root/.nuget/packages`?

**Comment by codito** [comment]
The empty path message is coming from https://github.com/Microsoft/vstest/blob/master/src/Microsoft.TestPlatform.TestHostProvider/Hosting/DotnetTestHostManager.cs#L317.

For some reason vstest is unable to find testhost.dll from `testapp.deps.json`. Is it possible to share the deps json from container? We can compare the file generated in regular scenario v/s RHEL container to find what's going on.

**Comment by tmds** [comment]
@codito https://pastebin.com/Zb0Chi76

When I diff this with the working deps, it doesn't show a difference...

I checked the log.txt for the working case, that doesn't have an empty path.

**Comment by tmds** [comment]
I figured out the difference...
When I change LANG from C.UTF-8:
```
export LANG=en_US.UTF-8
```
it is working...

Probably this changes the behavior of this check:
```
var testhostPackage = context.RuntimeLibraries.Where(lib => lib.Name.Equals(testHostPackageName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault(); 
```

**Comment by tmds** [comment]
Using `StringComparison.OrdinalIgnoreCase` should fix the issue.

**Comment by Faizan2304** [comment]
@tmds : Thank you very much for your contribution. 👍

**Comment by tmds** [comment]
@Faizan2304 no problem. Will this be included in the .NET Core 2.0.0 preview?

**Comment by tmds** [comment]
@Faizan2304 @smadala @codito I am trying this again using 15.3.0-preview-20170502-02. Unfortunately I hit the same error.

> Could not find testhost.dll for source '/opt/app-root/src/test/test1/bin/Debug/netcoreapp2.0/test1.dll'. Make sure test project has a nuget reference of package "microsoft.testplatform.testhost".

I assume this is a daily build which should include the fix. Is that correct?

**Comment by tmds** [comment]
Ah. I think this is packed as the vstest.console.dll in the cli. So probably this has not been updated yet?

**Comment by smadala** [comment]
@tmds Yes you are right, It is yet to update. You can track next insertion [here](https://github.com/dotnet/cli/pull/6420), Tentatively insertion will be completed by EOD tomorrow.

**Comment by tmds** [comment]
@smadala I want to be sure this in the 2.0 preview release, so I am trying this out with the daily.
Today using the `2.0.0-preview2-005905` SDK, I still hit the issue. Perhaps I should use a different version? Or wait another couple of days?

```
$ dotnet test
...
No test is available in /tmp/testapp/bin/Debug/netcoreapp2.0/testapp.dll. Make sure test project has a nuget reference of package "Microsoft.NET.Test.Sdk" and framework version settings are appropriate and try again.
...
$ LANG=en_US.UTF-8 dotnet test
...
Test Run Successful.
...
```

**Comment by smadala** [comment]
@tmds Changes are in [release/2.0.0 - 2.0.0-preview1-005945](https://github.com/dotnet/cli/tree/release/2.0.0#installers-and-binaries). We will cherry-pick the insertion commit to master.

**Comment by WilliamT-Streamba** [comment]
Anyone struggling with this issue in 2019, .Net Core 2.2 and XUnit and running tests in docker.

I had updated `Microsoft.NET.Test.Sdk` to 16.4.0 but didn't update `xunit` and `xunit.runner.visualstudio` to the latest version 2.4.1.

Updating the xunit packages resolved the issue for me.
