### ISSUE TITLE
VsTestConsoleWrapper doesn't work with Microsoft.TestPlatform.CLI

### ISSUE THREAD

**Issue by yaakov-h** [Microsoft/vstest#808]
## Description
In lieu of #702, I'm attempting to build a small program to lists tests and run a select subset. In doing so, it appears that there is a mismatch between `Microsoft.TestPlatform.VsTestConsole.TranslationLayer.VsTestConsoleProcessManager` and `Microsoft.TestPlatform.CLI`

## Steps to reproduce
1. Restore the NuGet package `Microsoft.TestPlatform.CLI` version 15.0.0 to `C:\Temp\VSTest\Microsoft.TestPlatform.CLI.15.0.0`
2. Run the following code example on .NET Framework 4.6, with a NuGet reference to `Microsoft.TestPlatform.VsTestConsole.TranslationLayer`

```
using System;
using System.Collections.Generic;
using System.IO;
using Microsoft.TestPlatform.VsTestConsole.TranslationLayer;
using Microsoft.VisualStudio.TestPlatform.ObjectModel;
using Microsoft.VisualStudio.TestPlatform.ObjectModel.Client;
using Microsoft.VisualStudio.TestPlatform.ObjectModel.Logging;

namespace VSTest
{
	class Program
	{
		static void Main(string[] args)
		{
			var vstestConsolePath = @"C:\temp\VSTest\packages\Microsoft.TestPlatform.CLI.15.0.0\contentFiles\any\any\TestHost\testhost.exe";
			var consoleParameters = new ConsoleParameters
			{
				LogFilePath = Path.Combine(Environment.CurrentDirectory, $"VSTestLog_{DateTime.Now:yyyyMMdd-HHmmss}.log")
			};
			var wrapper = new VsTestConsoleWrapper(vstestConsolePath, consoleParameters);

			var source = @"C:\Temp\ExampleXUnitTestProject\ExampleXUnitTestProject\bin\Debug\netcoreapp1.1\ExampleXUnitTestProject.dll";
			var sources = new[] { source };
			var discoverySettings = default(string);

			wrapper.DiscoverTests(sources, discoverySettings, new TestDiscoveryEventsHandler());
		}

		class TestDiscoveryEventsHandler : ITestDiscoveryEventsHandler
		{
			public void HandleDiscoveredTests(IEnumerable<TestCase> discoveredTestCases)
			{
				foreach (var testCase in discoveredTestCases)
				{
					Console.WriteLine($"Discovered test case: {testCase.FullyQualifiedName}");
				}
			}

			public void HandleDiscoveryComplete(long totalTests, IEnumerable<TestCase> lastChunk, bool isAborted)
			{
				Console.WriteLine("Discovery completed.");
			}

			public void HandleLogMessage(TestMessageLevel level, string message)
			{
				Console.WriteLine($"Log message: [{level}] {message}");
			}

			public void HandleRawMessage(string rawMessage)
			{
				Console.WriteLine($"Raw message: {rawMessage}");
			}
		}
	}
}
```

## Expected behavior
Some output is printed to the console.

## Actual behavior
After a 30-second timeout, the following exception is thrown:

```
Microsoft.TestPlatform.VsTestConsole.TranslationLayer.TransationLayerException occurred
  HResult=0x80131500
  Message=Error connecting to Vstest Command Line
  Source=Microsoft.TestPlatform.VsTestConsole.TranslationLayer
  StackTrace:
   at Microsoft.TestPlatform.VsTestConsole.TranslationLayer.VsTestConsoleWrapper.EnsureInitialized()
   at Microsoft.TestPlatform.VsTestConsole.TranslationLayer.VsTestConsoleWrapper.DiscoverTests(IEnumerable`1 sources, String discoverySettings, ITestDiscoveryEventsHandler discoveryEventsHandler)
   at VSTest.Program.Main(String[] args) in C:\temp\VSTest\VSTest\Program.cs:line 26
```

## Environment
Microsoft Windows 10 v1703 (10.0.15063.296)
Microsoft Visual Studio 2017 15.1.26403.7

---

It appears that [`VsTestConsoleWrapper`](https://github.com/Microsoft/vstest/blob/master/src/Microsoft.TestPlatform.VsTestConsole.TranslationLayer/VsTestConsoleWrapper.cs) uses command-line arguments of the form `/switch:value`, whereas [`testhost.exe`](https://github.com/Microsoft/vstest/blob/master/src/testhost.x86/Program.cs#L54) and [`vstest.console.exe`](https://github.com/Microsoft/vstest/blob/master/src/vstest.console/CommandLine/Executor.cs#L164) expect command-line arguments of the form `--switch value`.

Am I going about this in completely the wrong direction, and should be doing something else entirely, or is this indeed the correct path and it just doesn't quite work right?

**Comment by smadala** [comment]
@yaakov-h Restore Microsoft.TestPlatform package,  you should assign value for `vstestConsolePath` from "...\Microsoft.TestPlatform.15.0.0\tools\net46\vstest.console.exe". [Program.cs](https://github.com/Microsoft/vstest/blob/master/samples/Microsoft.TestPlatform.TranslationLayer.E2ETest/Program.cs) may help you.

**Comment by yaakov-h** [comment]
`Microsoft.TestPlatform`, as a package unto itself, doesn't appear to exist.

https://www.nuget.org/packages?q=Microsoft.testplatform

**Comment by smadala** [comment]
@yaakov-h Yeah, you are right, I don't know exact reason why it wasn't published to nuget.org.Can you please use source https://dotnet.myget.org/F/vstest/api/v3/index.json for workaround.

**Comment by yaakov-h** [comment]
Thanks, making progress. I now get a different exception:

```
System.ArgumentNullException occurred
  HResult=0x80004003
  Message=Value cannot be null.
  Source=Newtonsoft.Json
  StackTrace:
   at Newtonsoft.Json.Linq.JToken.FromObjectInternal(Object o, JsonSerializer jsonSerializer)
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.JsonDataSerializer.SerializePayload(String messageType, Object payload)
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.SocketCommunicationManager.SendMessage(String messageType, Object payload)
   at Microsoft.TestPlatform.VsTestConsole.TranslationLayer.VsTestConsoleRequestSender.InitializeExtensions(IEnumerable`1 pathToAdditionalExtensions)
   at Microsoft.TestPlatform.VsTestConsole.TranslationLayer.VsTestConsoleWrapper.EnsureInitialized()
   at Microsoft.TestPlatform.VsTestConsole.TranslationLayer.VsTestConsoleWrapper.DiscoverTests(IEnumerable`1 sources, String discoverySettings, ITestDiscoveryEventsHandler discoveryEventsHandler)
   at VSTest.Program.Main(String[] args) in C:\Temp\VSTest\VSTest\Program.cs:line 29
```

**Comment by smadala** [comment]
Did you can call `wrapper.StartSession()`: Starts vstest.console and `wrapper.InitializeExtensions()`: Initializes test adapter? [Example](https://github.com/Microsoft/vstest/blob/master/samples/Microsoft.TestPlatform.TranslationLayer.E2ETest/Program.cs#L62).

**Comment by yaakov-h** [comment]
EnsureInitialized calls StartSession and InitializeExtensions internally. So I have to call it separately, too?

**Comment by yaakov-h** [comment]
OK so that seems to work - calling `wrapper.StartSession()` before `wrapper.InitializeExtensions(...)` does fix the problem.

Unfortunately it doesn't seem to like the test adapter assembly:

```
TpTrace Information: 0 : 4748, 8, 2017/05/14, 19:20:35.863, 332220920875, testhost.x86.exe, AssemblyResolver: xunit.runner.visualstudio.dotnetcore.testadapter: Resolving assembly.
TpTrace Information: 0 : 4748, 8, 2017/05/14, 19:20:35.864, 332220925396, testhost.x86.exe, AssemblyResolver: xunit.runner.visualstudio.dotnetcore.testadapter: Resolved assembly. 
TpTrace Warning: 0 : 4748, 8, 2017/05/14, 19:20:35.866, 332220931053, testhost.x86.exe, TestPluginDiscoverer: Failed to get types from assembly 'xunit.runner.visualstudio.dotnetcore.testadapter, Version=2.2.0.1274, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c'.  Skipping test extension scan for this assembly.  Error: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at Microsoft.VisualStudio.TestPlatform.Common.ExtensionFramework.TestPluginDiscoverer.GetTestExtensionsFromAssembly(Assembly assembly, Dictionary`2 testDiscoverers, Dictionary`2 testExecutors, Dictionary`2 testSettingsProviders, Dictionary`2 testLoggers)
TpTrace Warning: 0 : 4748, 8, 2017/05/14, 19:20:35.866, 332220931359, testhost.x86.exe, LoaderExceptions: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Microsoft.VisualStudio.TestPlatform.Common.ExtensionFramework.TestPluginCache.CurrentDomainAssemblyResolve(Object sender, ResolveEventArgs args)
   at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)

...

TpTrace Warning: 0 : 4748, 8, 2017/05/14, 19:20:35.866, 332220933730, testhost.x86.exe, LoaderExceptions: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Microsoft.VisualStudio.TestPlatform.Common.ExtensionFramework.TestPluginCache.CurrentDomainAssemblyResolve(Object sender, ResolveEventArgs args)
   at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)
```

I also get the exact same error if I replace all of my code with the E2E sample above.

I'm using:

* `C:\Temp\VSTest\packages\Microsoft.TestPlatform.15.0.0\tools\net46\vstest.console.exe` as the runner path
* `C:\Temp\ExampleXUnitTestProject\ExampleXUnitTestProject\bin\Debug\netcoreapp1.1\xunit.runner.visualstudio.dotnetcore.testadapter.dll` as the test adapter path
* `C:\Temp\ExampleXUnitTestProject\ExampleXUnitTestProject\bin\Debug\netcoreapp1.1\ExampleXUnitTestProject.dll` as the test assembly.

**Comment by Faizan2304** [comment]
@yaakov-h : I am looking into it, will update you soon.

**Comment by Faizan2304** [comment]
@yaakov-h here is the working code 
```csharp
using System;
using System.Collections.Generic;
using System.IO;
using Microsoft.TestPlatform.VsTestConsole.TranslationLayer;
using Microsoft.VisualStudio.TestPlatform.ObjectModel;
using Microsoft.VisualStudio.TestPlatform.ObjectModel.Client;
using Microsoft.VisualStudio.TestPlatform.ObjectModel.Logging;

namespace VSTest
{
    class Program
    {
        static void Main(string[] args)
        {
            var vstestConsolePath = @"E:\Enlistments\vstest\artifacts\Debug\net46\win7-x64\vstest.console.exe";
            var consoleParameters = new ConsoleParameters
            {
                LogFilePath = Path.Combine(Environment.CurrentDirectory, $"VSTestLog_{DateTime.Now:yyyyMMdd-HHmmss}.log")
            };
            var wrapper = new VsTestConsoleWrapper(vstestConsolePath, consoleParameters);

            var source = @"C:\Users\faahmad\Documents\Visual Studio 2017\Projects\UnitTestProject7\UnitTestProject7\bin\Debug\netcoreapp1.1\UnitTestProject7.dll";
            var sources = new[] { source };

            var runSettingsXml = @"<RunSettings>
                                        <RunConfiguration>
                                            <TargetFrameworkVersion>FrameworkCore10</TargetFrameworkVersion>
                                        </RunConfiguration>
                                    </RunSettings>";
            var discoverySettings = runSettingsXml;

            wrapper.StartSession();

            var adapterPaths = new List<string>();
            adapterPaths.Add(@"C:\Users\faahmad\Documents\Visual Studio 2017\Projects\UnitTestProject7\UnitTestProject7\bin\Debug\netcoreapp1.1\Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.dll");

            wrapper.InitializeExtensions(adapterPaths);

            wrapper.DiscoverTests(sources, discoverySettings, new TestDiscoveryEventsHandler());
        }

        class TestDiscoveryEventsHandler : ITestDiscoveryEventsHandler
        {
            public void HandleDiscoveredTests(IEnumerable<TestCase> discoveredTestCases)
            {
                foreach (var testCase in discoveredTestCases)
                {
                    Console.WriteLine($"Discovered test case: {testCase.FullyQualifiedName}");
                }
            }

            public void HandleDiscoveryComplete(long totalTests, IEnumerable<TestCase> lastChunk, bool isAborted)
            {
                if (lastChunk != null)
                {
                    foreach (var testCase in lastChunk)
                    {
                        Console.WriteLine($"Discovered test case: {testCase.FullyQualifiedName}");
                    }
                }

                Console.WriteLine("Discovery completed.");
            }

            public void HandleLogMessage(TestMessageLevel level, string message)
            {
                Console.WriteLine($"Log message: [{level}] {message}");
            }

            public void HandleRawMessage(string rawMessage)
            {
                Console.WriteLine($"Raw message: {rawMessage}");
            }
        }
    }
}
```

Thinks to be take care:
1) The project for which you are running test is targeting netcoreapp, so you need to pass this information to runner via runsetting file.

2) Some test result can come as part of `DiscoveryComplete` event.

3) For project targeting netcoreapp there is no need to pass testadapterfullpath through initialize extension (`wrapper.InitializeExtensions`) but due to bug https://github.com/Microsoft/vstest/issues/823 you are hitting that exception.  Once the above bug will get fixed you don't need to call 
```csharp
wrapper.StartSession();
wrapper.InitializeExtensions(adapterPaths);
```
before calling `wrapper.DiscoverTests(sources, discoverySettings, new TestDiscoveryEventsHandler())` for test project targeting netcoreapp.

**Comment by yaakov-h** [comment]
Thanks @Faizan2304, I'll try that shortly.

Is the discovery settings XML documented anywhere?

**Comment by Faizan2304** [comment]
Detail doc here : https://msdn.microsoft.com/en-us/library/jj635153.aspx

**Comment by yaakov-h** [comment]
@Faizan2304 Thanks, that xml was the magic I was missing. It now works like a charm.

Are there any plans to publish `Microsoft.TestPlatform` to nuget.org?

**Comment by Faizan2304** [comment]
@yaakov-h We don't have any immediate plan to publish `Microsoft.TestPlatform` to nuget.org but we will publish in near future.

If you want to use/dogfood latest TPV2 then you can use myget feed https://dotnet.myget.org/F/vstest/api/v3/index.json to get `Microsoft.TestPlatform`  package. We keep uploading our daily build there.

**Comment by yaakov-h** [comment]
@Faizan2304 OK, thank you.

**Comment by luis-cortina** [comment]
Any news on publishing `Microsoft.TestPlatform` to nuget? 
There is a package `Microsoft.TestPlatform.CLI` which contains a `vstest.console.dll` but when I tried to use that with the apporach above I had the same error that started this issue.
`Message=Error connecting to Vstest Command Line`

If that package is not available on nuget it means we'd have to install VS on the machine we intend to run the code, where as just including it as part of the tool we are building will be the best approach.

Help?

Luis

**Comment by Faizan2304** [comment]
@codito  @pvlakshm

**Comment by Faizan2304** [comment]
@luis-cortina 
>Any news on publishing Microsoft.TestPlatform to nuget?

Unfortunately no

>If that package is not available on nuget it means we'd have to install VS on the machine we intend to run the code, where as just including it as part of the tool we are building will be the best approach.

If you want to use/dogfood latest TPV2 then you can use myget feed https://dotnet.myget.org/F/vstest/api/v3/index.json to get Microsoft.TestPlatform package. We keep uploading our daily build there.

**Comment by Faizan2304** [comment]
@luis-cortina : we have created this issue https://github.com/Microsoft/vstest/issues/910 to track your request to publish Microsoft.TestPlatform to nuget.
