### ISSUE TITLE
.NET Core xUnit LUT stops working by NullReferenceException after adding a new project 

### ISSUE THREAD

**Issue by MiaomiaoHuangfu** [Microsoft/vstest#842]
## Steps to reproduce
1. > Create a xUnit Test (.NET Core) project;
2. > Click the "Start" of "Live Unit Testing" under Test down list;
3. > Right click the solution and add new project, choose the template "Class Library (.NET Standard)" under ".NET Standard" node
4. >Then the output window throw an fatal error "FatalError - System.NullReferenceException: Object reference not set to an instance of an object." then live unit testing stopped:
 `	FatalError - System.NullReferenceException: Object reference not set to an instance of an object.
 	   at Microsoft.VisualStudio.LiveUnitTesting.Setup.MSBuildProvider.<>c__DisplayClass0_0.<<Microsoft-CodeAnalysis-LiveUnitTesting-IMSBuildProvider-TryExecuteGuardedProjectAction>b__1>d.MoveNext()
 	--- End of stack trace from previous location where exception was thrown ---
 	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 	   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
 	   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
 	   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
 	   at Microsoft.VisualStudio.LiveUnitTesting.Setup.MSBuildProvider.Microsoft.CodeAnalysis.LiveUnitTesting.IMSBuildProvider.TryExecuteGuardedProjectAction(String projectFilePath, Project project, Action`1 action)
 	   at Microsoft.CodeAnalysis.LiveUnitTesting.SolutionManager.GetOrAddProjectNode(String projectFilePath, Project project)
 	   at Microsoft.CodeAnalysis.LiveUnitTesting.SolutionManager.<>c__DisplayClass21_0.<GenerateProjectDependencyGraph>b__4(Project p)
 	   at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
 	   at Microsoft.CodeAnalysis.LiveUnitTesting.SolutionManager.GenerateProjectDependencyGraph()
 	   at Microsoft.CodeAnalysis.LiveUnitTesting.BuildManagement.BuildManagerState.<BuildAsync>d__86.MoveNext()
 [23:41:00.457 Info] Live Unit Testing stopped.`
   > ![xunitreferenceerror](https://cloud.githubusercontent.com/assets/22901391/26820991/63e510be-4ad7-11e7-99e3-dcba5333bfa5.PNG) 
5. >Restart the "Live Unit Testing";
6. >Add reference from xUnit to standard class library;
7. >From xunit calling the method of standard class, then live unit testing glyphs show up in the margin next to most lines of code in the xunit, but which don't show in .net standard class:
   > ![xunitreferencegglyphs](https://cloud.githubusercontent.com/assets/22901391/26821019/8093a0e0-4ad7-11e7-8545-2332ee9d7408.PNG)
>

## Expected behavior
> LUT works even if adding a new project

## Environment
> Install d15prerel.26605.02;
> Install latest CLI/SDK 2.0. from https://github.com/dotnet/cli/tree/release/2.0.0 
> Build version of vstest.console: 15.0.26605.02
> dotnet --info 
> ```
> .NET Command Line Tools (2.0.0-preview2-006341)
> 
> Product Information:
>  Version:            2.0.0-preview2-006341
>  Commit SHA-1 hash:  19d305783b
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.14393
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\2.0.0-preview2-006341\
> 
> Microsoft .NET Core Shared Framework Host
> 
>   Version  : 2.0.0-preview2-25402-02
>   Build    : 3c440c8947e7776b2c7772bcb98b3bc73e1b9193
> ```

**Comment by Faizan2304** [comment]
This is LUT issue. moving it to their repo: https://github.com/dotnet/testimpact/issues/1894
