### ISSUE TITLE
Test runner fails checking protocol version on osx

### ISSUE THREAD

**Issue by chuckb** [Microsoft/vstest#921]
## Description
When I attempt to run an xunit test project with "dotnet test", I get a stack trace with the error: Unhandled Exception: System.IO.EndOfStreamException: Unable to read beyond the end of the stream.

## Steps to reproduce
- Create a test project targeting net46.
- Run the test on osx.

## Expected behavior
The test should execute.

## Actual behavior
```
charles-benedicts-macbook:Disbursals.Facts chuck_benedict$ dotnet test -d:log.txt
Build started, please wait...
Build completed.

Test run for /Users/chuck_benedict/Projects/p15/sd-prototype/test/Disbursals.Facts/bin/Debug/net46/osx.10.12-x64/Disbursals.Facts.dll(.NETFramework,Version=v4.6)
Microsoft (R) Test Execution Command Line Tool Version 15.3.0-preview-20170703-02
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
Logging Vstest Diagnostics in file: /Users/chuck_benedict/Projects/p15/sd-prototype/test/Disbursals.Facts/log.txt

Unhandled Exception: System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.__Error.EndOfFile()
   at System.IO.BinaryReader.ReadByte()
   at System.IO.BinaryReader.Read7BitEncodedInt()
   at System.IO.BinaryReader.ReadString()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.SocketCommunicationManager.ReceiveMessage()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.TestRequestSender.CheckVersionWithTestHost()
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyExecutionManager.InitializeExtensions(IEnumerable`1 sources)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyExecutionManager.Initialize()
   at Microsoft.VisualStudio.TestPlatform.Client.TestPlatform.CreateTestRunRequest(TestRunCriteria testRunCriteria, ProtocolConfig protocolConfig)
   at Microsoft.VisualStudio.TestPlatform.CommandLine.TestPlatformHelpers.TestRequestManager.RunTests(TestRunCriteria testRunCriteria, ITestRunEventsRegistrar testRunEventsRegistrar, ProtocolConfig protocolConfig)
   at Microsoft.VisualStudio.TestPlatform.CommandLine.TestPlatformHelpers.TestRequestManager.RunTests(TestRunRequestPayload testRunRequestPayload, ITestHostLauncher testHostLauncher, ITestRunEventsRegistrar testRunEventsRegistrar, ProtocolConfig protocolConfig)
   at Microsoft.VisualStudio.TestPlatform.CommandLine.Processors.RunTestsArgumentExecutor.RunTests(IEnumerable`1 sources)
   at Microsoft.VisualStudio.TestPlatform.CommandLine.Processors.RunTestsArgumentExecutor.Execute()
   at Microsoft.VisualStudio.TestPlatform.CommandLine.Executor.ExecuteArgumentProcessor(IArgumentProcessor processor, Int32& exitCode)
   at Microsoft.VisualStudio.TestPlatform.CommandLine.Executor.Execute(String[] args)
   at Microsoft.VisualStudio.TestPlatform.CommandLine.Program.Main(String[] args)
```
Output from the dotnet test log file follows:

```
TpTrace Information: 0 : 4858, 2, 2017/07/10, 08:26:52.847, 76370040354000, vstest.console.dll, Using .Net Framework version:.NETFramework,Version=v4.6
TpTrace Information: 0 : 4858, 2, 2017/07/10, 08:26:52.855, 76370046336000, vstest.console.dll, Using platform:X64
TpTrace Verbose: 0 : 4858, 2, 2017/07/10, 08:26:52.876, 76370066886000, vstest.console.dll, TestPluginCache: Discovering the extensions using extension path.
TpTrace Information: 0 : 4858, 2, 2017/07/10, 08:26:52.877, 76370067554000, vstest.console.dll, AssemblyResolver: Microsoft.TestPlatform.TestHostRuntimeProvider: Resolving assembly.
TpTrace Information: 0 : 4858, 2, 2017/07/10, 08:26:52.877, 76370068037000, vstest.console.dll, AssemblyResolver: Microsoft.TestPlatform.TestHostRuntimeProvider: Resolved assembly. 
TpTrace Information: 0 : 4858, 2, 2017/07/10, 08:26:52.878, 76370069269000, vstest.console.dll, AssemblyResolver: Microsoft.VisualStudio.TestPlatform.Extensions.Trx.TestLogger: Resolving assembly.
TpTrace Information: 0 : 4858, 2, 2017/07/10, 08:26:52.879, 76370069682000, vstest.console.dll, AssemblyResolver: Microsoft.VisualStudio.TestPlatform.Extensions.Trx.TestLogger: Resolved assembly. 
TpTrace Verbose: 0 : 4858, 2, 2017/07/10, 08:26:52.880, 76370070702000, vstest.console.dll, TestPluginCache: Discovered the extensions using extension path ''.
TpTrace Verbose: 0 : 4858, 2, 2017/07/10, 08:26:52.880, 76370070768000, vstest.console.dll, TestPluginCache: Discoverers are ''.
TpTrace Verbose: 0 : 4858, 2, 2017/07/10, 08:26:52.880, 76370070811000, vstest.console.dll, TestPluginCache: Executors are ''.
TpTrace Verbose: 0 : 4858, 2, 2017/07/10, 08:26:52.880, 76370070848000, vstest.console.dll, TestPluginCache: Setting providers are ''.
TpTrace Verbose: 0 : 4858, 2, 2017/07/10, 08:26:52.880, 76370070889000, vstest.console.dll, TestPluginCache: Loggers are ''.
TpTrace Information: 0 : 4858, 2, 2017/07/10, 08:26:52.892, 76370083223000, vstest.console.dll, RunTestsArgumentProcessor:Execute: Test run is starting.
TpTrace Verbose: 0 : 4858, 2, 2017/07/10, 08:26:52.892, 76370083358000, vstest.console.dll, RunTestsArgumentProcessor:Execute: Queuing Test run.
TpTrace Information: 0 : 4858, 2, 2017/07/10, 08:26:52.893, 76370083878000, vstest.console.dll, TestRequestManager.RunTests: run tests started.
TpTrace Verbose: 0 : 4858, 2, 2017/07/10, 08:26:52.929, 76370120392000, vstest.console.dll, TestPluginCache: Updating loadOnlyWellKnownExtensions from False to True.
TpTrace Verbose: 0 : 4858, 2, 2017/07/10, 08:26:52.930, 76370120667000, vstest.console.dll, TestPluginCache: Using directories for assembly resolution '/Users/chuck_benedict/Projects/p15/sd-prototype/test/Disbursals.Facts/bin/Debug/net46/osx.10.12-x64'.
TpTrace Verbose: 0 : 4858, 2, 2017/07/10, 08:26:52.930, 76370120740000, vstest.console.dll, TestPluginCache: Updated the available extensions to '/Users/chuck_benedict/Projects/p15/sd-prototype/test/Disbursals.Facts/bin/Debug/net46/osx.10.12-x64/xunit.runner.visualstudio.testadapter.dll'.
TpTrace Verbose: 0 : 4858, 2, 2017/07/10, 08:26:52.932, 76370123386000, vstest.console.dll, TestPluginCache: Updating loadOnlyWellKnownExtensions from True to True.
TpTrace Verbose: 0 : 4858, 2, 2017/07/10, 08:26:52.933, 76370123512000, vstest.console.dll, TestPluginCache: Using directories for assembly resolution '/usr/local/share/dotnet/sdk/2.1.0-preview1-006723/Extensions,/Users/chuck_benedict/Projects/p15/sd-prototype/test/Disbursals.Facts/bin/Debug/net46/osx.10.12-x64'.
TpTrace Verbose: 0 : 4858, 2, 2017/07/10, 08:26:52.933, 76370123568000, vstest.console.dll, TestPluginCache: Updated the available extensions to '/usr/local/share/dotnet/sdk/2.1.0-preview1-006723/Extensions/Microsoft.VisualStudio.TestPlatform.Extensions.Trx.TestLogger.dll,/usr/local/share/dotnet/sdk/2.1.0-preview1-006723/Extensions/Microsoft.TestPlatform.TestHostRuntimeProvider.dll,/Users/chuck_benedict/Projects/p15/sd-prototype/test/Disbursals.Facts/bin/Debug/net46/osx.10.12-x64/xunit.runner.visualstudio.testadapter.dll'.
TpTrace Information: 0 : 4858, 2, 2017/07/10, 08:26:52.944, 76370135171000, vstest.console.dll, TestPluginManager.CreateTestExtension: Attempting to load test extension: Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DefaultTestHostManager
TpTrace Verbose: 0 : 4858, 2, 2017/07/10, 08:26:52.945, 76370135838000, vstest.console.dll, TestEngine: Initializing Parallel Execution as MaxCpuCount is set to: 1
TpTrace Verbose: 0 : 4858, 2, 2017/07/10, 08:26:52.950, 76370140525000, vstest.console.dll, ProxyExecutionManager: Test host is shared. SetupChannel it early.
TpTrace Information: 0 : 4858, 2, 2017/07/10, 08:26:52.957, 76370147906000, vstest.console.dll, Listening on port : 53738
TpTrace Verbose: 0 : 4858, 2, 2017/07/10, 08:26:52.967, 76370158437000, vstest.console.dll, DefaultTestHostmanager: Full path of TestHost/testhost.exe is /usr/local/share/dotnet/sdk/2.1.0-preview1-006723/Extensions/..//TestHost/testhost.exe
TpTrace Verbose: 0 : 4858, 4, 2017/07/10, 08:26:52.971, 76370161910000, vstest.console.dll, Launching default test Host Process /Library/Frameworks/Mono.framework/Versions/Current/Commands/mono with arguments /usr/local/share/dotnet/sdk/2.1.0-preview1-006723/Extensions/..//TestHost/testhost.exe  --port 53738 --parentprocessid 4858 --diag "/Users/chuck_benedict/Projects/p15/sd-prototype/test/Disbursals.Facts/log.host.17-07-10_08-26-52_96440_2.txt"
TpTrace Verbose: 0 : 4858, 4, 2017/07/10, 08:26:52.971, 76370162009000, vstest.console.dll, DefaultTestHostManager: Starting process '/Library/Frameworks/Mono.framework/Versions/Current/Commands/mono' with command line '/usr/local/share/dotnet/sdk/2.1.0-preview1-006723/Extensions/..//TestHost/testhost.exe  --port 53738 --parentprocessid 4858 --diag "/Users/chuck_benedict/Projects/p15/sd-prototype/test/Disbursals.Facts/log.host.17-07-10_08-26-52_96440_2.txt"'
TpTrace Verbose: 0 : 4858, 4, 2017/07/10, 08:26:52.977, 76370168254000, vstest.console.dll, Test Runtime launched with Pid: 4859
TpTrace Information: 0 : 4858, 6, 2017/07/10, 08:26:53.207, 76370398487000, vstest.console.dll, Accepted Client request and set the flag
```
Testhost log output follows:
```
TpTrace Information: 0 : 4859, 1, 2017/07/10, 08:26:53.172, 133792947967, testhost.exe, DefaultEngineInvoker: Using Application Configuration: '<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <startup useLegacyV2RuntimeActivationPolicy="true">
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.0" />
  </startup>
  <runtime>
    <legacyUnhandledExceptionPolicy enabled="1" />
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <probing privatePath="Extensions" />
      <!-- Test adapters compiled against version 11-14, need to be redirected to version 15. -->
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.VisualStudio.TestPlatform.ObjectModel" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="11.0.0.0-14.0.0.0" newVersion="15.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.VisualStudio.TestWindow.Interfaces" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="11.0.0.0-14.0.0.0" newVersion="15.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.VisualStudio.QualityTools.UnitTestFramework" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="10.1.0.0" newVersion="10.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.VisualStudio.QualityTools.Resource" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="10.0.0.0-14.0.0.0" newVersion="15.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.VisualStudio.QualityTools.ControllerObject" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="10.0.0.0-14.0.0.0" newVersion="15.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.VisualStudio.QualityTools.ExecutionCommon" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="10.0.0.0-14.0.0.0" newVersion="15.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.VisualStudio.QualityTools.Common" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="10.0.0.0-14.0.0.0" newVersion="15.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Collections.Immutable" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="1.1.37.0" newVersion="1.2.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
  <system.diagnostics>
    <switches>
      <add name="TpTraceLevel" value="0" />
    </switches>
  </system.diagnostics>
  <appSettings>
    <!--<add key="ExecutionThreadApartmentState" value ="MTA"/>-->
    <!--<add key="TraceLogMaxFileSizeInKb" value ="10240"/>-->
    <!-- MsTest Adapter Specific AppSettings -->
    <add key="TestProjectRetargetTo35Allowed" value="true" />
  </appSettings>
</configuration>'
TpTrace Information: 0 : 4859, 1, 2017/07/10, 08:26:53.187, 133793062808, testhost.exe, DefaultEngineInvoker: Monitoring parent process with id: '4858'
TpTrace Information: 0 : 4859, 1, 2017/07/10, 08:26:53.190, 133793090982, testhost.exe, DefaultEngineInvoker: Initialize communication on port number: '53738'
TpTrace Information: 0 : 4859, 1, 2017/07/10, 08:26:53.194, 133793134351, testhost.exe, Trying to connect to server on port : 53738
TpTrace Information: 0 : 4859, 5, 2017/07/10, 08:26:53.195, 133793140536, testhost.exe, DefaultEngineInvoker: ParentProcess '4858' Exited.
TpTrace Information: 0 : 4859, 1, 2017/07/10, 08:26:53.207, 133793264334, testhost.exe, DefaultEngineInvoker: Start Request Processing.
```

## Environment
```
charles-benedicts-macbook:Disbursals.Facts chuck_benedict$ dotnet --info
.NET Command Line Tools (2.1.0-preview1-006723)

Product Information:
 Version:            2.1.0-preview1-006723
 Commit SHA-1 hash:  7e1fe7eba7

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.0-preview1-006723/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview3-25502-01
  Build    : bd3f818bad84f1296b4ee53f72ab8837b3caac98
```
```
charles-benedicts-macbook:Disbursals.Facts chuck_benedict$ mono --version
Mono JIT compiler version 4.6.2 (mono-4.6.0-branch/ac9e222 Wed Dec 14 17:02:09 EST 2016)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           normal
        SIGSEGV:       altstack
        Notification:  kqueue
        Architecture:  x86
        Disabled:      none
        Misc:          softdebug
        LLVM:          yes(3.6.0svn-mono-master/8b1520c)
        GC:            sgen
```

**Comment by chuckb** [comment]
What I have noted is that the exit handler for the parent process within the TestHost is being triggered even though the parent process is still alive (note the time stamps of log information between the two log files).  I also noted that there seemed to be a known issue in mono (that was presumably corrected) with process exit handling on mac (https://github.com/mono/mono/pull/1691/files).  I am researching this further...

**Comment by chuckb** [comment]
I removed mono 4.6.2 and then installed 5.0.1.1.  This problem goes away, however now I get another problem, which I will document separately.

**Comment by codito** [comment]
@chuckb please let us know your findings on other issue. We will add mono 5.0.1.1 as a pre-requisite for dotnet test for net46 testing.

**Comment by chuckb** [comment]
I am cross posting for those brave souls trying to develop on mac targeting net46 and use xunit.  I did finally get it to work.  See https://github.com/xunit/xunit/issues/1357
