### ISSUE TITLE
Facades are no longer output for netfx tests referencing netstandard1.3 libs

### ISSUE THREAD

**Issue by gulbanana** [Microsoft/vstest#998]
## Description
Package Microsoft.CodeAnalysis.Compilers has a netstandard1.3 dep on System.Security.Cryptography.Algorithms. Using the 1.1 sdk and vstest 15.0, this assembly was copied to the test output and could be loaded at runtime. Using 2.0/15.3, neither the assembly nor any facades are present in the output.

## Steps to reproduce
1. Clone the repo at https://github.com/gulbanana/repro-vstest-netstandard-on-net461
2. `dotnet test`

## Expected behavior
The unit test should pass.

## Actual behavior
```
Failed   XUnitTestProject1.UnitTest1.Test1
Error Message:
 System.IO.FileNotFoundException : Could not load file or assembly 'System.Security.Cryptography.Algorithms, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
---- System.IO.FileNotFoundException : Could not load file or assembly 'System.Security.Cryptography.Algorithms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
Stack Trace:
   at Microsoft.CodeAnalysis.CryptographicHashProvider.ComputeSha1(Byte[] bytes)
   at Microsoft.CodeAnalysis.AssemblyIdentity.CalculatePublicKeyToken(ImmutableArray`1 publicKey)
   at Microsoft.CodeAnalysis.AssemblyIdentity.get_PublicKeyToken()
   at XUnitTestProject1.UnitTest1.Test1() in C:\code\repro-vstest-netstandard-on-net461\XUnitTestProject1\UnitTest1.cs:line 13
----- Inner Stack Trace -----
```

## Environment
`$ dotnet --info`
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

`dotnet test /version`
15.3.409.5702515.3.409.57025

**Comment by gulbanana** [comment]
I suspect this bug is the underlying cause of #655

**Comment by gulbanana** [comment]
This could also be caused by or related to https://github.com/dotnet/corefx/issues/23344

**Comment by gulbanana** [comment]
hopefully it's fixed, then
